### ISSUE TITLE
I want  back to the map page without executing onMapReady

### ISSUE THREAD

**Issue by ghost** [Yermo/nativescript-mapbox#100]
Hello!
I now encounter a problem, I return to another page in the map page, the map page onMapReady event implementation, I use the Angular2, the routing socket is used in the <page-router-outlet> </ page-router-outlet > This is the cache, the components of the Hook are not implemented, only onMapReady event implementation. Is there any solution?

**Comment by EddyVerbruggen** [comment]
Please share a repo for issues like this.
