### ISSUE TITLE
Map labels not displayed

### ISSUE THREAD

**Issue by j99ht** [Yermo/nativescript-mapbox#101]
When the same mapbox style is shown on two different Android devices, in one of them, some labels are not displayed. I'm attaching screenshots.
Can anybody help out on how to fix this?
![screenshot](https://cloud.githubusercontent.com/assets/13207577/24453626/f858086c-1488-11e7-929e-0ed707943ef3.png)
![screenshot_2017-03-29-13-56-36](https://cloud.githubusercontent.com/assets/13207577/24453627/f85afe78-1488-11e7-9d76-0e722205b074.png)

**Comment by EddyVerbruggen** [comment]
That's really a question for the mapbox sdk guys.
