### ISSUE TITLE
Plugin not adding telemetry service in manifest, map not showing

### ISSUE THREAD

**Issue by idomaz00** [Yermo/nativescript-mapbox#102]
When I add plugin version 2.6.1 to my project (nativescript and angular2) it doesn't want to even start, I get : 

BUILD FAILED
Total time: 43.729 secs
Command /Users/izabela/Documents/projekti/NativeScript/NativeScriptGeolocation/platforms/android/gradlew failed with exit code 1

When I try adding an older version of this plugin 2.3.1. (that works in a project I created cca 20 days ago) my app starts but crashes, I see mapbox logo but not a map and then it crashes. This older version doesn't add telemetry service to my manifest file and when I add it by hand if still doesn't work. 
I am testing my app on a real device (Nexus 5x Android ver. 7.1.2). And developing on Mac OsX El Capitan. I didn't add ios platform to my project, I currently only need Android

Funny thing is that a testing app I created 20 days ago still works fine

**Comment by EddyVerbruggen** [comment]
What plugin version is on that testing app, and did you add the TelemetryService to App_Resources/Android/AndroidManifest.xml in that case?

**Comment by idomaz00** [comment]
hi, I am sorry about the late answer, I had to work on another project...that testing project was with plugin version 2.3.1 that is why I tried it again in this new project. Today I tried again with the latest plugin version 3.0.0 and it still gives me the same error. In all cases I added telemetry service in manifest file but it didn't help. 
My old app with 2.3.1 version of that plugin still works fine.

**Comment by idomaz00** [comment]
Update: I tried everything again on a Windows laptop, it runs your demo app with no problems so the problem I described earlier must be a problem with my environment. 
The only thing that is still strange is that it does not add telemetry service to manifest file, but the app still works. 
I guess you can close the issue
