### ISSUE TITLE
onMapReady called several times IOS

### ISSUE THREAD

**Issue by j99ht** [Yermo/nativescript-mapbox#103]
I have declared a map in XML
```
<map:Mapbox xmlns:map="nativescript-mapbox"
   accessToken="{{ map.accessToken }}"
   mapStyle="{{ map.mapStyle }}"
   showUserLocation="true"
   hideLogo="true"
   mapReady="onMapReady">
</map:Mapbox>
```
Debugging my app (IOS version) I realized that the code goes up to 3 times to onMapReady function.

Inside onMapReady I am setting zoom level and map center coordinates and I set a timer to re-paint the markers every x seconds.
```
 timeoutID = timer.setTimeout(function () {
                that.drawMapPeriodically();
            }, remainingRefreshPeriod);
```
When the map is shown (this is not always happening), it does not react to clicks or dragging and I believe this is caused for loading onMapReady several times (so there are several timers that could make the app not working properly).

However, in Android I do not have these issues (onMapReady is called only once and map is reacting)

Any idea about why onMapReady is being called so many times in IOS?  (in Mapbox demo I see there are up to 6 calls)

**Comment by EddyVerbruggen** [comment]
I haven't confirmed your finding, but I can imagine it happens. I will fix this for the NativeScript 3-compatible version that I'm working on next week (update: [PR for iOS](https://github.com/EddyVerbruggen/nativescript-mapbox/pull/104) is ready, need to work on Android next).

**Comment by GrEg00z** [comment]
Same issue than @j99ht 
I put a flag to prevent multiple call inside onMapReady

**Comment by EddyVerbruggen** [comment]
This is probably fixed with the 3.0.0 that's NativeScript 3 compatible. Please let me know if this issue remains after trying that one.

**Comment by j99ht** [comment]
How can I install tns-core-modules3 before NativeScript3 is available? 
I'm getting this when I'm trying to install nativescript-mapbox 3..0.0
`nativescript-mapbox@3.0.0 requires a peer of tns-core-modules@^3.0.0 || ^3.0.0-rc.1 || ^3.0.0-rc.2 || >=3.0.0-2017 but none was installed.`

**Comment by EddyVerbruggen** [comment]
@j99ht `npm install -g nativescript@rc` will get you the latest release candidate of the CLI. Same trick can be done for the core modules.

**Comment by j99ht** [comment]
Getting this 

> JS ERROR TypeError: undefined is not an object (evaluating 'application.resources._L = _L')

I have used this
```
┌──────────────────┬────────────────────────┬────────────────┬─────────────┐
│ Component        │ Current version        │ Latest version │ Information │
│ nativescript     │ 3.0.0-rc.2             │ 2.5.4          │ Up to date  │
│ tns-core-modules │ 3.0.0-rc.2             │ 2.5.2          │ Up to date  │
│ tns-android      │ 2.5.0                  │ 2.5.0          │ Up to date  │
│ tns-ios          │ 3.0.0-rc.1-2017-3-28-2 │ 2.5.0          │ Up to date  │
└──────────────────┴────────────────────────┴────────────────┴─────────────┘
```

**Comment by EddyVerbruggen** [comment]
When does that pop up?

Did you completely remove the node_modules and platforms folders?

**Comment by j99ht** [comment]
When the app is about to start. It shows the splash screen but nothing else (a map should be shown).

The complete logs

```
Project successfully built.
Installing...
Successfully installed on device with identifier '1F6A5938-C48E-4FF1-907E-BBC65794D131'.
Transferring project files...
Successfully transferred all files.
Refreshing application...
No matching processes belonging to you were found
Successfully synced application com.myapp.mapapp on device 1F6A5938-C48E-4FF1-907E-BBC65794D131.

objc[37139]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x1274a7cc0) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x1272be6f0). One of the two will be used. Which one is undefined.
1   0x10f6db33c -[TNSRuntime executeModule:referredBy:]
2   0x10edeb359 main
3   0x1145e865d start
4   0x1
file:///app/tns_modules/tns-i18n/index.js:25:26: JS ERROR TypeError: undefined is not an object (evaluating 'application.resources._L = _L')
Apr 28 12:13:13 myapple.apple.CoreSimulator.SimDevice.1F6A5938-C48E-4FF1-907E-BBC65794D131.launchd_sim[28889] (UIKitApplication:com.myapp.mapapp[0xb014][28915][37139]): Service exited due to Segmentation fault: 11
```

**Comment by EddyVerbruggen** [comment]
That's unrelated to this plugin so it must be something wrong in the build. Did you completely remove the node_modules and platforms folders?

**Comment by j99ht** [comment]
It works now. Thanks.
