### ISSUE TITLE
iOS : mapBox very slow and app crash often

### ISSUE THREAD

**Issue by GrEg00z** [Yermo/nativescript-mapbox#105]
On iOS, mapbox looks very slow and long to react, compared to android version.

Also app often crash after multiple `tns run ios`, without display any error

Here is version I use :
 - iPhone 6 (version 10.2 (14C92)
 - nativescript mapbox : 2.6.1
 - tns info : 
   * angular : 2.4.3
   * nativescript : 2.5.4 │ Up to date
   * tns-core-modules : 2.5.2 │ Up to date
   * tns-android : 2.5.0 │ Up to date
   * tns-ios : 2.5.0 │ Up to date

**Comment by EddyVerbruggen** [comment]
Which Mapbox plugin version?

**Comment by GrEg00z** [comment]
2.6.1

**Comment by sowrabhbs** [comment]
@GrEg00z are u using mapbox using xml or ts??

**Comment by GrEg00z** [comment]
I use angular so I write the mapBox in my html view component (and register element mapBox in ts file component)

But I'm switching to 3.0.0 so I will tell you if it resolves the problem

**Comment by d3mac123** [comment]
I am having the same problem here with iOS (running tns 2.5.0 and mapbox 2.6.1). Difference is my Android does not even compile:
/platforms/android/build/intermediates/res/merged/F0F1F2F3F4F5/debug/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

**Comment by GrEg00z** [comment]
I confirm the problem is no more present while using 
 - Nativescript 3.0.1 
 - nativescript-mapbox 3.0.0

👍 👍
