### ISSUE TITLE
angular webpack

### ISSUE THREAD

**Issue by ButterMeWaffle** [Yermo/nativescript-mapbox#106]
Is there any info on using this plugin with NG + webpack? 

Thanks

**Comment by EddyVerbruggen** [comment]
The Travis config in this repo has a webpack target and that's working fine without any special modifications. Also, [this app](https://github.com/EddyVerbruggen/nativescript-pluginshowcase) is an Angular app with Mapbox and Webpack and is published to the stores without problems.
