### ISSUE TITLE
Full screen map not shown in v3.0.0

### ISSUE THREAD

**Issue by j99ht** [Yermo/nativescript-mapbox#107]
If I define the map with 
       ` <ContentView height="240" width="240">`
the map is correctly shown.

However if I set `<ContentView>` to have a full screen map, the map is not shown.

This was working on previous versions. Is there any change in v3.0.0 I should take into account?

**Comment by EddyVerbruggen** [comment]
Could be changed indeed. Is this iOS?

How did you previously defined the fullscreen map?

**Comment by j99ht** [comment]
Yes, it is IOS.

I did it in this way

```
<GridLayout rows="*,auto,auto,auto" columns="*">
   <ContentView row="0" col="0">
      <map:MapboxView xmlns:map="nativescript-mapbox"
                <!-- my map definition -->
      </map:MapboxView> 
   </ContentView>
   <!-- rest of rows and columns -->
</GridLayout>
```

**Comment by EddyVerbruggen** [comment]
And what does it look like?

**Comment by j99ht** [comment]
Now,

![image](https://cloud.githubusercontent.com/assets/13207577/25528860/f53f8bec-2c1f-11e7-82b8-95b0b97de126.png)


Before (in the new one I have removed all the others elements)
![image](https://cloud.githubusercontent.com/assets/13207577/25528877/02e4dbb2-2c20-11e7-9966-3428bf597bb4.png)

2017-04-28 14:24 GMT+02:00 Eddy Verbruggen <notifications@github.com>:

**Comment by EddyVerbruggen** [comment]
Thx, I have an idea why this changed.

**Comment by slushnys** [comment]
@j99ht if you're using angular2:
`import {screen, device} from 'platform';`

then in the your component define the height of your screen like this:

`
let mapHeight : number = 0;
    constructor() {
        this.mapHeight = screen.mainScreen.heightPixels;
    }
`
In your `<ContentView [height]="mapHeight"></ContentView>`


Let me know if that helps.

**Comment by EddyVerbruggen** [comment]
I was just looking at an app that had the following alomost-fullscreen layout working nicely on iOS:

```html
<StackLayout>
    <Button text="load markers" (tap)="loadPoints()"></Button>
    <ContentView height="100%" width="100%">
      <Mapbox
          accessToken="the_token"
          mapStyle="dark"
          latitude="50.467735"
          longitude="13.427718"
          hideCompass="true"
          zoomLevel="18"
          showUserLocation="false"
          disableZoom="false"
          disableRotation="false"
          disableScroll="false"
          disableTilt="false"
          (mapReady)="onMapReady($event)">
      </Mapbox>
    </ContentView>
</StackLayout>
```
