### ISSUE TITLE
mapbox.common.d.ts(1,32) -- view.d.ts' is not a module.

### ISSUE THREAD

**Issue by EstebanErcole** [Yermo/nativescript-mapbox#110]
My applications stops when trying to access to the view module from the tns_core-modules. located on node_modules/tns-core-modules/ui/core/view.d.ts' is not a module.

the "view.d.ts" doesn't export any module but declares. Other plugins seams to work fine with this but not mapBox. Any ideas? 

Thanks in advance!!

**Comment by EddyVerbruggen** [comment]
Guessing this is no longer an issue.
