### ISSUE TITLE
Blank screen when I open the map

### ISSUE THREAD

**Issue by Dangradz** [Yermo/nativescript-mapbox#111]
When I open the page with the map I have a blank screen with no error in the console... I don't understand why

**Comment by EddyVerbruggen** [comment]
Would you mind providing some details? Like plugin version, iOS/Android, device, and most importantly: code.

**Comment by Dangradz** [comment]
I use my phone (android 7.0.0), the version of the plugin is 2.5.2, here the xml code:
 <StackLayout>
    <ContentView class="map">
          <map:MapboxView
          accessToken="sk.eyJ1IjoiZGFuZ3JhZCIsImEiOiJjajI4bjdmNDIwMDU1MnlvN2Q4YWQxdWpxIn0.g3JGcysbvTEnZzYBHIWqJw"
          mapStyle="Mapbox Streets"
          latitude="43"
          longitude="12"
          zoomLevel="14"
          showUserLocation="false"
          mapReady="onMapReady">
      </map:MapboxView>
    </ContentView>
  </StackLayout>

**Comment by EddyVerbruggen** [comment]
Version 2.5.2 doesn't use `map:MapboxView` but `map:Mapbox`, sorry for the inconvenience.
