### ISSUE TITLE
Icon path

### ISSUE THREAD

**Issue by Dangradz** [Yermo/nativescript-mapbox#112]
I have solved the previous issue, thank you very much... Now I would like to set a custom icon to the markers but it doesn't find the icon... where am I wrong?

here the code:

 map.addMarkers([
    {
      id: counter, 
      lat: lat, 
      lng: lng, 
      title: description, 
      iconPath: '~/images/map/markers/markerFood.png',
    }]);

    counter++;

**Comment by EddyVerbruggen** [comment]
The example says to not use the `~` prefix: `iconPath: 'res/markers/green_pin_marker.png'`.. can you try that?

**Comment by Dangradz** [comment]
also with "res" I have the same issue
this is the error:
JS: Marker icon not found, using the default instead. Requested full path: /data/data/org.nativescript.AppEtice/files/app/res/images/map/markers/markerFood.png

**Comment by EddyVerbruggen** [comment]
Show me a screenshot of the image at ` /data/data/org.nativescript.AppEtice/files/app/res/images/map/markers/markerFood.png` plz

**Comment by Dangradz** [comment]
Ok i have figured it out, I was doing wrong about the image location, actually I don't have a "res" folder, I changed the path to "images/map/markers/markerFood.png" and it works
