### ISSUE TITLE
Markers disappear on changing model

### ISSUE THREAD

**Issue by Dangradz** [Yermo/nativescript-mapbox#114]
I have inserted the map inside the xml of my home page... When I load the home page I insert some markers into the map, if I change module and I come back to the home page, I load the markers and then suddenly remove them, I don't understand why....
I thought maybe the system loads two maps, one over the other, so I have tried to use the method mapbox.destroy() and mapbox.hide() but both of them don't work

**Comment by Dangradz** [comment]
I have noticed that the marker disappear as soon as it is called that ChildListener of firebase (this events change my markers)

**Comment by EddyVerbruggen** [comment]
This really sounds like an issue in your app, not the plugin.
