### ISSUE TITLE
Android - Map not shown using Angular and v3.0.0

### ISSUE THREAD

**Issue by j99ht** [Yermo/nativescript-mapbox#115]
I have tried to run an example just showing a map using Angular, Nativescript 3 and nativescript-mapbox v3.0.0 but without success.

This is my code
app,component.html (or xml also tried)
```
<StackLayout>
    <ContentView height="240" width="240" backgroundColor="blue">
      <MapboxView
          accessToken="myToken"
          mapStyle="myStyle"
          latitude="52.3702160"
          longitude="4.8951680"
          zoomLevel="3"
          showUserLocation="true"
          mapReady="onMapReady">
      </MapboxView>
    </ContentView>
</StackLayout>
```

app.component.ts
```
import {Component} from "@angular/core";

@Component({
    selector: "my-app",
    templateUrl: "app.component.html",
})
export class AppComponent {
    public counter: number = 16;

    public get message(): string {
        if (this.counter > 0) {
            return this.counter + " taps left";
        } else {
            return "Hoorraaay! \nYou are ready to start building!";
        }
    }
    
    public onTap() {
        this.counter--;
    }
}

```
The only thing I see is a blue square according to the background color defined.

I'm not getting any error neither from the app nor from the console.
Token and style are OK because both are working with a JS application.

Am I doing anything wrong?

**Comment by GrEg00z** [comment]
Add this to the top of your component : 

```
import {registerElement} from "nativescript-angular/element-registry";
registerElement("MapboxView", () => require("nativescript-mapbox").MapboxView);
```

**Comment by j99ht** [comment]
This is what I get

Successfully prepared plugin nativescript-angular for android.
Successfully prepared plugin nativescript-intl for android.
Successfully prepared plugin nativescript-mapbox for android.
Successfully prepared plugin tns-core-modules for android.
JS: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
JS: ns-renderer: viewClass is not a constructor
JS:
JS: TypeError: viewClass is not a constructor
JS:     at ViewUtil.createView
(file:///data/data/org.nativescript.mapBoxTest/files/app/tns_modules/nativescript-angular/view-util.js:123:20)
JS:     at NativeScriptRenderer.createElement
(file:///data/data/org.nativescript.mapBoxTest/files/app/tns_modules/nativescript-angular/renderer.js:104:30)
JS:     at DebugRenderer2.createElement
(file:///data/data/org.nativescript.mapBoxTest/files/app/tns_modules/@angular/core/bundles/core.umd.js:13119:49)
JS:     at createElement
(file:///data/data/org.nativescript.mapBoxTest/files/app/tns_modules/@angular/core/bundles/core.umd.js:9325:27)
JS:     at createViewNodes
(file:///data/data/org.nativescript.mapBoxTest/files/app/tns_modules/@angular/core/bundles/core.umd.js:11963:44)
JS:     at callViewAction
(file:///data/data/org.nativescript.mapBoxTest/files/app/tns_modules/@angular/core/bundles/core.umd.js:12381:13)
JS:     at execComponentViewsAction
(file:///data/data/org.nativescript.mapBoxTest/files/app/tns_modules/@angular/core/bundles/core.umd.js:12320:13)
JS:     at createViewNodes
(file:///data/data/org.nativescript.mapBoxTest/files/app/tns_modules/@angular/core/bundles/core.umd.js:12032:5)
JS:     at createRootView
(file:///data/data/org.nativescript.mapBoxTest/files/app/tns_modules/@angular/core/bundles/core.umd.js:11910:5)
JS:     at callWithDebugContext
(file:///data/data/org.nativescript.mapBoxTest/files/app/tns_modules/@angular/core/bundles/core.umd.js:13048:42)
JS:     at Object.debugCreateRootView [as createRootView]
(file:///data/data/org.nativescript.mapBoxTest/files/app/tns_modules/@angular/core/bundles/core.umd.js:12508:12)
JS:     at ComponentFactory_.create
(file:///data/data/org.nativescript.mapBoxTest/files/app/tns_modules/@angular/core/bundles/core.umd.js:9831:46)
JS:     at ComponentFactoryBoundToModule.create
(file:///data/data/org.nativescript.mapBoxTest/files/app/tns_modules/@angular/core/bundles/core.umd.js:3434:29)
JS:     at ApplicationRef_.bootstrap
(file:///data/data/org.nativescript.mapBoxTest/files/app/tns_modules/@angular/core/bundles/core.umd.js:5015:57)
JS:     at
file:///data/data/org.nativescript.mapBoxTest/files/app/tns_modules/@angular/core/bundles/core.umd.js:4804:79


2017-05-05 19:41 GMT+02:00 GrEg00z <notifications@github.com>:

**Comment by GrEg00z** [comment]
Try to remove mapStyle attribute, and also if you're using angular, you should write the attributes like this :
[accessToken]="...", [latitude]="...", etc...
And (mapReady)="mapReady()" (where mapReady is a function defined in your component ts file)

**Comment by mlb6** [comment]
@GrEg00z Your solution worked for me. Thanks

**Comment by j99ht** [comment]
Sorry for the question but I'm newbie to this.

How can I set accessToken and mapStyles then?

2017-05-12 21:42 GMT+02:00 Martin Le Bas <notifications@github.com>:

**Comment by rhanb** [comment]
Hi @j99ht ,

You have two different to to do it:

### Angular componentt:
```typescript
function onMapReady(args) {
  // don't forget to declare _map variable
  this._map. accessToken = "your_token";
 this._map.mapStyles = ...;
  );
}
```
# OR

### XML: 
```xml
<MapboxView
          [accessToken]="accessToken"
         [mapStyles]="mapStyles"
>
</MapboxView>
```
AND

### Angular Component:
```typescript
public accessToken: string;
public mapStyles: any;

constructor () {
    this.accessToken = "your_token";
    this.mapStyles = ...
}
```

And this apply to any custom views with properties in Angular you always have those two options.

**Comment by j99ht** [comment]
It works. Thanks.

Also the map is working as well.

2017-05-16 15:49 GMT+02:00 JB <notifications@github.com>:
