### ISSUE TITLE
Compass and user location not showing

### ISSUE THREAD

**Issue by d3mac123** [Yermo/nativescript-mapbox#117]
Hi, even with both parameters set to true, they are not showing up...
```
<ContentView row="1" height="240" width="240">
              <map:Mapbox
                  latitude="26.058857"
                  longitude="-80.274303"
                  zoomLevel="12"
                  mapStyle="light"
                  hideAttribution="true"
                  showUserLocation="true"
                  hideCompass="false"
                  accessToken="pk.jazFwMDd2MzMyczZtMzg1Njl5eSJ9.w2K2EUOZzxtCqqAARGBbZA"
                  mapReady="onMapReady" 
                  class="map">
              </map:Mapbox>
</ContentView>
```
![image](https://cloud.githubusercontent.com/assets/229148/25969958/f11e210a-3664-11e7-92a1-48eff7db8263.png)

**Comment by EddyVerbruggen** [comment]
For compass you may need to rotate the map a bit (2 finger rotation gesture).

For location: what's your device location set to, and did you grant permission?

**Comment by d3mac123** [comment]
Right now I am using only the iOS emulator (I do have an Android device but I have reported another issue as Android is not compiling the app - if you can check the other post, it would be much appreciated).

Regarding the compass, is there a way to keep it on all the time (my app will be a GPS tracker and having the compass would be great)?

What is the right way to set the device location? I add the lat/long of my house in the map object (I also set a market to the same point to see if it was working).

Regarding permission, I set the plugin following all the instructions for the plugin page. Do I need anything special for that?

Sorry if my questions are too dumb. I am a designer try to code my first app with NativeScript and almost everything is new to me.

Thanks again,
Alex

**Comment by EddyVerbruggen** [comment]
The location of a simulator can be set via the macOS menu (when the sim is in the foreground): Debug > Location.

**Comment by d3mac123** [comment]
User location is showing only on iOS. Does not show on Android.

![screen shot 2017-05-12 at 5 10 36 pm](https://cloud.githubusercontent.com/assets/229148/26017116/053e1902-3736-11e7-9b05-3cc731d6902d.png)

**Comment by rnonnon** [comment]
Hi,

If you use genymotion emulator for Android, you have to enable GPS configuration.
![image](https://cloud.githubusercontent.com/assets/14371587/26078841/0f808674-39c1-11e7-9c26-fedd0d234a63.png)
