### ISSUE TITLE
Mapbox-4.0.0 : Can't add a marker : markerOptions.title is not a function

### ISSUE THREAD

**Issue by Neomac** [Yermo/nativescript-mapbox#12]
Hi, I've got an issue with your mapbox-4.0.0 branch. I know it's under development, but I needed a mapbox 4 version to make it run on 64bits devices so I gave it a shot.

I succeeded to make the map show up by adding : 
`<service android:name="com.mapbox.mapboxsdk.telemetry.TelemetryService" />`
in the android manifest. I don't know why the one in the plugin doesn't work.

Then I tried to put a marker on the map but I go this error : 

> JS: Error in mapbox.addMarkers: TypeError: markerOptions.title is not a function
> JS: EXCEPTION: Error: Uncaught (in promise): TypeError: markerOptions.title is not a function
> JS: STACKTRACE:
> JS: Error: Uncaught (in promise): TypeError: markerOptions.title is not a function
> JS:     at resolvePromise (/data/data/org.nativescript.gpadri/files/app/tns_modules/zone.js/dist/zone-node.js:496:32)
> JS:     at /data/data/org.nativescript.gpadri/files/app/tns_modules/zone.js/dist/zone-node.js:473:14
> JS:     at /data/data/org.nativescript.gpadri/files/app/tns_modules/nativescript-mapbox/mapbox.js:189:7
> JS:     at new ZoneAwarePromise (/data/data/org.nativescript.gpadri/files/app/tns_modules/zone.js/dist/zone-node.js:542:30)
> JS:     at Object.mapbox.addMarkers (/data/data/org.nativescript.gpadri/files/app/tns_modules/nativescript-mapbox/mapbox.js:175:10)
> JS:     at GeotrackPage.addMarkers (/data/data/org.nativescript.gpadri/files/app/geotrack/geotrack.components.js:66:16)
> JS:     at DebugAppView._View_GeotrackPage0._handle_tap_12_0 (GeotrackPage.template.js:92:28)
> JS:     at /data/data/org.nativescript.gpadri/files/app/tns_modules/@angular/core/src/linker/view.js:316:24
> JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.gpadri/files/app/tns_modules/zone.js/dist/zone-node.js:281:29)
> JS:     at Object.NgZoneImpl.inner.inner.fork.onInvoke (/data/data/org.nativescript.gpadri/files/app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:45:41)
> JS: Unhandled Promise rejection: markerOptions.title is not a function ; Zone: angular ; Task:  ; Value: TypeError: markerOptions.title is not a function
> JS: Error: Uncaught (in promise): TypeError: markerOptions.title is not a function

By checking the mapbox documentation, your implementation looks good. I can't figure out why it doesn't want to find the title function.
I saw some Todo around so maybe it's something that you already know.

**Comment by EddyVerbruggen** [comment]
Ha, that's exacltly the reason why I stopped working on that branch until [this issue](https://github.com/mapbox/mapbox-gl-native/issues/4761) is resolved. Please follow that issue for updates. I will continue my work once that's fixed and released.

**Comment by Neomac** [comment]
Ok, I see I'm just on time :). Hope they gonna fix this soon.
