### ISSUE TITLE
Apple Mach-O Linker Error Group

### ISSUE THREAD

**Issue by b4rtt** [Yermo/nativescript-mapbox#123]
Hi, I have problem with built project.

In simulator everything works good but when I open built project in XCode and I run build it gives me **Apple Mach-O Linker Error Group - clang: error: linker command failed with exit code 1 (use -v to see invocation)** and building dies. I really don't know where should be problem. For example here I have repository with problematic project. https://github.com/b4rtt/geoapp

Update: in error detail I see this:

Showing Recent Issues
ld: framework not found Pods_Geoapp

![snimek obrazovky 2017-05-21 v 18 31 32](https://cloud.githubusercontent.com/assets/4247839/26285671/a13558a0-3e54-11e7-94ae-ff328a793756.png)

Thank you for help.

**Comment by VladimirAmiorkov** [comment]
Maybe [this](https://github.com/googlevr/gvr-unity-sdk/issues/539#issuecomment-294738041) will help you. Basically do not open the .**xcodeproj** but the **.xcworkspace**
