### ISSUE TITLE
Angular2 markers custom image doesn't work

### ISSUE THREAD

**Issue by b4rtt** [Yermo/nativescript-mapbox#124]
Everything works fine. Marker is visible but it has default image not custom.
```
this._mapbox.nativeElement.addMarkers([{
                    id: 1,
                    lat: this.player_latitude,
                    lng: this.player_longitude, 
                    icon: 'res/markers/green_pin_marker.png'
}]);
```

**Comment by EddyVerbruggen** [comment]
Can you share your repo so I can see what that path points to? Or a screenshot of your folders perhaps.

**Comment by b4rtt** [comment]
@EddyVerbruggen here you can see problematic project repository https://github.com/b4rtt/geoapp. Thank you for help

**Comment by b4rtt** [comment]
@EddyVerbruggen and on tap event doesn`t work too

**Comment by EddyVerbruggen** [comment]
Thanks for the demo app. I haven't used it with Angular so I'll need some time to figure this out.

**Comment by EddyVerbruggen** [comment]
First thing I tried was this and at least that seems to work, perhaps you can build on that?

HTML (last line of the map definition)
```html
      (mapReady)="onMapReady(mapbox)" #mapbox>
```

Component:
```typescript
onMapReady(map: Mapbox) {
  map.setZoomLevel({
     level: 3,
     animated: true
   });
}
```

**Comment by b4rtt** [comment]
@EddyVerbruggen In my code addMarkers() setCenter() etc. is working, but marker hasn't custom image. I tried local image and URL image too. I still see default marker icon. Marker tap event doesn't work too

**Comment by EddyVerbruggen** [comment]
But your demo app doesn't have the `green_pin_marker.png` icon in the app/res/ folder, right?

**Comment by b4rtt** [comment]
@EddyVerbruggen Right I know that image in this repo isn't. I have updated repo. But it was not problem. It still doesn't work. When I change it to http image it still doesn't work

**Comment by EddyVerbruggen** [comment]
For anyone having issues with markers (in an Angular app or not), you can for example use it like [this](https://github.com/EddyVerbruggen/nativescript-pluginshowcase/blob/41dffbef0a597b4a83310dce1b8dbf207d0063ac/app/mapping/mapping.component.ts#L100) or [this](https://github.com/EddyVerbruggen/nativescript-pluginshowcase/blob/41dffbef0a597b4a83310dce1b8dbf207d0063ac/app/mapping/mapping.component.ts#L121).
