### ISSUE TITLE
In version 3.0.0, mapbox.show() promise never resolves (iOS)

### ISSUE THREAD

**Issue by ghost** [Yermo/nativescript-mapbox#126]
Just upgraded to nativescript-mapbox v3.0.0 and now when I try to declare a map programmatically, the promise just hangs, and the code in the .then() block never runs. Can you help? I am on iOS, with nativescript-angular v3.0.0

By the way, thanks for all your work on this project. I've been following it for a few months now and it's really great!

**Comment by EddyVerbruggen** [comment]
Hmm, this should be working since over almost a year now. To anyone encountering this: please reopen if not, and share a repo showing the error.
