### ISSUE TITLE
Offline and Element overlay capability question

### ISSUE THREAD

**Issue by vessp** [Yermo/nativescript-mapbox#13]
Hello there, i'm starting a new project for which I need to use maps on both ios and android. However I need to show images overtop of the map sometimes, is it possible to show ui elements overtop of the map? (this is difficult for some hybrid frameworks)

Also, MapBox native libraries have support for offline usage and I was wondering if this is supported yet.

Kind regards.

**Comment by EddyVerbruggen** [comment]
Offline is not yet supported because we can't update to the latest SDK supporting that feature do to an open issue in the Mapbox SDK. See #12.

I think it's possible to overlay images with NativeScript but didn't try myself.

**Comment by bloigge** [comment]
Hi - We are also looking for a way to enable offline caching using mapbox and nativescript. Is there any forecast for this feature in nativescript-mapbox?

**Comment by Stavanger75** [comment]
+1
