### ISSUE TITLE
Use with Mapbox on-premise installation

### ISSUE THREAD

**Issue by davidpronk** [Yermo/nativescript-mapbox#131]
Would it be possible to use nativescript-mapbox with an on-premise installation of Mapbox? In other words, configure the mapbox server url.

**Comment by EddyVerbruggen** [comment]
I have no idea. What would that take?

**Comment by davidpronk** [comment]
By default Mapbox tiles are loaded from https://api.tiles.mapbox.com and I am looking for a way to change this to another domain which hosts Mapbox as mentioned at https://www.mapbox.com/atlas/
But I guess I should dig deeper into the Mapbox-native code.

**Comment by EddyVerbruggen** [comment]
Would be cool if you can find where in the SDK this can be configured.

**Comment by davidpronk** [comment]
This Stackoverflow page answers my question: https://stackoverflow.com/a/36837943 There is a possibility to configure a url for where sources are loaded from.
