### ISSUE TITLE
Map Doesn't show

### ISSUE THREAD

**Issue by dogabudak** [Yermo/nativescript-mapbox#133]
My application was working properly until i update my tns-version. Now my application works but the map doesn't show on the screen. I get these two errors while I want to reach the map 

> [INFO] {DefaultFileSource}[Database]: cannot open file at line 38280 of [0e5ffd9123] (Code 14)
[INFO] {DefaultFileSource}[Database]: [0e5ffd9123]:38280: (3) open(/Users/dogabudak/Library/Developer/CoreSimulator/Devices/FA8FBC63-02CF-435C-8F13-7728E7F4AE1B/data/Containers/Data/Application/D1EDE0E6-632A-4C4C-8385-2D09A0801AB2/Library/Application Support/org.nativescript.piarcha/.mapbox/cache.db) -  (Code 14)

my package.json is ;

> "tns-ios": {
      "version": "3.0.1"
    }

>     "nativescript-mapbox": "^3.0.0",

Do i have to do anything else after I upgrade my tns version ?

**Comment by EddyVerbruggen** [comment]
Depends on the code you use to render the map. If it's an XML definition then yeah, see the readme.

**Comment by dogabudak** [comment]
Oh didn't saw that on the first glance sorry,
      IMPORTANT: plugin version 3 uses :MapboxView, lower versions use :Mapbox 

now its fixed

**Comment by EddyVerbruggen** [comment]
Cool!
