### ISSUE TITLE
Icon and OnTap is working only in costructor

### ISSUE THREAD

**Issue by b4rtt** [Yermo/nativescript-mapbox#135]
Hi,

I found this issue. When I click to button which calls function (loadPoints), marker is shown but with default icon and impossible to make it clickable.

Adding markers in constructor is working fine without problem.

https://github.com/b4rtt/geoapp/blob/master/app/pages/login/login.page.ts

Is any way how to solve it?

Thank you

**Comment by b4rtt** [comment]
@EddyVerbruggen Could you help me please, or do you know anyone who can?

**Comment by b4rtt** [comment]
@bnussey Hi, i think that you are NS+Angular expert, could you help me please? I am kinda desperated :(

**Comment by b4rtt** [comment]
@EddyVerbruggen pls, I am in really problems with this :(

**Comment by EddyVerbruggen** [comment]
@b4rtt I just cloned that repo but it is very unresponsive since you're creating a location watcher every second. But no worries about that, I'll take a look.

**Comment by EddyVerbruggen** [comment]
I've found something. I need to change the plugin a bit and you'll need to change your code as well. I can fork your repo and send a PR if you like? **Or rather temporary write access, to save me some time**.

**Comment by b4rtt** [comment]
@EddyVerbruggen Yes, thank you very much! :)

**Comment by EddyVerbruggen** [comment]
Anyone encountering issues with incorrect icons or tap issues on iOS, please use 3.0.1.

**Comment by EddyVerbruggen** [comment]
@b4rtt Just pushed an update to your repo. You may have to restore some watch logic, but the update shows how to properly wire the map in an Angular app.

If there's any further issue please create an issue in **your** repo and ping me.
