### ISSUE TITLE
(QUESTION) Is there a way to capture when the map is scrolled?

### ISSUE THREAD

**Issue by d3mac123** [Yermo/nativescript-mapbox#136]
My app keeps the user always in the middle of the map (centered). However, I would like to allow the user move the map and then, after a few seconds, see it returning to the center position.

I couldn't find a way to capture if the map was moved (so I can start the setTimeout function). Is it possible?

Thanks, Alex

**Comment by EddyVerbruggen** [comment]
I don't think there currently is a way, but you could use a `setInterval` and poll the bounds.

**Comment by EddyVerbruggen** [comment]
3.2.0 added this feature: https://github.com/EddyVerbruggen/nativescript-mapbox#setonmapscrolllistener
