### ISSUE TITLE
Problem after install plugin

### ISSUE THREAD

**Issue by raschdiaz-zz** [Yermo/nativescript-mapbox#137]
After install the plugin, my project presents the following exception:

C:\xampp\htdocs\NativeScriptExample1\platforms\android\build\intermediates\res\merged\F0F1F2F3F4F5\debug\values-v24\values-v24.xml:3: AAPT: Error retrieving parent for item: No resource
found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

C:\xampp\htdocs\NativeScriptExample1\platforms\android\build\intermediates\res\merged\F0F1F2F3F4F5\debug\values-v24\values-v24.xml:4: AAPT: Error retrieving parent for item: No resource
found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

C:\xampp\htdocs\NativeScriptExample1\platforms\android\build\intermediates\res\merged\F0F1F2F3F4F5\debug\values-v24\values-v24.xml:3: error: Error retrieving parent for item: No resource
 found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

C:\xampp\htdocs\NativeScriptExample1\platforms\android\build\intermediates\res\merged\F0F1F2F3F4F5\debug\values-v24\values-v24.xml:4: error: Error retrieving parent for item: No resource
 found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
:processF0F1F2F3F4F5DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1F2F3F4F5DebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

My work environment is as follows:

NativeScript: 3.1.1.
NodeJS: 6.9.1.
Windows 8.1 Single Language.

**Comment by EddyVerbruggen** [comment]
Never had a clue about this one. Long ago --> closing.
