### ISSUE TITLE
[question] is it possible to set the language of map ? 

### ISSUE THREAD

**Issue by c1ngular** [Yermo/nativescript-mapbox#139]
wonderful plugin ~  the default language is English , possible to specify language ?

**Comment by EddyVerbruggen** [comment]
Hmm, no idea. Doesn't the map follow the device language? If not, can you perhaps check the [SDK repo](https://github.com/mapbox/mapbox-gl-native) for pointers? That's what this plugin builds upon.

**Comment by c1ngular** [comment]
Thanks, you are right , it is following the device language setting!  By the way, do you know where I can submit some corrections/translations  to the map ?

**Comment by EddyVerbruggen** [comment]
Nice. You'll have to take that up with the [Mapbox](https://www.mapbox.com/) guys.
