### ISSUE TITLE
Error when trying to use function downloadOfflineRegion 

### ISSUE THREAD

**Issue by idomaz00** [Yermo/nativescript-mapbox#141]
Hi,

I get an error when I try to use downloadOfflineRegion or listOfflineRegions function in my app, other functions like setCenter, addMarkers, getViewport work normaly. Code I used is copy-pasted from your examples, just modified a bit for use with typescript and angular2.
It is angular2+typescript app, nativescript version 3.0.2 and nativescript-mapbox plugin version ^3.0.0, testing on device nexus5x, Android 7.1.2. Function is triggered by a button click.
This is what I get on my screen:
>An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onClick failed
>TypeError: this._mapbox.nativeElement.downloadOfflineRegion is not a function
File: "file:///data/data/org.nativescript.testingmapplugin/files/app/tns_modules/@angular/core/bundles/core.umd.js, line: 13024, column: 8
>StackTrace: 
    Frame: function:'MapComponent.downloadCurrentMap', file:'file:///data/data/org.nativescript.testingmapplugin/files/app/pages/map/map.component.js', line: 151, column: 36
>    Frame: function:'', file:'', line: 153, column:
...........

And this in my terminal:

>07-12 12:11:39.120 22882 22882 W System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
07-12 12:11:39.120 22882 22882 W System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
07-12 12:11:39.120 22882 22882 W System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
07-12 12:11:39.120 22882 22882 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:890)
07-12 12:11:39.120 22882 22882 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:874)
07-12 12:11:39.120 22882 22882 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:866)

I tried your demo app and it works fine but it is a plugin version ^2.6.0 and I really need to use your new version. 
My code snippets:

- map.component.ts

`@ViewChild("mapbox") _mapbox: ElementRef;`
```
downloadCurrentMap() {
    this._mapbox.nativeElement.downloadOfflineRegion(
      {      
        accessToken: this.accessToken, // required for Android in case no map has been shown yet 
        name: "Amsterdam", // this name can be used to delete the region later 
        style: "light",
        minZoom: 9,
        maxZoom: 11,
        bounds: {
          north: 52.4820,
          east: 5.1087,
          south: 52.2581,
          west: 4.6816
        },
        onProgress: function (progress) {
          console.log("Download progress: " + JSON.stringify(progress));
        }
      }
    ).then(
      function() {
        console.log("Offline region downloaded");
      },
      function(error) {
        console.log("Download error: " + error);
      }
    );
}
```
map.component.html
```
<StackLayout>
      <Label  colSpan="2" class="text-center" text="I am here: {{lat}} - {{long}}"></Label>
      <Button class="btn" text="Refresh location" (tap)="showCurrentLocation()"></Button>
      <Button class="btn btn-primary btn-active" text="watchLocation" (tap)="watchLocation()"></Button>
      <Button class="btn btn-primary btn-active" text="listDownloaded" (tap)="listDownloaded()"></Button>
      <Button class="btn btn-primary btn-active" text="Download map" (tap)="downloadCurrentMap()"></Button>
      <ContentView>
        <MapboxView
            accessToken=MYTOKEN
            mapStyle="streets"
              [latitude]="lat"
              [longitude]="long"
              zoomLevel="14"
              showUserLocation="true"
              (mapReady)="onMapReady($event)" #mapbox>
        </MapboxView>
      </ContentView>
  </StackLayout>
```

**Comment by EddyVerbruggen** [comment]
You can't use that method currently that way, see the comment after [this](https://github.com/EddyVerbruggen/nativescript-mapbox#-or-want-to-set-the-viewport-bounds): "The methods you can invoke like this from an XML-declared map are..".

**Comment by idomaz00** [comment]
Ufff I'm sorry, I scrolled through documentation so many times but I guess I didn't read carefully enough. Thank you!
