### ISSUE TITLE
Possibility to disable marker tooltip

### ISSUE THREAD

**Issue by b4rtt** [Yermo/nativescript-mapbox#143]
Hi, is it possible? If yes, how?

Thank you

**Comment by EddyVerbruggen** [comment]
Have you tried not setting the `title` attribute?

**Comment by b4rtt** [comment]
@EddyVerbruggen When I delete tittle and subtitle then marker icon doesn't working :D

**Comment by EddyVerbruggen** [comment]
Ah ok. Perhaps you can do some research on the Mapbox website and github repo and report your findings?

**Comment by b4rtt** [comment]
@EddyVerbruggen

I found this: https://github.com/mapbox/mapbox-gl-native/issues/3559

In Mapbox it should be solved. When is title empty then tooltip should be hidden on click.

**Comment by EddyVerbruggen** [comment]
Ah, that's perfect, so they fixed that a while ago. I will look into it.

**Comment by EddyVerbruggen** [comment]
Hey @b4rtt I just tried with the current version and it works if you do it [like this](https://github.com/EddyVerbruggen/nativescript-mapbox/blob/6bebf9872c2ef85333beb2b98cbf38629f3d051a/demo/app/main-view-model.ts#L147-L151).

**Comment by b4rtt** [comment]
@EddyVerbruggen How should I update it? I have 3.0.1 version and when I delete Title and subtitle (same as in you code), icon is default and tap doesn't working https://github.com/b4rtt/PiratiGo

**Comment by EddyVerbruggen** [comment]
@b4rtt iOS or Android?
I cloned your repo but I only see a Google login button, no map (iOS).

**Comment by b4rtt** [comment]
@EddyVerbruggen I developing it only for iOS now.

Yes, sorry I made progress in my app. If you don't mind it you can login. (it's only login - after login you can see map)


BTW It's for other topic, but when I try to build it for Android building crashes. (because Firebase - don't know why)

I know that you are GOD creator of Firebase too. You can look for it too? Maybe will be better to create issue in Firebase repo?

**Comment by EddyVerbruggen** [comment]
The problem is I can't login (see screenshot). And the console is flooded with errors. Can you please run the Mapbox demo and see if that code I linked to previously works?

![simulator screen shot 25 jul 2017 10 43 19](https://user-images.githubusercontent.com/1426370/28563397-2217d3f4-7126-11e7-8457-f3672d9ec45a.png)

**Comment by EddyVerbruggen** [comment]
I don't think this was published to npm - it's part of 3.0.2.

**Comment by ExaltedJim** [comment]
@EddyVerbruggen Is it possible to have markers on the map without a tooltip but still have the onTap for a marker fire? I have tried not setting the title and no tooltip is displayed, but my onTap function doesn't fire. If I add the title attribute back, the onTap does fire, but I get the tooltip that I don't want to display.

Any advice would be appreciated.

Cheers

**Comment by EddyVerbruggen** [comment]
Good call, @ExaltedJim - with 3.0.3 you can do just that.
