### ISSUE TITLE
How to update Mapbox SDK for the plugin use?

### ISSUE THREAD

**Issue by d3mac123** [Yermo/nativescript-mapbox#145]
I keep getting this message from Terminal:
`Mapbox iOS SDK version 3.6.0 is now available: https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.6.0`

What is the right way to update the SDK?

**Comment by EddyVerbruggen** [comment]
Just ignore it. The plugin updates the underlying SDK's and test xplatform compatibility for you.
