### ISSUE TITLE
Turn By Turn Navigation

### ISSUE THREAD

**Issue by Shifs** [Yermo/nativescript-mapbox#148]
I need turn by turn navigation from point A to point B . Please let me know when this would be integrated in this plugin . Also , I have to create a plugin for this , can you please let me know how much time it takes as I am newbie to nativescript.

**Comment by EddyVerbruggen** [comment]
You may want to look at [nativescript-directions](https://github.com/EddyVerbruggen/nativescript-directions) for now.
