### ISSUE TITLE
Map not showing on Android 5.0.1 device

### ISSUE THREAD

**Issue by ADjenkov** [Yermo/nativescript-mapbox#15]
I'm getting exception:

> mapbox show error: Error: java.lang.UnsatisfiedLinkError: com.mapbox.mapboxsdk.views.NativeMapView
>     com.mapbox.mapboxsdk.views.MapView.initialize(MapView.java:787)
>     com.mapbox.mapboxsdk.views.MapView.<init>(MapView.java:690)
>     com.tns.Runtime.callJSMethodNative(Native Method)
>     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
>     com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
>     com.tns.Runtime.callJSMethod(Runtime.java:712)
>     com.tns.Runtime.callJSMethod(Runtime.java:693)
>     com.tns.Runtime.callJSMethod(Runtime.java:683)
>     com.tns.gen.java.lang.Runnable_ftns_modules_timer_timer_l15_c20__.run(Runnable_ftns_modules_timer_timer_l15_c20__.java:10)
>     android.os.Handler.handleCallback(Handler.java:739)
>     android.os.Handler.dispatchMessage(Handler.java:95)
>     android.os.Looper.loop(Looper.java:135)
>     android.app.ActivityThread.main(ActivityThread.java:5538)
>     java.lang.reflect.Method.invoke(Native Method)
>     java.lang.reflect.Method.invoke(Method.java:372)
>     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958)
>     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:753)

In /tns_modules/nativescript-mapbox/mapbox.js (.android) when trying to create  `mapView = new com.mapbox.mapboxsdk.views.MapView(application.android.context, settings.accessToken);`

I'm with {N} CLI 2.0.1 and modules 2.0.0 version. The funny thing is that the same application works on Nexus 4 (5.0.1), Nexus 5 (6.0.1) , Samsung G. S4 (5.0.1) but it crashes on 3 different Huawei P8 devices with (5.0.1). Can you point me to something? 
Thanks

**Comment by EddyVerbruggen** [comment]
This is probably fixed by now ;)
