### ISSUE TITLE
Using/Showing an offline map

### ISSUE THREAD

**Issue by jet-lee-m** [Yermo/nativescript-mapbox#150]
Hi,

I can download and list an offline map, but I don't find any description or code example that describe how to use an offline map. 

Can someone help and show me an code example?

Thx

**Comment by jet-lee-m** [comment]
Okay... I found the solution. 

I must show the mapbox programmatically with this.mapbox.show(...). I use nativescript angular2/4.

But now I have the problem that I want the mapbox is dependant from the size of the parent layout (eg. stacklayout). I saw that I can use margins, but in this case the view is absolute. 

is there any solution to put the mapbox in a parent layout and 
and at the same time I use the map offline?

thx

**Comment by EddyVerbruggen** [comment]
Do you need to show the map to be able to download a map? What code have you tried, and on which platform?

**Comment by jet-lee-m** [comment]
Hi,

yes I need to show the map to be able to download the map. 
I use:
nativescript:  3.0.0
platform: ios (tns-ios 3.1.0)
with angular 2/4 

thx

**Comment by yzyii** [comment]
Is there any update on this? I'm finding the same exact issues.

In order to use offline maps, we're forced to use the programmatic way of using this plugin which displays the map absolutely and blocks out things like nativescript sidedrawer or the action bar?

Is there no way to either use offline maps with XML or to position the programmatically generated one inside a parent layout?

nativescript: 4.0.0
platform: android (tns-android 4.0.1)
using angular 5.

**Comment by EddyVerbruggen** [comment]
I'm not sure it will solve all your challenges but with plugin version 4.0.0 (which includes the latest iOS Mapbox SDK) i don't have to show a map in order to download it.

Please reopen with a sample repo (reproducing this issue) if it's still the case after upgrading (will release it today).

**Comment by yzyii** [comment]
I'm not sure that will fix it although I will definitely test it once 4.0.0 is released and upload a sample repo.

Currently on version 3.3.0 of the plugin on Android:
* I am able to display a map using XML and onMapReady.
* I can also download offline files by importing MapBox, creating a new MapBox() instance and calling downloadOfflineRegion() on that.

After I download the region, kill the app, turn on aeroplane mode (to go offline), and restart it though:
* I end up getting the same error as on https://github.com/EddyVerbruggen/nativescript-mapbox/issues/199

It's possible to get sort of working glitchy behaviour by explicitly calling listOfflineRegions or downloadOfflineRegion BEFORE the XML onMapReady fires but often the map will fail to load entirely and remain entirely black.

**Comment by yzyii** [comment]
Looks like 4.0.0 fixes it. Thanks!

There's a small issue on android where the app won't actually work normally when online if you call listOfflineMaps.

It will only load the offline maps and won't load one's you haven't downloaded as you scroll around (the regions you haven't downloaded will stay black).

You can work around it by calling downloadOfflineRegion() with any arguments though and the app will then work as normal.

**Comment by Mflm** [comment]
Hi
I don't find any description or code example that describe how to use an offline map.
I can't show the regions downloaded, all the map is black.

How I can show the map?

First in the XML i have that
`<map:MapboxView
          accessToken="TOKEN"
		  latitude="52.3702160"
          longitude="4.8951680"
          zoomLevel="10"
          showUserLocation="true"
          mapReady="onMapReady">
      </map:MapboxView>`

Second I download the map.
Later without connection all the map is black.

Also if I call the **onMapReady** with the same bonuds.


Thanks

**Comment by keithgulbro** [comment]
@EddyVerbruggen Any idea on how to accomplish what @Mflm is asking? I'm encountering a similar issue.

**Comment by alexonozor** [comment]
@EddyVerbruggen @jastmicro @Yermo   is there a way to show offline tile after downloading?
