### ISSUE TITLE
icon anchor

### ISSUE THREAD

**Issue by j99ht** [Yermo/nativescript-mapbox#151]
Is there is any way to define the icon anchor as stated in Mapbox SDK?

**Comment by EddyVerbruggen** [comment]
Interesting. Can you please add links to the sdks?

**Comment by j99ht** [comment]
Android
https://www.mapbox.com/help/android-markers/

IOS
https://www.mapbox.com/ios-sdk/examples/marker-image/ (here it is called
center offset)

2017-07-31 18:48 GMT+02:00 Eddy Verbruggen <notifications@github.com>:

**Comment by EddyVerbruggen** [comment]
I think the Mapbox SDK changed (that's what they do really) and there is no mention of 'anchor' on Android anymore (in the provided link), and the iOS link mentions fixing your marker image.
