### ISSUE TITLE
setOnMapClickListener iOS

### ISSUE THREAD

**Issue by slushnys** [Yermo/nativescript-mapbox#153]
Any plans to implement tap, longpress events to ios?

**Comment by d3mac123** [comment]
I would love to have this as well (the same feature as Android).

**Comment by marcel-braun** [comment]
i need this too! Is there a workaround?

**Comment by EddyVerbruggen** [comment]
@marcelbraun1985 When I implemented it for Android the problem was there was no equivalent API in the Mapbox iOS SDK that supports that feature. Can you perhaps do some digging [in their repo](https://github.com/mapbox/mapbox-gl-native) if it's possible by now?

**Comment by marcel-braun** [comment]
Yes i will do that and let you know my research.

**Comment by EddyVerbruggen** [comment]
@marcelbraun1985 I was also curious - looks like [this is now possible](https://www.mapbox.com/ios-sdk/api/3.4.1/Classes/MGLMapView.html).

The main question is: how should our implementation behave by default? If a user taps a portion of the map where there's also an annotation, should it then:

1. only trigger the annotation, or
2. only trigger our listener, or
3. trigger the annotation and our listener.

I think option 3 would be best, but I'll check how Android behaves as well.

**Comment by EddyVerbruggen** [comment]
OK, Android behaves like option 1 described above so when an annotation is tapped the tap listener of `setOnMapClickListener` is not fired. I'll try and make it similar on iOS.

**Comment by EddyVerbruggen** [comment]
Pulled it off! Will release a new version shortly.

**Comment by marcel-braun** [comment]
Amazing! Thanks!

**Comment by slushnys** [comment]
I was absent after this feature request/enhancement and now I'm pleasantly surprised by this update. Thanks @EddyVerbruggen !

**Comment by slushnys** [comment]
Created a new pull request implementing long press for both ios and android: https://github.com/EddyVerbruggen/nativescript-mapbox/pull/266/commits
