### ISSUE TITLE
Polylines on iOS

### ISSUE THREAD

**Issue by d3mac123** [Yermo/nativescript-mapbox#154]
This is a strange situation on iOS. Running this code, does NOT show any lines (I have tried both options below):
```
function onMapReady(args) {
   map = args.map;
   //delete previous routes
   map.removePolylines();

   var abc = [{lat:26.058587,lng:-80.2764915},{lat:26.061879,lng:-80.273255}]
/*
   args.map.addPolyline({
        id: 100, // optional, can be used in 'removePolylines'
        color: '#30BCFF', // Set the color of the line (default black)
        width: 3, //Set the width of the line (default 5),
        opacity: 1,
        points: [
            {
              'lat': 26.058587,
              'lng': -80.2764915
            },
            {
              'lat': 26.061879,
              'lng': -80.273255
            }
        ]
    });
*/
    map.addPolyline({
        id: 100, // optional, can be used in 'removePolylines'
        color: '#3F5CFF', // Set the color of the line (default black)
        width: 5, //Set the width of the line (default 5)
        points: JSON.parse(JSON.stringify(abc))
    });
```

However, in another page, loading all data points into a table/array, shows the line:
```
map.addPolyline({
    id: 1, // optional, can be used in 'removePolylines'
    color: '#30BCFF', // Set the color of the line (default black)
    width: 5, //Set the width of the line (default 5)
    points: JSON.parse(JSON.stringify(flightData))
});
```

Any ideas why?

**Comment by EddyVerbruggen** [comment]
Nope..

**Comment by d3mac123** [comment]
@EddyVerbruggen there is something wrong with the plugin in iOS. I created a new, empty, project (just iOS), add the plugin and used your own example from the documentation page: added the map and the following "onMapReady":
```
function onMapReady(args) {
  args.map.addPolyline({
        id: 100, // optional, can be used in 'removePolylines'
        color: '#30BCFF', // Set the color of the line (default black)
        width: 3, //Set the width of the line (default 5),
        opacity: 1,
        points: [
            {
              'lat': 26.058587,
              'lng': -80.2764915
            },
            {
              'lat': 26.061879,
              'lng': -80.273255
            }
        ]
    });
}
```
...Nothing is rendered. Have you tried to do that?

**Comment by EddyVerbruggen** [comment]
Please share your project so I can try. Thx.

**Comment by d3mac123** [comment]
Here it goes: https://1drv.ms/u/s!AoyLe81WMbMDia0oDCbHYuYitjFqrg (it seems the onMapReady function is not being called)

**Comment by EddyVerbruggen** [comment]
Thanks - look closely at the file(name) the `onMapReady` function is defined in. That should give you a clue: https://github.com/EddyVerbruggen/nativescript-mapbox/blob/0c596381ae2efad901bb2ece0ae11e9fec66dcd3/demo/app/main-page.ts#L13

**Comment by d3mac123** [comment]
Got it! It worked on the sample project. Thank you!

However... in the "real project", it is still not working. Would you be kind enough to do a quick check at page dash_live-page.js? https://1drv.ms/u/s!AoyLe81WMbMDia0p27xLysWr9WE59g

Really weird...

**Comment by EddyVerbruggen** [comment]
I can't run your app as the parent folder is missing. But I'm also not really available for this kind of debugging..

**Comment by d3mac123** [comment]
No worries then. I will keep looking. I was just wondering if you could find something in the onMapReady function in the dash_live-page, especially because the code is working fine on Android.

**Comment by d3mac123** [comment]
I found the problem (although I do not understand why this is working on Android but not on iOS). Anyways, originally I had this code coming BEFORE the map.addPolylines...:
```
   if (selectedMap==="Streets") {
        args.map.setMapStyle(mapbox.MapStyle.STREETS);
   } else if (selectedMap==="Light") {
        args.map.setMapStyle(mapbox.MapStyle.LIGHT);
   }  else if (selectedMap==="Dark") {
      args.map.setMapStyle(mapbox.MapStyle.DARK);
   } else if (selectedMap==="Satellite") {
        args.map.setMapStyle(mapbox.MapStyle.SATELLITE);
   }  else if (selectedMap==="Hybrid") {
      args.map.setMapStyle(mapbox.MapStyle.HYBRID);
   } 
```

having moved it to AFTER the map.addPolylines, it worked. Ideas?

**Comment by d3mac123** [comment]
I found the issue. On iOS you must remove the polyline before updating it. This is not necessary on Android.
