### ISSUE TITLE
listOfflineRegions fails on Android if no map has been shown

### ISSUE THREAD

**Issue by danielelkington** [Yermo/nativescript-mapbox#172]
When you call listOfflineRegions on Android and no map has been shown, the following error is received.
`Using MapView requires setting a valid access token. Use Mapbox.getInstance(Context context, String accessToken) to provide one.`

The readme says you can do the following
```
mapbox.listOfflineRegions({
    // required for Android in case no map has been shown yet
    accessToken: accessToken,
  })
```
However listOfflineRegions doesn't appear to take a parameter, and Typescript cannot compile the code if you try to provide one.

**Comment by EddyVerbruggen** [comment]
You're right, `downloadOfflineRegion` supports this kind of usage correctly, but `listOfflineRegions` doesn't. Let me fix that..
