### ISSUE TITLE
Possible to add image to info window

### ISSUE THREAD

**Issue by randy-johnson** [Yermo/nativescript-mapbox#174]
Is it possible to add an image to the infowindow?

**Comment by EddyVerbruggen** [comment]
Not that I know off, but if you can find anything that works on both platforms in [the Mapbox repo](https://github.com/mapbox/mapbox-gl-native) then I'm all ears! I think I saw a mention of custom info windows somewhere, but not entirely sure.. anyway: that's not exposed by this plugin.

**Comment by randy-johnson** [comment]
Thanks.  I found an example for android but not  IOS.  If I find something I will let you know.
