### ISSUE TITLE
Dragging Map

### ISSUE THREAD

**Issue by randy-johnson** [Yermo/nativescript-mapbox#175]
Is there an event that gets fired when I drag the map?

**Comment by randy-johnson** [comment]
https://www.mapbox.com/android-docs/map-sdk/overview/events/#camera-change-events

Looks like it is not part of the plugin yet?

After reviewing I imagine I could use the setOnMapClickListener code in the plugin as a guide to implementing the camera change features.

Thoughts?

**Comment by EddyVerbruggen** [comment]
Hi @randy-johnson! You're right, it's not part of the plugin yet.

And I think that would be a good approach indeed. Please give it a go if you have time.

**Comment by EddyVerbruggen** [comment]
3.2.0 added https://github.com/EddyVerbruggen/nativescript-mapbox#setonmapscrolllistener
