### ISSUE TITLE
Error when running demo

### ISSUE THREAD

**Issue by randy-johnson** [Yermo/nativescript-mapbox#176]
Hello,
When I go into the demo folder I get the following error when I run:

https://www.dropbox.com/s/16rpaslqk9ln8p2/2017-10-12_21-30-31.png?dl=0

Failed to find module nativescript-mapbox relative to app/tns_modules.

^CRandys-iMac:demo randy$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.2.1           │ 3.2.1          │ Up to date  │
│ tns-core-modules │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-android      │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-ios          │ 3.2.0           │ 3.2.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘

I was going to use demo to try and do the camerachanged enhancement.

I went into the demo folder.  Ran tns update
tns build android

tns run android

everything builds fine and I get the error when the app starts up.

**Comment by randy-johnson** [comment]
I figured it out after reading this:  https://docs.nativescript.org/plugins/building-plugins

i need to be in the src folder and run npm run demo.android

**Comment by hariaravind10** [comment]
in _command line_ 
`cd src`
for **IOS**
`npm run build && cd ../demo && tns run ios --syncAllFiles`
for **Android**
`npm run build && cd ../demo && tns run android`
