### ISSUE TITLE
Console output query

### ISSUE THREAD

**Issue by shivapersad** [Yermo/nativescript-mapbox#177]
Good day,

I implemented a map in XML using nativescript-mapbox. I also decided to add markers to the map, however, when I add the markers I am receiving the output below in the console. The map displays properly but I was wondering how come the following is produced as output in the console. Thanks for any assistance you can give me.

[INFO] {}[Database]: recovered 77 frames from WAL file /Users/shivapersad/Library/Developer/CoreSimulator/Devices/FB33CBCB-660B-4294-B243-26CDB6B8DBCE/data/Containers/Data/Application/B6551F3E-7FBA-497A-9D1C-5A5333FDE5FD/Library/Caches/org.ngccng.cngApp/Cache.db-wal (Code 283)
Failed to bind EAGLDrawable: <CAEAGLLayer: 0x600000830b60> to GL_RENDERBUFFER 1
Failed to make complete framebuffer object 8cd6
Failed to bind EAGLDrawable: <CAEAGLLayer: 0x600000830b60> to GL_RENDERBUFFER 1
Failed to make complete framebuffer object 8cd6
CONSOLE LOG file:///app/pages/cng-refuelling-stations/cng-refuelling-stations.component.js:556:20: Mapbox onMapReady for iOS, native object received: <MGLMapView: 0x7fa7c7849600; frame = (0 0; 300 443); clipsToBounds = YES; opaque = NO; autoresize = W+H; gestureRecognizers = <NSArray: 0x608000e4d500>; layer = <CALayer: 0x600000831600>>
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_yellow
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_yellow
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_green
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_green
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_green
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_green
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_yellow
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_yellow
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_red
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_yellow
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_red
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_yellow
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_green
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_green
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_yellow
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_green
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_green
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_green
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_green
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_yellow
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_green
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_yellow
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:773:32: resourcename: marker_yellow
CONSOLE LOG file:///app/tns_modules/nativescript-mapbox/mapbox.js:775:32: imageSource: [object Object]

**Comment by EddyVerbruggen** [comment]
Have you tried searching this repo? [Click here](https://github.com/EddyVerbruggen/nativescript-mapbox/search?utf8=%E2%9C%93&q=resourcename%3A&type=) and you'll see it's simply a `console.log` in the plugin source.

I'll leave this issue open as a reminder to remove those, but feel free to send a PR if those bother you.

**Comment by shivapersad** [comment]
I was just wondering if they would cause an issue with a deployed app for iOS? I didn't see it in the code for the iconPath. Also the console.log output appear in the Android version of the app. Thanks for the quick response.

**Comment by EddyVerbruggen** [comment]
The console logs have been removed in 3.3.0. They were for debugging purposes anyway, and it all seems to work nicely so I have no need for them any longer.
