### ISSUE TITLE
map variables not updating automatically

### ISSUE THREAD

**Issue by randy-johnson** [Yermo/nativescript-mapbox#179]
```
<map:MapboxView
                accessToken=""
                mapStyle="traffic_night"
                latitude="{{ mapModel.latitude }}"
                longitude="{{ mapModel.longitude }}"
                zoomLevel="{{ mapModel.zoom }}"
                showUserLocation="true"
                mapReady="onMapReady"
```

This code doesn't update the map automatically like I expected.  Am I doing something wrong or is it not possible with mapbox?

IT works on initial map load, but doesn't seem to work with subsequent updates to the map model.

**Comment by EddyVerbruggen** [comment]
Correct, there's no watch for those properties.

**Comment by EddyVerbruggen** [comment]
If you need to set fi. the zoomLevel at a later time, just call `setZoomLevel` (see the readme).
