### ISSUE TITLE
How to get lat long of userlocation from mapbox

### ISSUE THREAD

**Issue by devyaz** [Yermo/nativescript-mapbox#180]
i just updated my {N} and now my project wont get my current location using {N} geolocation, which worked before updating, but Mapbox shows and tracks userlocation without location, but to set center or to animate camera is now a problem, am very positive it's got to do with {N} geolocation, Now how do i use Mapbox's own userlocation as latt and long?? @EddyVerbruggen

**Comment by simonettoa** [comment]
same request for me! now I'm using the geolocation in background for another use and then load the last position from db; but it could be nice to have the lat/lon from mapbox if possible!

**Comment by guigulin** [comment]
`var geolocation = require("nativescript-geolocation");

geolocation.getCurrentLocation({ desiredAccuracy: 1, updateDistance: 10, minimumUpdateTime: 600000, maximumAge: 600000, timeout: 10000 })
        .then(function (location) {
            var lat = location.latitude;
            var lng = location.longitude;
            console.log("Coordinate: " + lat + " " + lng);
            args.map.addMarkers([
                {
                    id: 1,
                    lat: lat,
                    lng: lng,
                    title: 'Su ubicación actual', // no popup unless set
                    // subtitle: 'Subtitulo 1',
                    iconPath: 'markers/current_location.png',
                    onTap: function () { console.log("'Nice location' marker tapped"); },
                    onCalloutTap: function () {
                        console.log("'Nice location' marker callout tapped");
                        console.log(lat + " " + lng);
                    }
                }]).then(
                function (result) {
                    console.log("User Location Added");
                },
                function (error) {
                    console.log("Error, User Location: " + error);
                })

        }, function (e) {
            console.log("Error: " + e.message);
        });`

**Comment by EddyVerbruggen** [comment]
Thanks for the request folks!

With 3.3.0 you will be able to get the location of the user with this new function: https://github.com/EddyVerbruggen/nativescript-mapbox#getuserlocation
