### ISSUE TITLE
mapbox.listOfflineRegions is not a function

### ISSUE THREAD

**Issue by emoreno-94** [Yermo/nativescript-mapbox#184]
Hello, recently I updated to `nativescript` `3.3.1` and `nativescript-mapbox` from `2.6.1` to `3.1.3` but now I can't use `listOfflineRegions`. I tried with:
```typescript
let mapbox = require('nativescript-mapbox');
...
...
mapbox.listOfflineRegions()
      .then(regions => console.log(regions))
      .catch(err => console.log(err));
```
but always I get the same error `JS: ERROR TypeError: mapbox.listOfflineRegions is not a function`.

I have `nativescript 3.3.1`, `nativescript-mapbox 3.1.3` and `typescript 2.4.2`

**Comment by EddyVerbruggen** [comment]
Please try the [demo app](https://github.com/EddyVerbruggen/nativescript-mapbox/tree/master/demo). I just did and it worked on both platforms.

You can do so by cloning this repo, `cd src`, `npm run demo.ios|android`.

The 'List downloaded' button on this screen results in this alert (note that I downloaded 1 offline region already):

![simulator screen shot - iphone 8 - 2017-12-02 at 12 55 29](https://user-images.githubusercontent.com/1426370/33515202-22a9cc1e-d760-11e7-8830-936c4ee3719d.png)
