### ISSUE TITLE
Calling selectAnnotation() from native map view throws "TypeError: nv.selectAnnotation is not a function"

### ISSUE THREAD

**Issue by bozhidarc** [Yermo/nativescript-mapbox#186]
I'm trying to call the `MGLMapView.selectAnnotation()` from `args.map.getNativeMapView()`, but the only thing I got is an error.
I need this method so I can show the marker (annotation) title by default.
Am I doing something wrong or maybe the method is missing from the current MapBox version that the plugin wraps?

**Comment by EddyVerbruggen** [comment]
Ah, you mean you want to show the callout immediately when you add the marker? Sounds like a good addition to the plugin API (note that Mapbox only allows 1 open callout at any given time).

Looks like that method signature is actually `selectAnnotationAnimated(annotation: MGLAnnotation, animated: boolean): void`

**Comment by EddyVerbruggen** [comment]
With version 3.2.0 you'll be able to add `selected: true` when adding a marker. See the updated README.
