### ISSUE TITLE
Change default icon for user location 

### ISSUE THREAD

**Issue by guigulin** [Yermo/nativescript-mapbox#189]
I can see that in file mapbox.android.js appears 
var resourcename = "mapbox_mylocation_icon_default";
where mapbox_mylocation_icon_default are files .PNG that live in several folders on myapp\platforms\android\app\build\intermediates\res\merged\F0xxx\....
I replace that files, respecting their names and size, with the icon that I want to show on the map for user location.
But that don't works, continue showing the default image.
What i doing wrong?

**Comment by EddyVerbruggen** [comment]
Well actually I just updated to the latest Mapbox Android SDK and the location drawing was entirely changed so I had to remove that code.

Perhaps in the future you'll be able to style the indicator, but not right now.
