### ISSUE TITLE
Remove Markers Function

### ISSUE THREAD

**Issue by jacobocantillo** [Yermo/nativescript-mapbox#19]
Hi. 

Checking the functionality of the library I see that there is a method that adds markers to the map. It strikes me that there is no method to clear the contents of the markers, or remove any of them.

I think it would be very useful that the library existed a similar method.

Happy coding!

**Comment by EddyVerbruggen** [comment]
Hi,

What would that API look like? I mean, how would you like to reference the marker to be removed? I think you'd need to pass in some reference (id) you can later use to remove the marker by id(s).

By far the easiest thing to do though would be to remove _all_ markers at once - would that suffice for your usecase?

For my reference, [here's the iOS doc](https://www.mapbox.com/ios-sdk/api/3.3.4/Classes/MGLMapView.html#/c:objc%28cs%29MGLMapView%28im%29removeAnnotation:)

**Comment by jacobocantillo** [comment]
Hi,

It would be nice to have two methods: 
1. One to remove a marker associated with a particular ID.
2. Another to remove all markers.

That would be enough.

**Comment by EddyVerbruggen** [comment]
Hi, just landed in 1.4.0, please check [the readme](https://github.com/EddyVerbruggen/nativescript-mapbox#removemarkers) for details.
