### ISSUE TITLE
Outdoors map

### ISSUE THREAD

**Issue by d3mac123** [Yermo/nativescript-mapbox#191]
Hey Eddy, any chance to include the outdoors map style in the next release?
Thanks!

**Comment by EddyVerbruggen** [comment]
[isn't it already](https://github.com/EddyVerbruggen/nativescript-mapbox/blob/60845febd4dee237fe5f20ef54c52025a413f387/src/mapbox.common.ts#L6)?

**Comment by d3mac123** [comment]
Man, you rock!! Thanks (I was using an older version and, because the documentation doesn't mention it...)!

However, I just tried here and entering (in the xml) mapStyle="outdoors" rendered it as Streets. Any idea why?

**Comment by EddyVerbruggen** [comment]
Oh. Hmm. Let me check that this weekend. iOS or Android?

**Comment by EddyVerbruggen** [comment]
I just verified the latest 3.1.3 version shows the correct map style when choosing `mapStyle="outdoors"`.

Note that it looks very much like `streets`, depending on the terrain. For instance, compare these two:
* https://api.mapbox.com/styles/v1/mapbox/outdoors-v10.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#15.86/52.136407/5.292805
* https://api.mapbox.com/styles/v1/mapbox/streets-v10.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#15.86/52.136407/5.292805

The former (`outdoors`) is a bit greener and shows a camping location.
