### ISSUE TITLE
Location Layer Android

### ISSUE THREAD

**Issue by d3mac123** [Yermo/nativescript-mapbox#197]
I have the following lines added into Mapbox's plugin, which allow the camera/map to move according to user location (I added this in the setCenter function, just before the update of the camera positon):
```
theMap.mapboxMap.getTrackingSettings().setMyLocationTrackingMode(com.mapbox.mapboxsdk.constants.MyLocationTracking.TRACKING_FOLLOW);
theMap.mapboxMap.getTrackingSettings().setMyBearingTrackingMode(com.mapbox.mapboxsdk.constants.MyBearingTracking.GPS);
```

Everything worked fine until I noticed the update of Mapbox SDK. Checking their forums, I found this case: https://github.com/mapbox/mapbox-gl-native/issues/9775 which mentions the new Location Layer plugin, which, supposedly, is a better way of handling the camera movement.

Checking Mapbox's SDK documentation, I found this link: https://www.mapbox.com/android-docs/plugins/overview/location-layer/

Any chance to add the ability to enable the camera/map movement natively into the plugin? In iOS the working code is (also added into the setCenter function): 
`theMap.userTrackingMode = MGLUserTrackingMode.MGLUserTrackingModeFollowWithCourse;`

In sum, what I need is this (map rotates depending on my bearing):
https://user-images.githubusercontent.com/4394910/28844322-1c52a672-76b9-11e7-904a-fcf6f51c1481.gif

Related to case #144

**Comment by EddyVerbruggen** [comment]
See the updates in #144.
