### ISSUE TITLE
 Didn't find class "com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin"

### ISSUE THREAD

**Issue by leocrawf** [Yermo/nativescript-mapbox#198]
All Worked well until this morning when I went on the contact page. I can remember using the app contact page about a week ago. 
Here is the consice error:  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin"

Here is the verbose error in android:

System.err: Calling js method run failed
System.err: Error: java.lang.ClassNotFoundException: com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:251)
System.err:     java.lang.Class.forName(Class.java:216)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1010)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:46)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:581)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
System.err:     android.os.Handler.handleCallback(Handler.java:808)
System.err:     android.os.Handler.dispatchMessage(Handler.java:103)
System.err:     android.os.Looper.loop(Looper.java:193)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5339)
System.err:     java.lang.reflect.Method.invokeNative(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:515)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
System.err:     dalvik.system.NativeStart.main(Native Method)
System.err: Caused by: java.lang.NoClassDefFoundError: com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:251)
System.err:     java.lang.Class.forName(Class.java:216)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1010)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:46)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:581)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
System.err:     android.os.Handler.handleCallback(Handler.java:808)
System.err:     android.os.Handler.dispatchMessage(Handler.java:103)
System.err:     android.os.Looper.loop(Looper.java:193)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5339)
System.err:     java.lang.reflect.Method.invokeNative(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:515)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
System.err:     dalvik.system.NativeStart.main(Native Method)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin" on path: DexPathList[[zip file "/data/app/org.nativescript.dcikwlmobile2-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.nativescript.dcikwlmobile2-1, /vendor/lib, /system/lib]]
System.err:     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:497)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:457)
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:251)
System.err:     java.lang.Class.forName(Class.java:216)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1010)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:46)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:581)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
System.err:     android.os.Handler.handleCallback(Handler.java:808)
System.err:     android.os.Handler.dispatchMessage(Handler.java:103)
System.err:     android.os.Looper.loop(Looper.java:193)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5339)
System.err:     java.lang.reflect.Method.invokeNative(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:515)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
System.err:     dalvik.system.NativeStart.main(Native Method)
System.err: File: "file:///data/data/org.nativescript.dcikwlmobile2/files/app/tns_modules/nativescript-mapbox/mapbox.js, line: 145, column: 30
System.err: StackTrace: 
System.err: 	Frame: function:'_showLocation', file:'file:///data/data/org.nativescript.dcikwlmobile2/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 145, column: 31
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.dcikwlmobile2/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 51, column: 37
System.err: 	Frame: function:'invoke', file:'file:///data/data/org.nativescript.dcikwlmobile2/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
System.err: 	Frame: function:'run', file:'file:///data/data/org.nativescript.dcikwlmobile2/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: 	at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
System.err: 	at android.os.Handler.handleCallback(Handler.java:808)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:103)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5339)
System.err: 	at java.lang.reflect.Method.invokeNative(Native Method)
System.err: 	at java.lang.reflect.Method.invoke(Method.java:515)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
System.err: 	at dalvik.system.NativeStart.main(Native Method)
System.err: Caused by: java.lang.ClassNotFoundException: com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin
System.err: 	at java.lang.Class.classForName(Native Method)
System.err: 	at java.lang.Class.forName(Class.java:251)
System.err: 	at java.lang.Class.forName(Class.java:216)
System.err: 	at com.tns.Runtime.getClassForName(Runtime.java:1010)
System.err: 	at com.tns.ClassResolver.resolveClass(ClassResolver.java:46)
System.err: 	at com.tns.Runtime.resolveClass(Runtime.java:581)
System.err: 	... 16 more
System.err: Caused by: java.lang.NoClassDefFoundError: com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin
System.err: 	... 22 more
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin" on path: DexPathList[[zip file "/data/app/org.nativescript.dcikwlmobile2-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.nativescript.dcikwlmobile2-1, /vendor/lib, /system/lib]]
System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
System.err: 	... 22 more
System.err: com.tns.NativeScriptException: 
System.err: Calling js method run failed
System.err: Error: java.lang.ClassNotFoundException: com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:251)
System.err:     java.lang.Class.forName(Class.java:216)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1010)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:46)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:581)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
System.err:     android.os.Handler.handleCallback(Handler.java:808)
System.err:     android.os.Handler.dispatchMessage(Handler.java:103)
System.err:     android.os.Looper.loop(Looper.java:193)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5339)
System.err:     java.lang.reflect.Method.invokeNative(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:515)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
System.err:     dalvik.system.NativeStart.main(Native Method)
System.err: Caused by: java.lang.NoClassDefFoundError: com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:251)
System.err:     java.lang.Class.forName(Class.java:216)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1010)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:46)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:581)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
System.err:     android.os.Handler.handleCallback(Handler.java:808)
System.err:     android.os.Handler.dispatchMessage(Handler.java:103)
System.err:     android.os.Looper.loop(Looper.java:193)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5339)
System.err:     java.lang.reflect.Method.invokeNative(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:515)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
System.err:     dalvik.system.NativeStart.main(Native Method)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin" on path: DexPathList[[zip file "/data/app/org.nativescript.dcikwlmobile2-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.nativescript.dcikwlmobile2-1, /vendor/lib, /system/lib]]
System.err:     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:497)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:457)
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:251)
System.err:     java.lang.Class.forName(Class.java:216)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1010)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:46)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:581)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
System.err:     android.os.Handler.handleCallback(Handler.java:808)
System.err:     android.os.Handler.dispatchMessage(Handler.java:103)
System.err:     android.os.Looper.loop(Looper.java:193)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5339)
System.err:     java.lang.reflect.Method.invokeNative(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:515)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
System.err:     dalvik.system.NativeStart.main(Native Method)
System.err: File: "file:///data/data/org.nativescript.dcikwlmobile2/files/app/tns_modules/nativescript-mapbox/mapbox.js, line: 145, column: 30
System.err: StackTrace: 
System.err: 	Frame: function:'_showLocation', file:'file:///data/data/org.nativescript.dcikwlmobile2/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 145, column: 31
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.dcikwlmobile2/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 51, column: 37
System.err: 	Frame: function:'invoke', file:'file:///data/data/org.nativescript.dcikwlmobile2/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
System.err: 	Frame: function:'run', file:'file:///data/data/org.nativescript.dcikwlmobile2/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: 	at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
System.err: 	at android.os.Handler.handleCallback(Handler.java:808)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:103)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5339)
System.err: 	at java.lang.reflect.Method.invokeNative(Native Method)
System.err: 	at java.lang.reflect.Method.invoke(Method.java:515)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
System.err: 	at dalvik.system.NativeStart.main(Native Method)
System.err: Caused by: java.lang.ClassNotFoundException: com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin
System.err: 	at java.lang.Class.classForName(Native Method)
System.err: 	at java.lang.Class.forName(Class.java:251)
System.err: 	at java.lang.Class.forName(Class.java:216)
System.err: 	at com.tns.Runtime.getClassForName(Runtime.java:1010)
System.err: 	at com.tns.ClassResolver.resolveClass(ClassResolver.java:46)
System.err: 	at com.tns.Runtime.resolveClass(Runtime.java:581)
System.err: 	... 16 more
System.err: Caused by: java.lang.NoClassDefFoundError: com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin
System.err: 	... 22 more
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin" on path: DexPathList[[zip file "/data/app/org.nativescript.dcikwlmobile2-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.nativescript.dcikwlmobile2-1, /vendor/lib, /system/lib]]
System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
System.err: 	... 22 more
ActivityManager: Process org.nativescript.dcikwlmobile2 (pid 10396) has died.

**Comment by EddyVerbruggen** [comment]
You probably just need to remove the platforms/android folder and build the app again.

**Comment by leocrawf** [comment]
I tried that many times already but I got the same result.

**Comment by BeatPots** [comment]
Hi,
I have the same errore when I try to get the user location:

Code:

```
this.mapbox.show({
  ..
  }).then(
            (showResult) => {
                  this.mapbox.getUserLocation().then((userLocation) => {
                  console.log("Current user location: " +  userLocation.location.lat + ", " + 
                   userLocation.location.lng);
    
                this.currLatitude = userLocation.location.lat;
                this.currLongitude = userLocation.location.lng;
                });
  },
  (error: string) => {
        console.log("mapbox show error: " + error);
  }
);
```

**Comment by BeatPots** [comment]
Ok, there is this error but it still seems to work:
the user location is recevied!

UPDATE: the mapbox.getUserLocation() returns the position but it is not shown on the map!

**Comment by leocrawf** [comment]
How do you get it to work? When ever this happens, the app crashes with the above exception.

**Comment by leocrawf** [comment]
Was this resolved?

**Comment by EddyVerbruggen** [comment]
Please update to 4.0.0 (about to be released) and try again. Make sure to remove the platforms folder after updating the plugin.
