### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by RusEu** [Yermo/nativescript-mapbox#2]
when i click show the app stops with an error

**Comment by wisonye** [comment]
Hello, please Help on this !!! :) After I upgrade to XCode7.2( IOS 9.2 ), my NativeScript project cannot compile, and show this error in terminal output:

``` javascript
CodeSign error: entitlements are required for product type 'Application' in SDK 'Simulator - iOS 9.2'. Your Xcode installation may be damaged.
```

But after I remove this plugin( and also disable the code related to using MapBox temporary ), compile works, then I check the information from:

``` javascript
https://www.mapbox.com/ios-sdk/#cocoapods
```

I noticed that they upgrade to 3.0.1, then and I check your "podfile" which still using "2.1.2" like this:

``` javascript
pod 'Mapbox-iOS-SDK', '~> 2.1.2'
```

Is that just change to "~> 3.0.1" can works( no need to do anything in "mapbox.ios.js" ) ???

**Comment by EddyVerbruggen** [comment]
Probably no longer an issue with the latest version.
