### ISSUE TITLE
calloutTap not working after navigating back

### ISSUE THREAD

**Issue by bytesoverflow** [Yermo/nativescript-mapbox#203]
I use calloutTap on the markers to navigate to another screen. Everything works fine first time round but when i navigate back to the map the calloutTap function stops working...

```
public markerCallback(poi: Poi) {
    this.data.storage = poi;
    this.routerExtensions.navigate(["/poidetail"]);
}

this.pois.forEach((p)=>{
    markers.push({lat:p.lat, lng:p.lng, title:p.title, subtitle: p.category, onCalloutTap:()=>{console.log("onCalloutTap");this.markerCallback(p);}})
})
mapView.addMarkers(markers).then(()=>{
    mapView.setViewport({
        bounds: {
            north: maxLat,
            east: maxLng,
            south: minLat,
            west: minLng
        },
        animated: true
    });
});
```

**Comment by bytesoverflow** [comment]
The issue seems to be on my end. If i navigate to a different page and then navigate back the calloutTap continues to fire.

**Comment by bytesoverflow** [comment]
When I navigate from the calloutTap to a screen which contains another map, and then navigate back, the calloutTap is not longer fired.

**Comment by EddyVerbruggen** [comment]
I can imagine that happens because loading a second map probably clears the internal cache of the first one. If the first one would be recreated then this wouldn't happen. So perhaps you can re-add the markers in this case?

**Comment by bytesoverflow** [comment]
Ok. onMapReady isn't called when navigating back so when would be the best time to re generate the markers? onNavigatedTo?

**Comment by EddyVerbruggen** [comment]
I assume in your case the map is already loaded (because you went 'back', it wasn't destroyed). So any time really.

**Comment by bytesoverflow** [comment]
Ok thanks, seems to be working. Do i need to clear the markers before calling addMarkers again?

**Comment by EddyVerbruggen** [comment]
Yeah I would do that - you won't see it, but there will be markers (exactly) on top of each other.
