### ISSUE TITLE
Marker onCalloutTap can't resolve 'this' in an angular component

### ISSUE THREAD

**Issue by wanpeng2008** [Yermo/nativescript-mapbox#206]
I config 'onCalloutTap' function on the marker, but the var 'this' in this function unexpectedly  refers to the marker instead of the component itself.

env: angular5+nativescript

here are the defined member functions in my component
````
class CustomerComponent {
   lodeMarkers(){
           ...
                this.markers.push(
                    {
                        id: customer.id,
                        ...
                        onCalloutTap: this.onCalloutTap,
                        // here should be: 
                        // onCalloutTap: (marker)=>{this.onCalloutTap(marker);}
                    }
                );
            ...
    }
    onCalloutTap(marker){
        console.dir(this) // Here outputs the content of marker instead of the component, so strange
        this.navigateToCustomerDetailPage(marker.id) // error here: 'navigateToCustomerDetailPage' not recognized
    }
    navigateToCustomerDetailPage(id) {...}
    ...
}
````

> System.err: com.tns.NativeScriptException: 
> System.err: Calling js method onInfoWindowClick failed
> System.err: 
> System.err: TypeError: this.navigateToCustomerDetailPage is not a function

**Comment by EddyVerbruggen** [comment]
I don’t see TypeScript arrow functions so that’s typing JS behavior, right?

**Comment by wanpeng2008** [comment]
@EddyVerbruggen 
Thank you for correcting my mistakes
