### ISSUE TITLE
Implement FitToBounds

### ISSUE THREAD

**Issue by burkeholland** [Yermo/nativescript-mapbox#21]
It looks like the MapBox SDK supports fitting the map to an array of geolocation points. It would be nice if we could do this by passing an array of markers so the map zooms to fit the markers. I believe the proper API is `visibleCoordinateBounds`.

https://www.mapbox.com/ios-sdk/api/3.3.1/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)visibleCoordinateBounds

**Comment by Stavanger75** [comment]
+1

**Comment by EddyVerbruggen** [comment]
Added to 2.1.0 as `setViewport` which can also be used from the `mapReady` event of an XML-declared map.

I'm pondering adding a convenience 'fitToMarkers' function but until then you'll need to pass the outer boundaries of your markers to the `setViewport` function. Should be a fairly easy calculation.
