### ISSUE TITLE
Map is blank

### ISSUE THREAD

**Issue by yzyii** [Yermo/nativescript-mapbox#211]
I pulled the demo project from this repo and replaced all accessTokens in main-page.xml with my own.

All the maps are blank with different background colours depending on what mapStyle it is. e.g. "satellite" is black, "streets" is grey.

Running it on emulator emulating Android 6.0 (Nexus 5).

**Comment by EddyVerbruggen** [comment]
I'm not sure what hardware is powering your emulator, but I have no problem with mine so there's not much I can do about that. Please reopen if a real device has the same issue.

**Comment by yzyii** [comment]
Yep, tested it on my Pixel and it works fine. Not sure why it's failing on my emulator. I'll keep looking into it.
