### ISSUE TITLE
animateCamera with target increases the zoomLevel to maximum in iOS

### ISSUE THREAD

**Issue by mohammadrafigh** [Yermo/nativescript-mapbox#215]
calling animateCamera with a target increases the zoomLevel to maximum in iOS.

```
this.map.animateCamera({
    target: {
        lat: point.lat,
        lng: point.lng
    },
    duration: 2000
});
```

also adding `zoomLevel` does not make any difference.

**Comment by EddyVerbruggen** [comment]
Yeah, if you set `altitude` it'll work. But let me see if I can grab those other values (like `altitude`) from the current camera and apply those if not set.
