### ISSUE TITLE
The App crashs on Android when using nativescript-vue - missing toHumanReadableAscii method

### ISSUE THREAD

**Issue by andreMariano90** [Yermo/nativescript-mapbox#216]
Hello Guys! I already tried to find it on google and even on the mapbox API but without success. 

I am developing my App using nativescript-vue. But everytime I try to render the map on Android it crashes always saying its missing this method
`Error: java.lang.NoSuchMethodError: No static method toHumanReadableAscii(Ljava/lang/String;)Ljava/lang/String; in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in /data/app/com.app.sample-1/base.apk)
    com.mapbox.services.android.telemetry.MapboxTelemetry.setUserAgent(MapboxTelemetry.java:315)
    com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:174)
    com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:125)`

**Android Version: 6.0**

Do I have to add any lib at my app.gradle?
Here follows my gradle configuration
`android {
  compileSdkVersion 27
  buildToolsVersion "27.0.3"

  defaultConfig {
    generatedDensities = []
    applicationId = "com.app.sample"
  }
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  
}

ext{
   supportVersion = "27.1.0"
}

configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:27.1.0'
        force 'com.android.support:design:27.1.0'
    }
}`

When using it on iOS it works like a charm.

**Comment by andreMariano90** [comment]
Hi Guys. If anybody is experiencing this, I found a workaround. Specially on nativescript-vue. In your gradle.app you must compile the version 5.5.1 or greater (where it was fixed) and then force every project (including this one) to use it

@EddyVerbruggen , I didn't test it on another tecnologies, but just by releasing with the latest version should do the trick..

Here follows the workaround in the app.gradle:

Add both configs:
```gradle
configurations.all {
    resolutionStrategy {
        force 'com.mapbox.mapboxsdk:mapbox-android-sdk:5.5.1'
    }
}

dependencies{
compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.5.1@aar'){
        transitive=true
    }
}
```

I Just didn't close it so you can read it @EddyVerbruggen

**Comment by EddyVerbruggen** [comment]
Thanks, @andreMariano90!

I'm about to release version 4.0.0 in which the Mapbox Android SDK has been bumped to 6.0.1, so we should be good now.

Cheers!
