### ISSUE TITLE
Feature Request: Move Map Markers

### ISSUE THREAD

**Issue by rohanrichards** [Yermo/nativescript-mapbox#226]
Is there a way to pass back a reference to Map Markers from the AddMarkers method on the map object? If I could get my hands on the newly added markers I might be able to change their position.
How hard would it be to actually bind to the objects passed into this method and watch them for changes?

I have never worked with the business logic of data binding so I'm not sure how you'd go about watching for changes. 

Are you currently accepting public PR's on this plugin? If so, can anyone point me to a good starting point for implementing something like this to allow for real time map markers? Or even just simply a way to update their position with a reference.

**Comment by redriverit** [comment]
Interested in this as well. I have used the mapbox GL JS library to connect to firebase real-time data sources and update my markers as the data changes (moving vehicles). I would love to see this capability in nativescript. Maybe even include some of the dynamic styling for the points/markers.

**Comment by EddyVerbruggen** [comment]
Here you go: https://github.com/EddyVerbruggen/nativescript-mapbox#updating-markers

**Comment by rohanrichards** [comment]
Hi @EddyVerbruggen how do we do this? In the documentation you are just creating a JS Object, it has no `update()` method.
I'm thinking we need to somehow get the reference to the actual marker object, is it returned from addMarkers? This should be added to the readme if that is the case.

Edit:
have tried
```
let markers = this.map.addMarkers([marker]) //looks like a promise type object
//so tried
this.map.addMarkers([marker]).then(markers => { console.log(markers) }) //returns undefined
//finally tried
this.map.addMarkers([marker]).then(()=> {
	console.log(this.map.mapView.mapboxMap.getMarkers())
        // >>> [ ]
});
```

Final Edit:
After consulting the examples I can see where I went wrong, you need to use the interface and cast your marker into a MapMarker like this:

```
import { Mapbox, MapStyle, LatLng, Viewport, MapboxMarker } from "nativescript-mapbox";
...
marker = <MapboxMarker>{
	lat: lat,
	lng: lng,
}
```
