### ISSUE TITLE
Feature Request: Features and FeatureCollections

### ISSUE THREAD

**Issue by rohanrichards** [Yermo/nativescript-mapbox#228]
Map Markers and layers should accept FeatureCollections or Feature types.

I have developed a back-end that provides GeoJSON data to a dashboard that implements mapboxGL. It quite happily spits out a FeatureCollection which mapboxGL consumes and automatically generates map markers for (I provide it as a data source and create a Layer from the source).

Now I want to provide this same data to my App using this plugin, however the AddMarkers method on the map object does not accept a GeoJSON Feature. I really don't want to have to map my FeatureCollection to deconstruct the data into something this plugin can use, that would be very innefficient.

Here's an example of the data my back-end provides:

```
{
  "type": "geojson",
  "cluster": true,
  "clusterMaxZoom": 14,
  "clusterRadius": 50,
  "data": {
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature",
        "geometry": {
          "type": "Point",
          "coordinates": [
            152.918075173855,
            -27.3835808006743
          ]
        },
        "properties": {
          "icon": "suitcase",
          "name": "Map Marker 2",
          "info": "this is a map marker",
        }
      }
    ]
  }
}
```

**Comment by wyattp11** [comment]
Did you see the addGeoJsonClustered function in the prototypes? Haven't tried it yet but I assume it takes GeoJSON.

**Comment by redriverit** [comment]
I would also like to see the ability to integrate geoJSON features and featureCollections. Most all geo data sources are now appearing as GeoJSON, so this would be extremely helpful in moving forward.

**Comment by lochstar** [comment]
Has anyone happened upon a solution for this yet?
