### ISSUE TITLE
Additional style for Markers

### ISSUE THREAD

**Issue by shivapersad** [Yermo/nativescript-mapbox#23]
Hi,

Is there an additional style for Markers? I want to include two types of Markers on a Mapbox map to signify two different types of locations on a map. Thanks.

**Comment by EddyVerbruggen** [comment]
The [demo app] uses a few different [marker styles](https://github.com/EddyVerbruggen/nativescript-mapbox-demo/tree/master/Mapbox/app/res/markers).
