### ISSUE TITLE
removeMarkers broken on Android.

### ISSUE THREAD

**Issue by yzyii** [Yermo/nativescript-mapbox#231]
This is probably a duplicate of https://github.com/EddyVerbruggen/nativescript-mapbox/issues/229

removeMarkers() without supplying a list of ids doesn't work on Android. I've tested it using the demo project in the repo running an an Android Pixel Phone.

Clicking the "Add 4 Markers" button adds 4 markers as expected. Clicking the "Remove All Markers" doesn't do anything except print "Mapbox doRemoveAllMarkers done" to console.

The "Remove 2 Markers" functionality where you pass in the ids of the markers works fine.

I think it is only broken for Android. It appears to work fine on iOS.

**Comment by EddyVerbruggen** [comment]
Thanks for bringing this to my attention. Fixed in 4.1.0.
