### ISSUE TITLE
Build error on Android, related to source level 1.8

### ISSUE THREAD

**Issue by EddyVerbruggen** [Yermo/nativescript-mapbox#234]
See https://github.com/mapbox/mapbox-java/issues/782

**Comment by yoat** [comment]
This issue is not fixed. The related bug advises users that Android Studio 3.1 will not have this issue and some other notes about Kotlin.

We are not using Android Studio (nor Kotlin that I am aware of) so how can we resolve this in NativeScript via Sidekick?

**Comment by EddyVerbruggen** [comment]
How do you suggest this plugin to fix that? It kinda outside of its control..

**Comment by yoat** [comment]
The resolution of the other issue is to "do nothing and use Android Studio", which isn't a solution in NativeScript.  If there is no resolution available to NativeScript then does that mean nativescript-mapbox is totally unusable?

I'm just looking for confirmation (is the issue in this plugin or that Java project?).  Is nativescript-mapbox completely broken for everyone?  If there is any hope it works then I'd like to use it, but if it's broken I can file a bug on the other project or give up on mapbox entirely.

Thanks for any info!

**Comment by EddyVerbruggen** [comment]
I don’t use sidekick but wonder if 4.1.0 of this plugin fixes it for you.
