### ISSUE TITLE
Add a method to remove polygons

### ISSUE THREAD

**Issue by xjpmauricio** [Yermo/nativescript-mapbox#237]
Hi, I'm having trouble removing existing Polylines on Android (I've not tested on IOS). 
This is how I add them:
```typescript
this.map.addPolygon({
	id: this.circular_polyline_id,
	fillColor: new Color("#0099FF"),
	fillOpacity: 0.7,
	points: circlePoints.map(c => {
		return {
			'lat': c[1],
			'lng': c[0]
		}
	})
});
```
Before adding, I try to remove them like this:
```typescript
this.map.removePolylines([this.circular_polyline_id]).then(response => {  

});
```
I've tried everything, even using setTimeout, etc.

Any ideias what I'm doing wrong?

**Comment by EddyVerbruggen** [comment]
You're adding a poly**gon** but remove a poly**line**.

The available functions currently are: `addPolygon`, `addPolyline`, and `removePolylines`.

**Comment by xjpmauricio** [comment]
@EddyVerbruggen, thanks for the quick response but, how do I remove an existing polygon ?

**Comment by EddyVerbruggen** [comment]
There's currently no exposed function to do that.

**Comment by xjpmauricio** [comment]
So, how could I draw a circle with a fill color without using the addPolygon function ?

This is what I can do with the addPolygon function :

![addpolygon](https://user-images.githubusercontent.com/5897335/42209299-32e82e02-7ea6-11e8-9171-c3f446370f17.png)

**Comment by EddyVerbruggen** [comment]
You could either send a PR to add the remove function, or wait 15 minutes for me to add it.

**Comment by xjpmauricio** [comment]
@EddyVerbruggen, I'll gladly wait 15 minutes for your function! :-)

**Comment by EddyVerbruggen** [comment]
4.1.1 released ➡️ grab it while it's 🔥

Make sure to read the updated docs and or demo app to see how to use it.

**Comment by xjpmauricio** [comment]
I already update to the latest version, it works! Thanks!!!

**Comment by blipk** [comment]
sorry to revive old issue, but is there a way to draw circles from a centre and radius with this plugin? or will I have to draw a 'rough' circular polygon from multiple points?
