### ISSUE TITLE
Global mapbox instance

### ISSUE THREAD

**Issue by keerl** [Yermo/nativescript-mapbox#241]
Hi,

I have a NativeScript Angular app that has multiple tabs and currently when I navigate through the tabs each time I get to the map one it has to reload the map which takes about a second.

I am wondering if I could declare the map to be global somehow so it doesn't get destroyed each time I navigate away.

I think I could do it if I can figure out how to declare a map programmatically in angular, but it is only documented for TypeScript/XML.

Any tips on how I could declare a map instance programmatically instead of in the HTML?

**Comment by EddyVerbruggen** [comment]
The programmatically declared map is not Angular/XML-specific. What's the issue?

**Comment by keerl** [comment]
I must be using it wrong then. When I try to insert the code into ngOnInit() I get the error "mapbox.show is not a function". I also do not understand where the map is added to, like is there a way to attach it to a specific container element in the HTML? Sorry if these are bad questions, I am new to NativeScript/Angular.

**Comment by EddyVerbruggen** [comment]
Those are good questions, but you could also look at the demo app. The programmatic approach doesn't need a container; it's fullscreen and you can add margins to all sides to make it not cover certain parts. That approach is not perfect and that's why I added the declarative version later.

https://github.com/EddyVerbruggen/nativescript-mapbox/blob/21861478fdad362e589ae91fbc9cd6240f9bc675/demo/app/main-view-model.ts#L19-L53

**Comment by keerl** [comment]
Thanks, I will take a look at the demo code. So there is no way to add it to a container? My app design has the map as the background element with some UI overlays on top of it.

**Comment by EddyVerbruggen** [comment]
Like I said, that's what the UI-based version is for. But in that case, if your map is on a master page and you navigate to children then it should be retained. If you load another master route it's normal that it's destroyed.

**Comment by keerl** [comment]
Ok I understand now. I will have to restructure my app to account for that kind of master/child relation. Thanks.
