### ISSUE TITLE
Issue loading the map

### ISSUE THREAD

**Issue by abunuwas** [Yermo/nativescript-mapbox#242]
I followed the following tutorial to get started with mapbox and nativescript-vue: https://www.nativescript.org/blog/include-feature-rich-maps-in-a-nativescript-vue-app-with-mapbox

However, when I run the app, the map doesn't load. I click the button and just nothing happens. The debugger doesn't display any errors either. This is not a problem with my mapbox API key, as I've tried loading the map in a plain html file and it works. 

For reference, here's the code that I've written for this test:
https://github.com/abunuwas/nativescript-vue-mapbox-test
(relevant bits [here](https://github.com/abunuwas/nativescript-vue-mapbox-test/blob/master/src/main.js) and [here](https://github.com/abunuwas/nativescript-vue-mapbox-test/blob/master/src/components/HelloWorld.vue) )

Am I doing anything very obviously wrong? Any help appreciated, thanks.

**Comment by EddyVerbruggen** [comment]
Hmm, doesn't look wrong to me. Does your console.log (on map loaded event) run?

**Comment by abunuwas** [comment]
@EddyVerbruggen thanks for your comment, interestingly I just run the application again and the map worked. Can't really tell what changed in between the two runs. This ticket can be closed now!

**Comment by msl2000** [comment]
I'd like to open this again. Having the exact same issue. OnMapReady function is not working and I followed the same tutorial. I tried rerunning and uninstalling multiple times but it's still failing. Running on Android and using Mapbox 4.4.1

Code as follows..

<template>
<StackLayout>
    <Label text="MAP BOX SHOULD BE HERE"></Label>
    <Mapbox :accessToken="token" mapStyle="traffic_day" latitude="37.7397" longitude="-121.4252" hideCompass="true" zoomLevel="12" showUserLocation="false" disableZoom="false" disableRotation="false" disableScroll="false" disableTilt="false" @mapReady="onMapReady($event)">
    </Mapbox>
</StackLayout>
</template>

```
<template>
<StackLayout>
    <Label text="MAP BOX SHOULD BE HERE"></Label>
    <Mapbox :accessToken="token" mapStyle="traffic_day" latitude="37.7397" longitude="-121.4252" hideCompass="true" zoomLevel="12" showUserLocation="false" disableZoom="false" disableRotation="false" disableScroll="false" disableTilt="false" @mapReady="onMapReady($event)">
    </Mapbox>
</StackLayout>
</template>

<script>
import * as utils from "utils/utils";
export default {
    data() {
        return {
            token: "Token Here"
        }
    },
    mounted() {
        console.log("Mounting the map");
    },
    methods: {
        onMapReady(args) {
            console.log("MAP IS READY");
            args.map.addMarkers([{
                lat: 37.7397,
                lng: -121.4252,
                title: "Tracy, CA",
                subtitle: "Home of The Polyglot Developer!",
                onCalloutTap: () => {
                    utils.openUrl("https://www.thepolyglotdeveloper.com");
                }
            }]);
        }
    }
}
</script>


```
