### ISSUE TITLE
Map Not showing on iOS Simulator

### ISSUE THREAD

**Issue by BMwanza** [Yermo/nativescript-mapbox#245]
Trying to get the mapbox to show on iOS, tried looking in my package.JSON folder:
    "tns-ios": {
      "version": "4.1.1"
    }
    "nativescript-mapbox": "^4.1.1",

XML: <Page navigatingTo="onNavigatingTo" class="page"
    xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:map="nativescript-mapbox" >
    <ActionBar class="action-bar">
        <Label class="action-bar-title" text="Home"></Label>
    </ActionBar>

    <StackLayout>
        <map:MapboxView
            latitude="52.3702160"
            longitude="4.8951680"
            zoomLevel="3"
            mapStyle="light"
            hideAttribution="true"
            showUserLocation="true"
            hideCompass="false"
            accessToken="sk.eyJ1IjoiZWRkeXZlcmJydWdnZW4iLCJhIjoia1JpRW82NCJ9.OgnvpsKzB3GJhzyofQNUBw">
        </map:MapboxView>

    </StackLayout>
</Page>
I'm declaring the mapbox in my XML using MapboxView, no error messages, just simply won't show. I get the prompt that asks for permissions for my app to use user location, but no response after that.

**Comment by EddyVerbruggen** [comment]
This raises a few questions:

- Does the demo app in this repo work?
- Does it work on a real device?

**Comment by BMwanza** [comment]
Regarding the Demo app working:
No it does not, I may be doing something wrong here but here's what I do to try to get the demo app up and running:
git clone this repo
cd into demo/
tns run ios --emulator
The app is successfully built, then the following error message appears

Project successfully built.
Installing...
Successfully installed on device with identifier '66335FDD-3BC5-4AC7-92C6-ABCD524FAA11'.
Successfully transferred all files.
Refreshing application...
Successfully synced application org.nativescript.mapbox on device 66335FDD-3BC5-4AC7-92C6-ABCD524FAA11.
[10:46:17 a.m.] File change detected. Starting incremental compilation...
[10:46:20 a.m.] File change detected. Starting incremental compilation...
[10:46:20 a.m.] File change detected. Starting incremental compilation...
[10:46:21 a.m.] File change detected. Starting incremental compilation...



***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x1059ec649 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x105a14c5b NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x10630a5c1 ffi_closure_unix64_inner
4   0x10630af22 ffi_closure_unix64
5   0x10ad6ea65 _CFXRegistrationPost
6   0x10ad6e7a1 ___CFXNotificationPost_block_invoke
7   0x10ad30422 -[_CFXNotificationRegistrar find:object:observer:enumerator:]
8   0x10ad2f5a1 _CFXNotificationPost
9   0x1069efe57 -[NSNotificationCenter postNotificationName:object:userInfo:]
10  0x10702c469 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:]
11  0x1070315cb -[UIApplication _runWithMainScene:transitionContext:completion:]
12  0x1073f3f7e __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke
13  0x1077c6a39 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:]
14  0x1073f3bba -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]
15  0x1073f43db -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:]
16  0x107d65614 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke
17  0x107d654ae -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]
18  0x107a4975d __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke
19  0x107c444b7 _performActionsWithDelayForTransitionContext
20  0x107a49627 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]
21  0x1077c60e0 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:]
22  0x10702feac -[UIApplication workspace:didCreateScene:withTransitionContext:completion:]
23  0x107602bcb -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:]
24  0x1118da2f3 -[FBSSceneImpl _didCreateWithTransitionContext:completion:]
25  0x1118e2cfa __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2
26  0x10cefa709 _dispatch_client_callout
27  0x10ceff8c1 _dispatch_block_invoke_direct
28  0x11190e470 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
29  0x11190e12e -[FBSSerialQueue _performNext]
30  0x11190e68e -[FBSSerialQueue _performNextFromRunLoopSource]
31  0x10ad75bb1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
JavaScript stack trace:
1   require@file:///app/main-view-model.js:7:36
2   anonymous@file:///app/main-view-model.js:7:36
3   evaluate@[native code]
4   moduleEvaluation@[native code]
5   @[native code]
6   promiseReactionJob@[native code]
7   require@[native code]
8   anonymous@file:///app/main-page.js:4:32
9   evaluate@[native code]
10  moduleEvaluation@[native code]
11  @[native code]
12  promiseReactionJob@[native code]
13  require@[native code]
14  _loop_1@file:///app/tns_modules/tns-core-modules/globals/globals.js:60:30
15  loadModule@file:///app/tns_modules/tns-core-modules/globals/globals.js:68:30
16  @file:///app/tns_modules/tns-core-modules/ui/builder/builder.js:65:37
17  @file:///app/tns_modules/tns-core-modules/ui/builder/builder.js:81:39
18  navigate@file:///app/tns_modules/tns-core-modules/ui/frame/frame-common.js:118:49
19  createRootView@file:///app/tns_modules/tns-core-modules/application/application.js:238:31
20  setWindowContent@file:///app/tns_modules/tns-core-modules/application/application.js:202:38
21  didFinishLaunchingWithOptions@file:///app/tns_modules/tns-core-modules/application/application.js:139:30
22  @[native code]
23  onReceive@file:///app/tns_modules/tns-core-modules/application/application.js:30:32
24  UIApplicationMain@[native code]
25  start@file:///app/tns_modules/tns-core-modules/application/application.js:264:26
26  anonymous@file:///app/app.js:4:18
27  evaluate@[native code]
28  moduleEvaluation@[native code]
29  @[native code]
30  promiseReactionJob@[native code]
JavaScript error:
file:///app/main-view-model.js:7:36: JS ERROR Error: Could not find module 'nativescript-mapbox'. Computed path '/Users/BMwanza/Library/Developer/CoreSimulator/Devices/66335FDD-3BC5-4AC7-92C6-ABCD524FAA11/data/Containers/Bundle/Application/BD89C6B9-248F-4E7E-B7E7-BD87E71AAA00/demo.app/app/tns_modules/nativescript-mapbox'.

**Comment by EddyVerbruggen** [comment]
Before you try running the demo again, check if it helps to set a height and width on the mapview.

## running the demo app
Throw away what you have, then:

```bash
git clone https://github.com/EddyVerbruggen/nativescript-mapbox
cd nativescript-mapbox
cd src
npm run demo.ios
```

Let it run for a while and this will be the result:

![simulator screen shot - iphone 6 - 2018-08-10 at 17 59 07](https://user-images.githubusercontent.com/1426370/43968349-2248bd52-9cc7-11e8-9c1c-95aaa7e51d47.png)

**Comment by BMwanza** [comment]
Okay sweet that worked, but how should I go about solving my original problem of it not showing in my ios application?

**Comment by EddyVerbruggen** [comment]
Did you try setting the height/width as I suggested? Also see the way the demo does it.

**Comment by BMwanza** [comment]
Yes adding a ContentView with width and height setting worked thanks I will close this now Thanks so much Eddy :)
