### ISSUE TITLE
[question] is it possible to deliver a downloaded map within my app  ?

### ISSUE THREAD

**Issue by c1ngular** [Yermo/nativescript-mapbox#26]
for instance , i want to download a map of a certain region in advance , and ship it with app package ,  save user's time and data connection ! if possible , how should i achieve such goal ?
thank you

**Comment by EddyVerbruggen** [comment]
I don't think there is an official way to do that (but please ask the Mapbox folks to be sure). A reason could be that those things need to expire because road data gets outdated quickly in certain regions.
