### ISSUE TITLE
Showing Map Programmatically

### ISSUE THREAD

**Issue by BMwanza** [Yermo/nativescript-mapbox#262]
Is it possible to have some kind of button show together with the map using map.show() to allow the user to destroy the map? I find it hard setting up dynamic margins when using map.show to accommodate for multiple devices

**Comment by EddyVerbruggen** [comment]
That's actually [part of the demo app](https://github.com/EddyVerbruggen/nativescript-mapbox/blob/4ac99bb5dbd3a4c535b1c7e6136caa12f3c696b5/demo/app/main-page.xml#L87), if I interpret your question correctly.

**Comment by BMwanza** [comment]
Not exactly what I meant, for example, I want my programmatically defined MapBox to cover everything but the Action Bar in my app. However I don't know how to set the value of the top margin to accomodate for different screen sizes and devices.

For example, the iPhone X's Action bar tends is a bit longer than the iPhone 6 - 8's. Which results in the mapbox cutting off the a bit of the action bar. So I was hoping that I could have a button that can be displayed on the mapbox when it is in full screen mode

Hope I was being a bit more clear

**Comment by EddyVerbruggen** [comment]
Why not use the declarative map like this screenshot? https://github.com/EddyVerbruggen/nativescript-pluginshowcase/tree/master/app/mapping

**Comment by BMwanza** [comment]
Bless you Eddy!! This looks like it would be exactly what I need! Though, is their a pure JS or even typescript demo app of that that I can use as direction on how to implement? I'm not really sure how to go about doing this

**Comment by EddyVerbruggen** [comment]
Yeah, it's in this plugin repo actually. Note that the only difference with that Angular implementation is how you import the view tag. Here's the declaration (mind the namespace declaration on the first line of that file):

https://github.com/EddyVerbruggen/nativescript-mapbox/blob/4ac99bb5dbd3a4c535b1c7e6136caa12f3c696b5/demo/app/main-page.xml#L9-L17

**Comment by BMwanza** [comment]
Oh sorry I need to back track a bit, I cannot use the declarative mapbox at all because the page in which I am showing the mapbox has some complex functionality and is easier to handle if the mapbox is declared programatically. 

But If there is a way to get the FAB to be shown with my programmatically defined map that will work

**Comment by EddyVerbruggen** [comment]
Hmm, I'm not sure you can add that on top of the programmatic map (because I never tried it). Guess you'll need to try it.
