### ISSUE TITLE
marker sizing

### ISSUE THREAD

**Issue by abegehr** [Yermo/nativescript-mapbox#264]
Thank you for providing this plugin!
I was able to use png images as custom markers.

Is it possible to set icon sizing programmatically?

Thank you.

**Comment by nadjibnet** [comment]
You can change the scale of your Marker icon Drawable Object.
`Drawable icon = getResources().getDrawable(R.drawable.MyIconPNG);

  WrappedDrawable wrappedDrawable = new WrappedDrawable(icon);

  wrappedDrawable.setBounds(0,0,32,32);

  marker.setIcon(wrappedDrawable);`

You can find the WrappedDrawable class source code in the link below:
https://stackoverflow.com/questions/4609456/set-drawable-size-programmatically
