### ISSUE TITLE
App is crashing with map while moving

### ISSUE THREAD

**Issue by d3mac123** [Yermo/nativescript-mapbox#265]
Hi @EddyVerbruggen,

My app, which always worked fine for more than a year, started getting crazy and crashing every time I try to load data while in movement. See the video https://youtu.be/yonBlB3gyiI to understand it better.

If I am connected (via cable) to my computer, app freezes and the console simply stop (no messages, errors, anything). If I am not connected via cable, phone app crashes (like you probably saw in the video).

I know you don't check people's app but I am begging if you can, at least, take a quick look at my repo (flight-page.js is the culprit) at https://github.com/d3mac123/ppgFinder - maybe your pro eyes can catch something from my side or from the plugin side. After all, in this page, the map acts only as a static picture (do you think this can be the issue?).

You are my last hope before removing the app from the store and move on from Nativescript (I am just a designer with development aspirations). 

Really appreciate your support,
Alex

**Comment by d3mac123** [comment]
According to Nicklliev (from the Nativescript support), this seems to be:

> "The issue is most likely related to an event listener triggered when the mapbox plugin detects a change in the coordinates."

Can you please take a look @EddyVerbruggen ?

**Comment by EddyVerbruggen** [comment]
Which platform do you experience this on?

**Comment by d3mac123** [comment]
Ios

Alex Souza
On Oct 15, 2018, 1:20 PM -0400, Eddy Verbruggen <notifications@github.com>, wrote:

Which platform do you experience this on?

**Comment by EddyVerbruggen** [comment]
Sorry, I didn't have time to look at this before. Can you check in the 'firebase.nativescript.json' file so I can configure the Firebase plugin in the same way you have?

**Comment by d3mac123** [comment]
here it goes:
`{
    "using_ios": true,
    "using_android": true,
    "remote_config": false,
    "messaging": true,
    "crash_reporting": false,
    "storage": true,
    "facebook_auth": true,
    "google_auth": false,
    "admob": false,
    "invites": false,
    "firestore": true
}`

@EddyVerbruggen I have no words to say how much I appreciate what you are doing for all of us. I feel really bad to bother you with issues like that. Sorry!

**Comment by EddyVerbruggen** [comment]
Thanks for the kind words. I guess support comes with the OSS job ;)

Would you be able to also provide me with `/app/App_Resources/iOS/GoogleService-Info.plist`?

**Comment by d3mac123** [comment]
Man, you rock!

here it goes:
`<plist version="1.0">
<dict>
	<key>AD_UNIT_ID_FOR_BANNER_TEST</key>
	<string>ca-app-pub-3940256099942544/2934735716</string>
	<key>AD_UNIT_ID_FOR_INTERSTITIAL_TEST</key>
	<string>ca-app-pub-3940256099942544/4411468910</string>
	<key>CLIENT_ID</key>
	<string>1008910072649-fh5hu67gdn128428bg1qsskl7gbcdbnn.apps.googleusercontent.com</string>
	<key>REVERSED_CLIENT_ID</key>
	<string>com.googleusercontent.apps.1008910072649-fh5hu67gdn128428bg1qsskl7gbcdbnn</string>
	<key>API_KEY</key>
	<string>AIzaSyBpxxxxxx</string>
	<key>GCM_SENDER_ID</key>
	<string>1008910072649</string>
	<key>PLIST_VERSION</key>
	<string>1</string>
	<key>BUNDLE_ID</key>
	<string>com.asouza.ppgFinder</string>
	<key>PROJECT_ID</key>
	<string>ppg-finder</string>
	<key>STORAGE_BUCKET</key>
	<string>ppg-finder.appspot.com</string>
	<key>IS_ADS_ENABLED</key>
	<true/>
	<key>IS_ANALYTICS_ENABLED</key>
	<false/>
	<key>IS_APPINVITE_ENABLED</key>
	<false/>
	<key>IS_GCM_ENABLED</key>
	<true/>
	<key>IS_SIGNIN_ENABLED</key>
	<true/>
	<key>GOOGLE_APP_ID</key>
	<string>1:1008910072649:ios:378d9ed0aa0868b9</string>
	<key>DATABASE_URL</key>
	<string>https://ppg-finder.firebaseio.com</string>
</dict>
</plist>
`

**Comment by EddyVerbruggen** [comment]
Ha.. next one: from that same folder, Info.plist is missing. It probably contains some app-specific configuration so I'll need that as well.

**Comment by d3mac123** [comment]
`<plist version="1.0">
  <dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleDisplayName</key>
    <string>${PRODUCT_NAME}</string>
    <key>CFBundleExecutable</key>
    <string>${EXECUTABLE_NAME}</string>
    <key>CFBundleIcons</key>
    <dict>
      <key>CFBundlePrimaryIcon</key>
      <dict>
        <key>CFBundleIconFiles</key>
        <array>
          <string>icon-40</string>
          <string>icon-60</string>
          <string>icon-72</string>
          <string>icon-76</string>
          <string>Icon-Small</string>
          <string>Icon-Small-50</string>
        </array>
        <key>UIPrerenderedIcon</key>
        <false/>
      </dict>
    </dict>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>${PRODUCT_NAME}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>2.6.0</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>CFBundleVersion</key>
    <string>2.6.0</string>
    <key>LSRequiresIPhoneOS</key>
    <true/>
    <key>UILaunchStoryboardName</key>
    <string>LaunchScreen</string>
    <key>UIRequiresFullScreen</key>
    <false/>
    <key>UIRequiredDeviceCapabilities</key>
    <array>
      <string>armv7</string>
    </array>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>PPG Finder needs location services to share your position with other pilots flying around you.</string>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>PPG Finder needs location services to share your position with other pilots flying around you.</string>
    <key>NSCalendarsUsageDescription</key>
    <string>This app may need, in the future, to access your calendar events</string>
    <key>ITSAppUsesNonExemptEncryption</key>
    <false/>
    <key>UISupportedInterfaceOrientations</key>
    <array>
      <string>UIInterfaceOrientationLandscapeLeft</string>
      <string>UIInterfaceOrientationLandscapeRight</string>
      <string>UIInterfaceOrientationPortrait</string>
    </array>
    <key>UISupportedInterfaceOrientations~ipad</key>
    <array>
      <string>UIInterfaceOrientationLandscapeLeft</string>
      <string>UIInterfaceOrientationLandscapeRight</string>
      <string>UIInterfaceOrientationPortrait</string>
      <string>UIInterfaceOrientationPortraitUpsideDown</string>
    </array>
    <key>CFBundleURLTypes</key>
    <array>
      <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLName</key>
        <string>org.nativescript.firebasedemo</string>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>org.nativescript.firebasedemo</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLName</key>
        <string>REVERSED_CLIENT_ID</string>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>com.googleusercontent.apps.1052836194035-l81fsjai1u40ocnqjcpnoebnnsltt03b</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLName</key>
        <string>org.nativescript.firebasedemo</string>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>fb1734263236864026</string>
        </array>
      </dict>
    </array>
    <key>FacebookAppID</key>
    <string>1734263236864026</string>
    <key>FacebookDisplayName</key>
    <string>PPG Finder</string>
    <key>LSApplicationQueriesSchemes</key>
    <array>
      <string>fbapi</string>
      <string>fb-messenger-api</string>
      <string>fbauth2</string>
      <string>fbshareextension</string>
    </array>
    <key>NSPhotoLibraryUsageDescription</key>
    <string>Picture to identify pilots</string>
    <key>UIBackgroundModes</key>
    <array>
      <string>remote-notification</string>
    </array>
    <key>NSAppTransportSecurity</key>
    <dict>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
      <key>NSAllowsArbitraryLoadsForMedia</key>
      <true/>
      <key>NSAllowsArbitraryLoadsInWebContent</key>
      <true/>
    </dict>
    <key>UIStatusBarStyle</key>
    <string>UIStatusBarStyleLightContent</string>
    <key>UIViewControllerBasedStatusBarAppearance</key>
    <false/>
  </dict>
</plist>`

**Comment by steinerjakob** [comment]
Hi @EddyVerbruggen  and @d3mac123 ,
I've had a simillar issue. After changing the map layer my app crashed after moving on the map. (Android)
Think it was depending on this error : ([#12432](https://github.com/mapbox/mapbox-gl-native/issues/12432)) is fixed in the mapbox version 6.4.0-alpha.1 - July 25, 2018
changed my plugin version from "4.3.0" to "4.4.0" now it works!
@d3mac123 update the plugin and try again, I think it's the same issue.
Greetings!

**Comment by EddyVerbruggen** [comment]
Yeah I just released that 4.4.0 version yesterday, and the Mapbox SDK was bumped. It may help as they fix a lot of bugs each version.

@d3mac123 if it doesn't help, then can you tell me how to login to the app? Getting 'internal error' when trying to register, so perhaps I can use an email address that works.

**Comment by d3mac123** [comment]
Eddy, you can try ze@ze.com<mailto:ze@ze.com>, password zezeze.

I'll update the sdk later today when I'm back at home. I'll keep you posted. Thanks again!

Alex Souza
On Oct 16, 2018, 11:47 AM -0400, Eddy Verbruggen <notifications@github.com>, wrote:

Yeah I just released that 4.4.0 version yesterday, and the Mapbox SDK was bumped. It may help as they fix a lot of bugs each version.

@d3mac123<https://github.com/d3mac123> if it doesn't help, then can you tell me how to login to the app? Getting 'internal error' when trying to register, so perhaps I can use an email address that works.

**Comment by d3mac123** [comment]
Mr. @EddyVerbruggen you are a GENIUS! Everything is working fine now. THANK YOU VERY MUCH!!!!
