### ISSUE TITLE
Desired Feature: Button on Programmatically Defined Map

### ISSUE THREAD

**Issue by BMwanza** [Yermo/nativescript-mapbox#272]
It'd be really cool to have a button that can show with your map when programatically defined to destroy it or perform some action. If you make your map full screen on ios for example, there's no way to get out of it unless you tap on a marker that leads you to another page

**Comment by steinerjakob** [comment]
Hi,
you can add buttons over the map by yourself?
![screenshot_1542299825](https://user-images.githubusercontent.com/23446667/48567532-85905a00-e8fd-11e8-8da5-7df9fb63dc86.png)

**Comment by BMwanza** [comment]
@stoanarrr I've been looking for a way to do this, How did you get it done?

**Comment by slushnys** [comment]
I believe it's just items within absolute layout.

**Comment by steinerjakob** [comment]
I'm using a gridlayout and all items do have the same row.

**Comment by BMwanza** [comment]
@stoanarrr If I programatically show the map though, it covers everything even if I define buttons in the xml myself

**Comment by steinerjakob** [comment]
@BMwanza I've created a little showcase here: [showcase](https://github.com/stoanarrr/nativescript-mapbox-showcase)
