### ISSUE TITLE
[!] Invalid `Podfile` file: The target `Pods-projectName` already has a platform set..

### ISSUE THREAD

**Issue by fabriek-huis** [Yermo/nativescript-mapbox#274]
When I install the `nativescript-mapbox` plugin then run (`tns run ios`) my project I get this error: 

[!] Invalid `Podfile` file: The target `Pods-projectName` already has a platform set..

**Comment by slushnys** [comment]
Have you tried running rm -rf platforms and building it again?

**Comment by fabriek-huis** [comment]
update the `Podfile` in platforms/ios folder. then `pod install` from that dir. 

```
# Begin Podfile - /Volumes/Drive/Work/project/projectName/dateapp/node_modules/nativescript-mapbox/platforms/ios/Podfile 
 pod 'Mapbox-iOS-SDK', '~> 4.4.1'
 
 # End Podfile 
```

or go into the node_modules folder and remove the `platform :ios, '9.0'` line in `Podfile` of the mapbox plugin.

**Comment by fabriek-huis** [comment]
fixed.

**Comment by AviBhagowantin** [comment]
I have the same issue. I tried what @sputn1k said but it doesn't work. Any other solution?

**Comment by miahdouble07** [comment]
You might have the same things twice on your podfile.

For example: 
  **
platform :ios, '9.0'
target :'ScreenColorChange' do
    use_frameworks!

    pod 'AWSCore', '~> 2.9.0'
end

platform :ios, '9.0'
target :'YOUR-APP-NAME' do
    use_frameworks!

    pod 'AWSAppSync', '~> 2.10.0'
end

**

Solution: Remove the duplicate code: 
**platform :ios, '9.0'
target :'YOUR-APP-NAME' do
    use_frameworks!**

and just add the last line to the previous code
**pod 'AWSAppSync', '~> 2.10.0'**

So it should look like this:
**platform :ios, '9.0'
target :'ScreenColorChange' do
    use_frameworks!

    pod 'AWSCore', '~> 2.9.0'
    pod 'AWSAppSync', '~> 2.10.0'
 # other pods

end
end**

**Comment by miahdouble07** [comment]
> I have the same issue. I tried what @sputn1k said but it doesn't work. Any other solution?

You might have the same things twice on your podfile.

For example:
platform :ios, '9.0'
target :'ScreenColorChange' do
use_frameworks!
pod 'AWSCore', '~> 2.9.0'

end

platform :ios, '9.0'
target :'YOUR-APP-NAME' do
use_frameworks!
pod 'AWSAppSync', '~> 2.10.0'
# other pods
end

Solution: Remove the duplicate code:
**platform :ios, '9.0'
target :'YOUR-APP-NAME' do
use_frameworks!**

and just add the last line to the previous code
pod 'AWSAppSync', '~> 2.10.0'

So it should look like this:
platform :ios, '9.0'
target :'ScreenColorChange' do
use_frameworks!

pod 'AWSCore', '~> 2.9.0'
pod 'AWSAppSync', '~> 2.10.0'
# other pods
end
end

**Comment by miahdouble07** [comment]
For example:
platform :ios, '9.0'
target :'ScreenColorChange' do
use_frameworks!
pod 'AWSCore', '~> 2.9.0'

end

platform :ios, '9.0'
target :'YOUR-APP-NAME' do
use_frameworks!
pod 'AWSAppSync', '~> 2.10.0'

end

Solution: Remove the duplicate code:
**platform :ios, '9.0'
target :'YOUR-APP-NAME' do
use_frameworks!**

and just add the last line to the previous code
**pod 'AWSAppSync', '~> 2.10.0'**

So it should look like this:
**platform :ios, '9.0'
target :'ScreenColorChange' do
use_frameworks!

pod 'AWSCore', '~> 2.9.0'
pod 'AWSAppSync', '~> 2.10.0'

end
end**

**Comment by codedjems** [comment]
You probably have the same code twice...

**For example:**

platform :ios, '9.0'
target :'ScreenColorChange' do
use_frameworks!
pod 'AWSCore', '~> 2.9.0'

end

platform :ios, '9.0'
target :'YOUR-APP-NAME' do
use_frameworks!
pod 'AWSAppSync', '~> 2.10.0'

end

**Solution:** Remove the duplicate code:
platform :ios, '9.0'
target :'YOUR-APP-NAME' do
use_frameworks!

**and just add the last line to the previous code**
pod 'AWSAppSync', '~> 2.10.0'

**So it should look like this:**
platform :ios, '9.0'
target :'YOUR-APP-NAME' do
use_frameworks!

pod 'AWSCore', '~> 2.9.0'
pod 'AWSAppSync', '~> 2.10.0'

end
end
