### ISSUE TITLE
Location not available.

### ISSUE THREAD

**Issue by Gcuencam** [Yermo/nativescript-mapbox#279]
Hi Eddy, 

If I use the getUserLocation method I get "location not available". I'm testing with the wifi and the gps active.

I thought about searching for your code and I got it to work if I change the "LocationEnginePriority" from HIGH_ACCURACY to BALANCED_POWER_ACCURACY. Is this normal?

Could we modify the code to parameterize the value of "LocationEnginePriority"?

Thanks.

**Comment by EddyVerbruggen** [comment]
Can you link to the line of code in the plugin where it says `HIGH_ACCURACY`? I'm a bit confused..

**Comment by Gcuencam** [comment]
I was wrong with the repository, the correct one was "nativescript-geolocation". Sorry.
