### ISSUE TITLE
Will the Mapbox Directions api work with Nativescript?

### ISSUE THREAD

**Issue by cherylbearden** [Yermo/nativescript-mapbox#28]
Is it possible to provide directions with a Mapbox map in a Nativescript app?  Thanks very much for the info.

**Comment by EddyVerbruggen** [comment]
Hi, I did a quick experiment on iOS and that should work indeed. Just need to add a few dependencies to the plugin and expose the API.

If anyone is interested to help out, here's the [iOS](https://www.mapbox.com/ios-sdk/#directions) and [Android](https://www.mapbox.com/android-sdk/examples/directions/) libs required.

**Comment by cherylbearden** [comment]
Hi. Thanks very much for checking this.

**Comment by rhanb** [comment]
Hi,

Do you know when this feature will be available?

Thanks :)

**Comment by rhanb** [comment]
I would love to contribute and try to implement this feature but I don't see any CONTRIBUTING.md file, could you provide one @EddyVerbruggen ?

Thanks :)

**Comment by EddyVerbruggen** [comment]
Hi,

Never needed to in the past.. what would you expect to be in it, do you have an example?

Thx!

**Comment by rhanb** [comment]
Here is a blog post from github about it @EddyVerbruggen :

https://github.com/blog/1184-contributing-guidelines

And an example: 

https://github.com/angular/angular/blob/master/CONTRIBUTING.md

**Comment by EddyVerbruggen** [comment]
Interesting. But is not having that holding you back in any way?

**Comment by rhanb** [comment]
It's just a standard to implement a contributing guideline on an open source project. 
It's to avoid waste of time for new collaborators when they try to figure out how the project is coded.

Effectively, I will try anyway if you don't plan to implement this feature :)

**Comment by EddyVerbruggen** [comment]
I'd like to have it added to the plugin, it's just not priority yet.
