### ISSUE TITLE
Question about supporting Mapbox Native Android 7.1.1/future plans?

### ISSUE THREAD

**Issue by Yermo** [Yermo/nativescript-mapbox#294]
First off, thank you very much for this plugin. Your work may have saved my project as I am frantically transitioning from a failed Cordova/mapbox-gl-js effort to your plugin. 

What I'm running into with this plugin however is that there are quite a few features missing that I need, namely things like:

- more styling options on polylines (dashed lines, etc)
- support for geojson sources akin to the way mapbox-gl-js works. 
- click handlers on everything.

So I thought maybe I could add these features myself and contribute to the project. I've crawled through the plugin code and I think I am starting to understand how things are put together. It doesn't seem too daunting. 

The pause/resume/navigate bug on Android is causing me some headaches. Implementing the destroy and recreate and redrawing the whole map is horrible UX but at least it doesn't crash. 

There was some mention about crash fixes in the changelogs upstream so I thought maybe they have addressed the pause/resume issue so I started looking at the current 7.1.1 version of the API.

Then I came across this:

[https://github.com/mapbox/mapbox-gl-native/wiki/Android-6.x-to-7.x-migration-guide](url)

It looks like they have made significant changes to the apis the NativeScript  plugin relies upon. For example:

> Starting in 7.0.0, the old concept of annotations is deprecated. Classes such as Polygon, Polyline, and Marker will not longer be maintained. This also means classes such as PolygonOptions and PolylineOptions should not be used. Lastly, this also means that methods such as addPolygon(), addPolyline(), or addMarker() should not be used.

If I understand what I am reading, it seems like they haven't yet migrated all the plugins the nativescript plugins relies upon to V7. 

For my purposes, my thought was that it should be possible to implement a NativeScript API that was a subset of the mapbox-gl-js API. This would make it much easier to share code between native apps and web apps, at least in theory. (I'm using Nativescript + Angular). 

So before I start spending a bunch of time and making a mess of things, I thought I'd ask what, if any, are the future plans for the NativeScript plugin? 

Do you intend to keep this plugin in sync with the upstream Mapbox changes? (i.e. do I work with the older SDK version as it is now and wait for 7+ support and update later or do I wait for 7+ support first or maybe help with the 7+ integration?)

Do you have a vision for how you want the plugin to change moving forward?

**Comment by Yermo** [comment]
https://github.com/Yermo/nativescript-mapbox

**Comment by EddyVerbruggen** [comment]
Thanks Yermo, let's move discussions to #300.
