### ISSUE TITLE
Can I display labels(text) on the map?

### ISSUE THREAD

**Issue by sanghyun5958** [Yermo/nativescript-mapbox#298]
I'm looking for the way to display the label on the map. there is any way to display?

Thank you

I used to title on the website like below.
`   
res.forEach(anchor => {
        anchorageList.push({
          type: 'Feature', properties: {'description': [{name: anchor.code}], 'title': anchor.code, 'color': '#fff'},
          geometry: {'type': 'Polygon', 'coordinates': [[...anchor.positions]]}
        });
      });
      this.anchoragePolygon = {type: 'FeatureCollection', features: anchorageList};`

**Comment by sanghyun5958** [comment]
I'm looking for the way to display on the polygon...

**Comment by EddyVerbruggen** [comment]
Can you please look at the native Mapbox SDK docs and see if it can be done, and if so post your findings here?

**Comment by blipk** [comment]
Using z-index and an absolutelayout I have been able to put anything on top of the map

**Comment by EddyVerbruggen** [comment]
Alternatively, you can overlay anything by stacking UI widgets using a `<GridLayout>` by assigning multiple widgets to the same `row` and `col` indices.
