### ISSUE TITLE
Weird post-build java error log output.

### ISSUE THREAD

**Issue by ghost** [Yermo/nativescript-mapbox#306]
I've been using the plugin almost perfectly, besides some minor mistakes deleting markers, however I suspect that's because some asynchronous problems in another library (zone.js), but when running "tns build android" and "tns run android" these messages are logged:

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Skip com.mapbox.mapboxsdk.lint.KeepDetector
        Error: java.lang.NullPointerException
Skip timber.lint.WrongTimberUsageDetector
        Error: java.lang.NullPointerException
Project successfully built.

Althought the apk is built successfully and the map seems to work ok in the app. 
For legal reasons I can not share the repo but these are the details for dependencies and environment:
{
    "nativescript": {
        "id": "app.company.myapp",
        "tns-ios": {
            "version": "5.2.0"
        },
        "tns-android": {
            "version": "5.2.1"
        }
    },
    "description": "NativeScript Application",
    "license": "SEE LICENSE IN <your-license-filename>",
    "repository": "<fill-your-repository-here>",
    "dependencies": {
        "@angular/animations": "~7.1.0",
        "@angular/common": "~7.1.0",
        "@angular/compiler": "^7.2.8",
        "@angular/core": "~7.1.0",
        "@angular/forms": "~7.1.0",
        "@angular/http": "~7.1.0",
        "@angular/platform-browser": "~7.1.0",
        "@angular/platform-browser-dynamic": "~7.1.0",
        "@angular/router": "~7.1.0",
        "nativescript-angular": "~7.1.0",
        "nativescript-geolocation": "^4.4.1",
        "nativescript-mapbox": "^4.4.1",
        "nativescript-secure-storage": "^2.3.0",
        "nativescript-theme-core": "~1.0.4",
        "reflect-metadata": "~0.1.10",
        "rxjs": "~6.3.0",
        "tns-core-modules": "^5.2.2",
        "typescript": "^3.1.1",
        "zone.js": "~0.8.18"
    },
    "devDependencies": {
        "@angular/cli": "^7.2.3",
        "@angular/compiler-cli": "^7.2.7",
        "@nativescript/schematics": "^0.5.0",
        "@ngtools/webpack": "~7.1.0",
        "nativescript-dev-typescript": "^0.7.9",
        "nativescript-dev-webpack": "~0.19.0"
    },
    "readme": "NativeScript Application"
}
Node version 10.15.0, Ubuntu 18.04.2 LTS, java version "1.8.0_181", javac 1.8.0_181, Android API 28
Btw, thank you, the plugin and the other ones are awesome! 😄😄

**Comment by EddyVerbruggen** [comment]
Thanks!

I have the same message. Same on a few other plugins. Nothing to worry about. Can’t get rid of them unfortunately.
