### ISSUE TITLE
Nativescript-vue declaring a map in code.

### ISSUE THREAD

**Issue by Spacarar** [Yermo/nativescript-mapbox#309]
Currently is there any way to declare the nativescript-mapbox map via code using the nativescript-vue framework?

I have followed this tutorial https://www.nativescript.org/blog/include-feature-rich-maps-in-a-nativescript-vue-app-with-mapbox to get my project up and running but this only explains the xml implementation.

I know you have the available options/methods of the xml map written below the table but perhaps something near the top of the documentation about how the XML implementation is incomplete would have saved me a lot of time.

When trying to implement a map via code I have tried any of the following to import nativescript-mapbox in order to declare a map programmatically, all of which have failed.

At the top of the script section of the component I have tried using
```
import mapbox from 'nativescript-mapbox'
import * as mapbox from 'nativescript-mapbox'
import {Mapbox} from 'nativescript-mapbox
```

I have also tried including these names in the data section
```
mapbox: require('nativescript-mapbox'),
mapbox: require('nativescript-mapbox').Mapbox
```

please note each line is a seperate attempt at importing this. all of which result in `NativeScript encountered a fatal error: TypeError: nativescript_mapbox__WEBPACK_IMPORTED_MODULE_2__["listOfflineRegions"] is not a function` when trying to use any of the methods listed in the documentation (listOfflineRegions shown, but does the same with any of the functions). however the object is present so something is indeed being imported it just seems incomplete or not aligned with the documentation..

**Comment by Codex-** [comment]
There were some examples of it here: https://github.com/EddyVerbruggen/nativescript-mapbox/issues/214

**Comment by lochstar** [comment]
I've got this working with NativeScripe-Vue.

```
// import
import { Mapbox } from 'nativescript-mapbox'

// use in component
const map = new Mapbox()
map.show({...options})
```

Although, I use the XML implementation, it allows for more control over the position and placement of the map. You should be able to do everything you need once you have the map reference that you get via `@mapReady`.

**Comment by Spacarar** [comment]
So right now is no way to do things like the offline maps while using a map that can be displayed with reference to the page? (eg. with style and action bar etc.)

**Comment by lochstar** [comment]
Offline maps should work fine either way, @Spacarar.

**Comment by Spacarar** [comment]
While I do see that offline maps can be downloaded/listed, if creating a `new Mapbox.Mapbox()` however, the `MapboxView` which can be styled as discussed does not have this capability. From what I can tell downloading a region using the `Mapbox` class will not let the `MapboxView` class access this information.

**Comment by Spacarar** [comment]
My goal is to download offline regions to be viewed later.

- In the xml of the code I have a map that is perfectly functional.
- This could be recreated by creating a new `MapboxView()` instance and appending it to the body. - To download an offline region you must use the `Mapbox()` class not the `MapboxView()` class.
- So I have a `Mapbox` instance that has downloaded the offline region I want to view.
- I can list the offline region, and even delete it
- the offline region is not displayed on the map when in airplane mode.

as a simplified example: when running this code, I see the offline region listed but it will display nothing on the map if running offline

```
<template>
	<page>
		<ActionBar title="Example mapbox" />
		<GridLayout row="*" columns="*">
			<Mapbox :accessToken="accessToken" :mapStyle="mapStyle" col="0" row="0" @mapReady="loadMap" />
		</GridLayout>
	</page>
</template>

<script>
import * as Mapbox from 'nativescript-mapbox'
export default {
	data() {
		accessToken: 'my access token',
		mapStyle: 'the style url',
		map: null,
		mapbox: null
	},
	methods: {
		loadMap(args) {
			this.map = args.map
		}
	}
	created() {
		this.mapbox = new Mapbox.Mapbox()
	},
	mounted() {
		// initializing mapbox seemed to take a small amount of time
		// this was put in mounted to give the mapbox a second
		// if this does not work, you may need to use this.$nextTick( () = > {}) or setTimeout( () => {}, 100)
		this.mapbox.listOfflineRegions({accessToken: this.accessToken}).then(response => {
			console.log(response)
		})
	}
}
</script>
```

**Comment by lochstar** [comment]
I've just tested this out in my own project.

Firstly, you can put the `listOfflineRegions` call in your `loadMap` function, so you don't run in to the timing issue.

Secondly, you can call `listOfflineRegions` and `downloadOfflineRegion` using `args.map.mapbox.listOfflineRegions` and `args.map.mapbox.downloadOfflineRegion`.

To test this, I downloaded the current viewport, unloaded the mapview, turned on aeroplane mode and reloaded the mapview. The map correctly shows until I zoom in/out of the downloaded viewport.

**Comment by Spacarar** [comment]
this appears to work. thank you for your patience and clarification. perhaps some of this could be clarified a bit further in the documentation about some of the object structure. I had no idea that args.map.mapbox was even an option. closing the issue.
