### ISSUE TITLE
Constant Crashes

### ISSUE THREAD

**Issue by blipk** [Yermo/nativescript-mapbox#313]
Map consistently crashes whenever the screen is turned on/off or attempting to change a view with a tabview or a router or leaving the app window then returning to it. Have stripped down the code to nothing but the map and the problem persists. 

I don't get an error or anything in the CLI output, any suggestions on how to debug this?

**Comment by blipk** [comment]
Using this code:

```
import Vue from 'nativescript-vue';
import App from './components/App.vue';

import VueDevtools from 'nativescript-vue-devtools';
if(TNS_ENV !== 'production') Vue.use(VueDevtools);
Vue.config.silent = (TNS_ENV === 'production');

Vue.registerElement("Mapbox", () => require("nativescript-mapbox").MapboxView);

const myApp = new Vue({
  render: h => h('frame', [h(App)])
}).$start();
```
```
<template>
    <Page>        
        <StackLayout>
                <Mapbox 
                    :accessToken="MAPBOX_APIKEY"
                    >
                </Mapbox>
        </StackLayout>
    </Page>
</template>

<script>
    import Vue from "nativescript-vue";

    export default {
        data() {
            return {
                MAPBOX_APIKEY: "my__token",
            };
        },
    };
</script>
```

**Comment by blipk** [comment]
Okay after using logcat I got the following
```
04-26 16:35:36.258 11093 11093 F DEBUG   :     #32 pc 00ad43c6  /system/framework/boot-framework.vdex (android.opengl.GLSurfaceView$GLThread.guardedRun+900)
```

Seems it's related to this issue: https://github.com/EddyVerbruggen/nativescript-mapbox/issues/275
The flutter plugin is having a similar issue and they suggest using TextureView instead of GLSurfaceView: https://github.com/mapbox/flutter-mapbox-gl/issues/74

In the mean time I will try downgrading to an older version of this plugin as @EddyVerbruggen suggested on the other issues, perhaps the issue they are having with flutter will shed some light on a resolution for this.

Thanks.

**Comment by blipk** [comment]
removing latest version and installing nativescript-mapbox@4.3.1 seems to have fixed the issue

**Comment by Codex-** [comment]
Was able to reproduce this, will investigate and make a PR if I get anywhere with it. Thanks for the lead with that issue link.

**Comment by Codex-** [comment]
I forgot to ask, do you know if this happens on iOS too? I have no easy access to iOS environments to test with but can look into that side of it too and find a test environment somewhere.

**Comment by Spacarar** [comment]
I feel stuck between a rock and a hard place on this issue. Using version 4.4.1 crashes android for me on resume events. but using version 4.3.1 crashes IOS for me...
The android issue seems to be https://github.com/EddyVerbruggen/nativescript-mapbox/issues/271

and the ios issue seems to be https://github.com/EddyVerbruggen/nativescript-mapbox/issues/265

**Comment by Tyler-V** [comment]
Can we not upgrade both Android/iOS to the latest SDK? @EddyVerbruggen

**Comment by Codex-** [comment]
@Tyler-V It's not a trivial task, I've spent over a day on it already, basically there are many API changes between versions and you basically need to step up versions all the way to current while ensuring the currently supported and exposed NS-MB API's are cross platform compatible.

**Comment by YegorMedvedev** [comment]
Do we have any workaround for that issue, apart downgrade to 4.3.1? @EddyVerbruggen 

Unfortunately, I can't switch to 4.3.1 cos it doesn't support user tracking (Android) and I can't use 4.4.0 (4.4.1), cos it crashes an app on every route change.

**Comment by VaidasDatenis** [comment]
Hey guys. Same problem here.. Still no updates with angular nativescript-mapbox@4.4.1 ?

**Comment by dmytro-gokun** [comment]
@VaidasDatenis We ended up creating our own version of the wrapper. This project is dead.

**Comment by VaidasDatenis** [comment]
> @VaidasDatenis We ended up creating our own version of the wrapper. This project is dead.

Hi @dmytro-gokun . Could you please explain in more detail? I'm new in this subject and didn't realy understood..

**Comment by dmytro-gokun** [comment]
@VaidasDatenis Well, this project is a thin wrapper around Mapbox iOS/Android SDKs. But, unfortunately, it has some very nasty bugs which nobody is able/willing to fix for really long time now. There is some work happening here: https://github.com/EddyVerbruggen/nativescript-mapbox/pull/331 for the last 6 months. But nobody really knows when that is ready.

**Comment by Yermo** [comment]
@dmytro-gokun @VaidasDatenis You can check my fork. I'm going to be taking this project over. I have a working fork for NS6 and the latest Android/iOS SDKs (well, as of a couple months ago). It addresses most of the bugs. I've just been slammed with other work so haven't had a chance to focus on it for a few months.

**Comment by VaidasDatenis** [comment]
Thank you guys, wish you the best. How could i participate in these kind of things? My NativeScript skills are low (I'm new) but it would be interesting to try :)

**Comment by Yermo** [comment]
@VaidasDatenis check out my fork. It will be merged with this project as soon as I have some time (which sadly I've been saying for a while now.)
