### ISSUE TITLE
animate: true on IOS simulator doesn't work

### ISSUE THREAD

**Issue by chaeron** [Yermo/nativescript-mapbox#315]

**Comment by chaeron** [comment]
I had animate: true for programmatic viewport and zoom changes, but on the IOS simulator nothing happens.

There is no animation, but also the actual call doesn't take effect....that is, the new viewport or zoom is ignored if animate: true is set.

Strange.

**Comment by Spacarar** [comment]
could you provide a code sample that is "broken" for you? I'm using this plugin and animations work fine on both simulator and real ios devices for me. I have found that animations will cancel one another, e.g. putting two animated movements one after another will cancel the first:
```
this.map.setZoomLevel({level: 8, animated: true})
this.map.setCenter({lng: -104.964777, lat: 39.740010, animated: true})
```
does not zoom to the correct level.

**Comment by chaeron** [comment]
Ah!  I was using multiple calls with animation.....the cancellation was what was causing my issue! Thanks for the heads up on the Spacarar!

Be nice if the documentation noted that as a constraint at some point.

I'm going to close this issue.
