### ISSUE TITLE
Is there any plans to release a new version?

### ISSUE THREAD

**Issue by dmytro-gokun** [Yermo/nativescript-mapbox#319]
@EddyVerbruggen This repository contains some useful additions since the last release. Do you plan to release a new version any time soon? If you need help with fixing some known issues before you can do that - please let us know, i think there are some ppl willing to help.

**Comment by EddyVerbruggen** [comment]
Any help is always welcome. And of course I’m happy to release a new version, but only if it’s at least as stable as the current one. So I guess testing the github version would be a good first step for anyone looking to help. Cheers!

**Comment by dmytro-gokun** [comment]
@EddyVerbruggen Okay, we are willing to test. The only problem is.. how do we reference the latest github version from our app? Is it published somewhere on a "beta channel" or forking it and publishing to a private registry is the only way to go?

**Comment by EddyVerbruggen** [comment]
If you clone the repo you can run the pack.sh script from the publish folder which will create the plugin package.

I’m abroad currently so can’t help more.
