### ISSUE TITLE
Map tap event

### ISSUE THREAD

**Issue by ishaqueahmed-mev** [Yermo/nativescript-mapbox#321]
Hello,

I am not able to get the tap event on mapbox element on android, please help...

**Comment by Spacarar** [comment]
could you provide an example of your code, a working sample, something more descriptive to go on. Version numbers would be useful.

**Comment by Izrab** [comment]
Can you try to put a onTap event element to the parent layout in which the mapbox view resides?

**Comment by ishaqueahmed-mev** [comment]
Hello,

I tried tapping on parent layout also, but it wasn't working there too. So I just put the setOnMapClickListener() event inside the map initialization method, and it worked well then.

Thanks everyone for the suggestions anyway...
