### ISSUE TITLE
Is there a way to use a raster source ?

### ISSUE THREAD

**Issue by QuentinLB** [Yermo/nativescript-mapbox#324]
Hello,

I tried to no avail to plug a map to a local tileserver-gl instance serving custom raster tiles (tileJson file). After digging in the source code of nativscript-mapbox plugin & [mapbox-gl-native 6.5.0](https://github.com/mapbox/mapbox-gl-native/tree/6.5.0) I did found an [`addSource` method](https://github.com/EddyVerbruggen/nativescript-mapbox/blob/716086bd1077757a8651cc48900edc9d84606520/src/mapbox.android.ts#L1542) but it only support vector sources. 

From here I see 3 possible solution for my problem : 

- I didn't dig enough and there's a way to use raster maps & tilejson files, can you point me to right direction ?
- Somehow turn my aerial views into vectors
- Fork this plugin to add the capability to handle raster source and maybe submit a PR but it would only be on android as I don't have any knowledge & mac to test on iOS.

Please, tell me if you need more information or if I need to rephrase my issue.

Thanks

**Comment by tomo54321** [comment]
It is already possible to use raster tiles with this plugin, take a look at the [demo app](https://github.com/EddyVerbruggen/nativescript-mapbox/blob/master/demo/) as it uses OpenStreetMap raster tiles - also take a look at the [MapBox style JSON spec](https://docs.mapbox.com/mapbox-gl-js/style-spec/) for more information.

To use them, first off create a may style JSON file. [An example can be found in the demo app here](https://github.com/EddyVerbruggen/nativescript-mapbox/blob/master/demo/app/OSM-map-style.json)

Then with the `onMapReady` event you can set the map style to the style we defined in the JSON file, [an example of this is in the demo app also here](https://github.com/EddyVerbruggen/nativescript-mapbox/blob/master/demo/app/main-page.ts#L38)

Hope this helps! :)

**Comment by QuentinLB** [comment]
Thank you for your reply, indeed I missed this example and didn't thought about local json file. I tried to replicate the exemple : 

MyActivity.vue :
```javascript
<Mapbox
        accessToken="noToken"
        mapStyle="~/style.json"
        hideCompass="true"
        hideAttribution="true"
        hideLogo="true"
        @mapReady="onMapReady($event)"
        ref="map">
</Mapbox>
```
After a build I can see my file `style.json` next to my bundle in `/platforms/android/app/src/main/assets/app/` but when I launch my app Mapbox can't find the `style.json` file nothing happen and there is this error in logcat : 
`E/Mbgl: {MyApp}[Setup]: loading style failed: Could not read asset`

Am I missing something ?

**Comment by tomo54321** [comment]
Hi,
I think that this may be a permissions issue, unfortunately I'm not experienced in using Vue however I have attempted to have a play around. What leads me to believe that this is a permissions issue is when the JSON file is loaded in locally, the app fails however if you load the JSON file in from a remote server it works fine, give it a try using the raw JSON file from the example ([here](https://raw.githubusercontent.com/EddyVerbruggen/nativescript-mapbox/master/demo/app/OSM-map-style.json)). However when I have tried this using NativeScript (Javascript) and had no such issues and loaded in just fine locally.

I've searched through the issues and it appears that other's are having the same issue, take a look here #286

**Comment by QuentinLB** [comment]
Thanks everyone for your replies, after spending a lot of time trying to make this work my team and I decided to give up on nativescript-mapbox & nativescript altogether. Apart from the issues with raster sources we need feature from newest version of the SDK that are not present here and we don't have enough bandwidth to do it ourselves and submit a PR.
