### ISSUE TITLE
App crashes when navigating in nativescript RadSideDrawer template

### ISSUE THREAD

**Issue by vahidvdn** [Yermo/nativescript-mapbox#332]
When I go to another menu in nativescript RadSideDrawer template (not sure if this happens in other templates) it crashes. For the demonstration, please create a new angular RadSideDrawer template and add the mapbox plugin. Also, I made a video for  the demonstration:

[crash-mapbox.zip](https://github.com/EddyVerbruggen/nativescript-mapbox/files/3764044/crash-mapbox.zip)

**Comment by Yermo** [comment]
This is a known issue and not a bug in the mapbox plugin but a problem in Nativescript tns-core-modules having to do with setting a background in the RadSideDrawer when markingMode "none" is used.

https://github.com/NativeScript/NativeScript/issues/7867

You can also check out my fork of the plugin which is being reviewed for merging into this repositiory:

https://github.com/Yermo/nativescript-mapbox

For a workaround see this file:

https://github.com/Yermo/nativescript-mapbox/blob/master/demo-angular/README.md#the-long-standing-android-navigation-crash--temporary-workaround-for-tns-core-modules-6112

**Comment by vahidvdn** [comment]
Hi @Yermo . Thanks for quick reply. Also this happens in nativescript tabview template. How can I install your fork? It seems it's not published in npm.

**Comment by Yermo** [comment]
@vahidvdn It's not published to npm yet. I've sent a pull request to @EddyVerbruggen but it's a big change with some breaking API changes and a few problems yet to be sorted out. 

There are instructions on how to build my fork. You'll need to clone the repository using git and build the plugin. See the README.

**Comment by vahidvdn** [comment]
@Yermo Thanks. And did you changed tns-core-modules codes? It so, then if I update nativescript the crash will occur again. Am I right?

**Comment by Yermo** [comment]
Yes. If you apply the patch I describe then you will have to apply it again every time you upgrade tns-core-modules. Hopefully, the Nativescript folks will fix that bug soon so that we don't have to do this.

**Comment by vahidvdn** [comment]
@Yermo Yes. But that bug differs from the plugin bug. The plugin bug happens even in the tab template. Unfortunately, I couldn't be able to run your fork. I get some weird errors. For now, I just handle it in my side, by hiding the map view before navigating away. Hopefully, waiting for your pull request to get merged. (otherwise, it would be really helpful to publish it in npm by you)

Btw, thanks for your efforts.

**Comment by noctain** [comment]
Hi @vahidvdn , could you share the code to hide mapview before navigating away? I'm experiencing the same issue.

**Comment by vahidvdn** [comment]
@noctain Here you are:

app.component.ts

```TS
onNavItemTap(navItemRoute: string): void {
    this.appService.setMapVisiblity(false);

    if (this._activatedUrl == "/home") {
        setTimeout(()=>{
            this.routerExtensions.navigate([navItemRoute], {
                transition: {
                    name: "fade"
                }
            });
        }, 500);
    }

    else {
        this.routerExtensions.navigate([navItemRoute], {
            transition: {
                name: "fade"
            }
        });
    }

    const sideDrawer = <RadSideDrawer>app.getRootView();
    sideDrawer.closeDrawer();
}
```

app.service.ts

```TS
import { Injectable, Inject } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})

export class AppService {

	private dataSource = new BehaviorSubject(true);
  	data = this.dataSource.asObservable();

	constructor() {}

	setMapVisiblity( flag ) {
		this.dataSource.next(flag);
	}


}
```

home.component.ts

```TS
ngOnInit(): void {
    this.appService.data.subscribe(data => {
        if ( data == false) {
            this.showMap = false;
        }
    })
}
```

home.component.html

```XML
<ContentView *ngIf="showMap" height="100%" width="100%">
    <Mapbox
    ...
```
