### ISSUE TITLE
Custom Styles In Maps

### ISSUE THREAD

**Issue by jacobocantillo** [Yermo/nativescript-mapbox#34]
Hi.

MapBox SDK allows you to set styles for maps. In your excellent implementation, for iOs and Android, styles are established through an enum with default styles.

The SDK also allows you to define your own styles, created with MapBox Studio, setting the style to map through the **styleUrl** function.

It would be quite useful this capability in the library.

Thank you!

**Comment by ahalls** [comment]
Looks like this is addressed in this PR:
https://github.com/EddyVerbruggen/nativescript-mapbox/pull/38

**Comment by EddyVerbruggen** [comment]
That PR was just merged and available in 2.1.0, so please give it a try!
