### ISSUE TITLE
Install instructions for 5.0

### ISSUE THREAD

**Issue by keerl** [Yermo/nativescript-mapbox#357]
Hi @Yermo,

Just installed the newly tagged version, seems to be working great! I was just looking at the readme and noticed that the install instructions are `npm install --save nativescript-mapbox` versus the normal `tns plugin install nativescript-mapbox`. Is there a reason for this? I used `tns plugin install nativescript-mapbox` and it seems to work fine. Just wondering if it would be more clear to use the standard plugin install method. Thanks!

**Comment by Yermo** [comment]
You're correct. Old habit of mine. Both seem to work. I have updated the README.
