### ISSUE TITLE
Add point separately

### ISSUE THREAD

**Issue by Mflm** [Yermo/nativescript-mapbox#363]
Hi,

It's possible to make the points ant later make the polyline?

I have this Json file:
`[{"id":"47","lang":"9.518660760970183","lat":"42.428797092769436"},{"id":"48","lang":"9.520034051985808","lat":"42.42947813418155"},{"id":"49","lang":"9.521214223952361","lat":"42.43030170926044"},{"id":"50","lang":"9.522179819197722","lat":"42.43098273432493"},{"id":"51","lang":"9.523381448836394","lat":"42.43095105890462"},{"id":"52","lang":"9.522957801818848","lat":"42.43150252231192"}]`

I need to send it to the map

`mapView.map.addPolyline({
      color: '#336699', // Set the color of the line (default black)
      width: 7, // Set the width of the line (default 5)
      opacity: 0.6, //Transparency / alpha, ranging 0-1. Default fully opaque (1).
      points:  points
  });`

Or can I send an array to method?

Thanks

**Comment by Yermo** [comment]
Convert your array of points into a GeoJSON line string and use addLayer().

**Comment by Mflm** [comment]
Thanks 

I tried but it doesn't work, so I did manual tests but the lines don't appear

Example:
`mapView = args;
mapView.map.setCenter(
      {
        lng: -122.48369693756104, 
        lat: 37.83381888486939, 
        animated: false 
      }
  )

mapView.map.addSource('route', {
'type': 'geojson',
'data': {
'type': 'Feature',
'properties': {},
'geometry': {
'type': 'LineString',
'coordinates': [
[-122.48369693756104, 37.83381888486939],
[-122.48348236083984, 37.83317489144141],
[-122.48339653015138, 37.83270036637107],
[-122.48356819152832, 37.832056363179625],
[-122.48404026031496, 37.83114119107971],
[-122.48404026031496, 37.83049717427869],
[-122.48348236083984, 37.829920943955045],
[-122.48356819152832, 37.82954808664175],
[-122.48507022857666, 37.82944639795659],
[-122.48610019683838, 37.82880236636284],
[-122.48695850372314, 37.82931081282506],
[-122.48700141906738, 37.83080223556934],
[-122.48751640319824, 37.83168351665737],
[-122.48803138732912, 37.832158048267786],
[-122.48888969421387, 37.83297152392784],
[-122.48987674713133, 37.83263257682617],
[-122.49043464660643, 37.832937629287755],
[-122.49125003814696, 37.832429207817725],
[-122.49163627624512, 37.832564787218985],
[-122.49223709106445, 37.83337825839438],
[-122.49378204345702, 37.83368330777276]
]
}
}
});
mapView.map.addLayer({
'id': 'route',
'type': 'line',
'source': 'route',
'layout': {
'line-join': 'round',
'line-cap': 'round'
},
'paint': {
'line-color': '#6b4ce6',
'line-width': 11
}
});`

Url : https://docs.mapbox.com/mapbox-gl-js/example/geojson-line/

**Comment by Yermo** [comment]
oh right. There's a bug in addSource I have to fix. 

You can include the source in your layer;

source: {
  "type" : "geojson",
  "data": {
    "type": "Feature"

etc

The addSource issue will be fixed in the next release. I'm hoping to get to that this week.

**Comment by Mflm** [comment]
Then I will wait, because it still does not work.

Thanks
