### ISSUE TITLE
clusters

### ISSUE THREAD

**Issue by neversaynever44** [Yermo/nativescript-mapbox#369]
how to change default marker icon to cluster background with circle count ?
https://prnt.sc/t25fex

**Comment by Yermo** [comment]
It's not implemented yet.

**Comment by Janskiproducer** [comment]
Hello - I need this too, the single reason I switched from Google Maps. I see that @EddyVerbruggen has this feature in his demo:
mapbox.addGeoJsonClustered(
        {
          name: "earthquakes",
          data: "https://www.mapbox.com/mapbox-gl-js/assets/earthquakes.geojson",
          clusterMaxZoom: 15,
          clusterRadius: 20
          // clusters: [
          //   {}
          // ]
        }
    ).then(
        function() {
          dialogs.alert({
            title: "GeoJSON added",
            message: "Moving to the USA as that's where the GeoJson data is drawn",
            okButtonText: "OK"
          }).then(function() {
            mapbox.setViewport(
                {
                  bounds: {
                    north: 52.9,
                    east: -62.2,
                    south: 22.1,
                    west: -128.2
                  },
                  zoomLevel: 3
                }
            )
          });
        },
        function(error) {
          console.log("mapbox doAddAndClusterGeoJSON error: " + error);
        }
    );
  };

but it won't work when I try to implement it. Was it removed?

**Comment by Yermo** [comment]
The API is still there. Is it not working in the demo? What error messages are you seeing? I'm going to be working on the plugin full time for a while starting in a few weeks.

**Comment by Janskiproducer** [comment]
Hmm no I get a "undefined is not a function (near '...map.addGeoJsonClustered...'" error. Very nice that you'll be working on the plugin! It's really the cornerstone of a new app for a startup company I'm working with, and these clusters would be extremely nice to get working :)

**Comment by Yermo** [comment]
You're getting this error when running the demo? 

I'm building my own startup and clusters are a central part of it as well, so I will get them working but it's going to be a few weeks yet. I've got to finish up my new map editor first which is getting very close to done.

**Comment by Janskiproducer** [comment]
The demo wouldn't run at all - so I tried to use that one function. Nice and good luck with your startup!

**Comment by Yermo** [comment]
The fact that the demo doesnt' run points to other problems. 

The demo works for me on both iOS and Android.

What platform are you running on?

**Comment by Janskiproducer** [comment]
Hello! 
I'm just wondering if there are any developments on this?
