### ISSUE TITLE
Cannot Place UI elements over viewport

### ISSUE THREAD

**Issue by xerotolerant** [Yermo/nativescript-mapbox#37]
I can't figure out how to draw some Ui elements over the map. 
I was using google maps and cordova previously and I could "draw" over a map since it was drawn within a div container.

In this case I don't know which element, if any I can apply some css to in order to draw over the map. Is it even possible to do so?

**Comment by bradmartin** [comment]
Using a `GridLayout` you can place elements on top of the MapBox now if you declare it in your markup. 

If you need an idea how to 'float' a view component on top of another check the FAB plugin README here using a `GridLayout` https://github.com/bradmartin/nativescript-floatingactionbutton#xml
