### ISSUE TITLE
Doesn't work with NS7

### ISSUE THREAD

**Issue by autaut03** [Yermo/nativescript-mapbox#387]
Hey. As far as I'm aware, this needs to be recompiled to target es2017 to work with NS7 correctly. Currently, when trying to use it with NS7, it throws this error while trying to instantiate the map component:

```log
JS: ERROR Error: Uncaught (in promise): TypeError: Class constructor ContentView cannot be invoked without 'new'
JS: TypeError: Class constructor ContentView cannot be invoked without 'new'
JS:     at MapboxViewCommonBase [as constructor] (file: node_modules\nativescript-mapbox\mapbox.common.js:73:0)
JS:     at MapboxViewBase [as constructor] (file: node_modules\nativescript-mapbox\mapbox.common.js:281:0)
JS:     at new MapboxView (file: node_modules\nativescript-mapbox\mapbox.android.js:20:0)
JS:     at ViewUtil.createView (file: node_modules\@nativescript\angular\__ivy_ngcc__\fesm2015\nativescript-angular.js:2550:0)
```

**Comment by Yermo** [comment]
Ok. Thanks for letting me know. I'm behind schedule on my end and had hoped to loop back around to the plugin before now. I haven't upgraded to NS7 yet. I don't have an ETA when I'll get back to it but it shouldn't be too much longer now. If you want to take a crack at it and create a pull request I can take the time out to review it. Otherwise, hopefully in the next few weeks I can get to it. I apologize for the delay.

**Comment by autaut03** [comment]
No worries. I delay my (much smaller) OS projects too. I'll try my best with a PR.

**Comment by trevortos** [comment]
Having the same issue here, non angular / vue app.

**Comment by codeturn** [comment]
Me too. Vue app. Please make update.

**Comment by jeffersondossantosaguiar** [comment]
Me too. I've the same problem

**Comment by madmas** [comment]
@trevortos @codeturn @jeffersondossantosaguiar here is a PR open for this: https://github.com/Yermo/nativescript-mapbox/pull/388
I you need this, too, maybe you can check it out and validate the changes work as expected? I think that will make it a lot easier for @Yermo to merge it when he get to it ;-) 
I'm planning to do so and want to validate the PR ASAP

**Comment by farfromrefug** [comment]
I am in the need on that plugin on N 7.
I will create a fork under `@nativescript-community`. I really hope that is ok. I tried to contact @Yermo but now answer, i hope it is ok with you. 
If we all agree we can start maintaining it there (which makes more sense), and people are welcome to join @nativescript-community to contribute more and in an easier way

**Comment by Yermo** [comment]
My apologies that I have been MIA. I had hoped to get back to working on the plugin much sooner but life keeps conspiring to get in the way. If you need to fork it, please go ahead. Of course it's ok.

**Comment by farfromrefug** [comment]
@Yermo done and released a "first version". already quite a lot of changes
Thanks

**Comment by farfromrefug** [comment]
the mapbox plugin is now an will remain maintained at @nativescript-community  https://github.com/nativescript-community/ui-mapbox. We released the new plugin for N7 with a lot of fixes  https://www.npmjs.com/package/@nativescript-community/ui-mapbox
