### ISSUE TITLE
Unable to start activity ComponentInfo:Failed to find module 'Crypto'

### ISSUE THREAD

**Issue by Arman8852** [Yermo/nativescript-mapbox#39]
I have installed a  request node package via npm.The dependency have been updated in package.json.But when I injected the package like this

var request=require('request');

I am getting the above error.What I can do?
![module](https://cloud.githubusercontent.com/assets/19362205/19223103/2ded70c4-8e89-11e6-87a7-c66097d93e4b.PNG)

**Comment by EddyVerbruggen** [comment]
I don't see how this is related to this plugin.
