### ISSUE TITLE
Can't find variable: MGLOfflineStorage

### ISSUE THREAD

**Issue by ttma1046** [Yermo/nativescript-mapbox#40]
Thanks for building this awesome plugin!

I followed the steps what they do during NativeScript 2.3 webinar by using Angular 2 typescript with NativeScript to build an ios app. 

https://youtu.be/WQktviwAGb0?t=25m3s

I have defined the "mapbox", "token" variable and loadMap function in the imagesList.component.ts. 

Once I run the app in the IOS simulator, I got this error:

JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ReferenceError: Can't find variable: MGLOfflineStorage

I have generated a token with everything ticked on mapbox.com after I registered an account.

**Comment by EddyVerbruggen** [comment]
That's strange.. did you try this with --watch / livesync enabled? If so can you do a `tns run ios` without those features?

**Comment by auser** [comment]
Did you ever get this solved? I'm hitting the same bug.

**Comment by ahalls** [comment]
@auser  This seems to be a build problem.  I would suggest you 'Nuke' your project
```
tns platfrom remove ios
rm -rf lib/ node_modules/ hooks/
```
Remove your app from the device or emulator 

Then build again with `tns run ios `

Once the build issues are resolved then I could go back to using `livesync`

**Comment by auser** [comment]
Yep. I did that with both and it fixed it :)
