### ISSUE TITLE
Add support for Polyline in IOS

### ISSUE THREAD

**Issue by Stavanger75** [Yermo/nativescript-mapbox#41]
Thanks for a great plugin. 

Is it possible to implement the addPolyline for IOS also. 
Need this core feature :-)

**Comment by EddyVerbruggen** [comment]
Yeah it's a bit tricky, as is `addPolygon`. But I'm trying to find a way.

**Comment by bradmartin** [comment]
If you need me @EddyVerbruggen just let me know 😄 . I might take a stab at this in the next few weeks if I get an itch

**Comment by imekinox** [comment]
Hello @EddyVerbruggen Im trying to implement Polyline, but Im at the point in which everything complies and runs but the polygon or polyline is not rendered... I also had connected the directions API and rendered a marker per point in the route. Still, as you said, is tricky I see no reason why it doesn't show up... do you have any idea? I think it's drawing the polyline but somehow not rendering or cropped or on another layer?

**Comment by EddyVerbruggen** [comment]
@imekinox Sorry I didn't see your comment before - you can send a PR if you like and I'd be more than happy to take a look.

**Comment by briandilley** [comment]
Any update on this?

**Comment by EddyVerbruggen** [comment]
Not from me.

**Comment by d3mac123** [comment]
I'd love to hear (hopefully some good) news here. I'm even considering paying for this feature as my app has the ability to show the route on Android but not on the iPhone.

**Comment by chriszrc** [comment]
Just a quick clarification question, I'm trying to evaluate options for mapping with typescript, when you implement "addPolyline for iOS", do you mean a binding with the mapbox sdk that already supports that functionality (https://www.mapbox.com/ios-sdk/api/3.6.0/Classes/MGLPolyline.html)? Does this plugin not give us access to all the api methods of the raw platform map object?

**Comment by bradmartin** [comment]
@chriszrc - you have access to the SDK so you can do it yourself for sure. This request is to expose it simply to match up with what's already working on the Android side 👍

**Comment by d3mac123** [comment]
Brad is right. All I need/ask is the match with the current android features (addPolyline and removePolyline).

**Comment by d3mac123** [comment]
@imekinox @EddyVerbruggen can you share the code you have written originally? Although I am far from a pro developer, I have some available time that I could use trying to figure out what is happening with the iOS part.

I am really in need of this feature for my app.

**Comment by EddyVerbruggen** [comment]
iOS support landed in 3.0.2. I've also added a new `opacity` property to this function so you can further tweak the appearance. Details are in the readme.
