### ISSUE TITLE
Does Mapbox measure this plugin's usage as a native app?

### ISSUE THREAD

**Issue by AnthonySmith01** [Yermo/nativescript-mapbox#42]
Hi

Great plugin, I just have a quick question.

Mapbox plans place limits based on either "map views" or "mobile users". 
The starter plan being: 50,000 map views / mo, or 50,000 mobile users / mo

The Mapbox documentation specifically refers to native apps when it talks about measuring mobile users. Does this plugin interact with Mapbox like a native app? (i.e measuring mobile users) or does this affect map views instead?

Thanks :)

**Comment by EddyVerbruggen** [comment]
I'm sure they want to differentiate between web and app. So in this regard it's a native app. Which uses the native sdk's as opposed to the web libraries.

**Comment by AnthonySmith01** [comment]
Thank you! :)
