### ISSUE TITLE
Allow to use icon path from resource

### ISSUE THREAD

**Issue by tviel** [Yermo/nativescript-mapbox#43]
Cannot find a way to use iconPath from a resource (as res://) to use native methods for selecting the best image for the current device screen density.

**Comment by EddyVerbruggen** [comment]
I'm going to add a `icon` property you can use this with.

**Comment by EddyVerbruggen** [comment]
Added to version 2.2.0. See the updated TS definition for details, and there's a little sample in the readme as well.
