### ISSUE TITLE
Question: remove the polyline

### ISSUE THREAD

**Issue by bradmartin** [Yermo/nativescript-mapbox#47]
I didn't find anything in the native android sdk, curious if you've seen support to remove a previously drawn line or have any suggestion on a good approach for that?

I've drawn a line and plotted the markers, successfully removed the markers but now need to remove the line so it's not there for a new line (route) with the new markers plotted, hope that makes sense. I'll dig around later and see but just curious. Thanks.

**Comment by bradmartin** [comment]
Looks like it from the API for Annotations https://www.mapbox.com/android-sdk/api/4.2.0-beta.4/ `remove()`. Have to keep a reference to the annotation added to the map and then looks like `remove()` on that object will remove from the map.

**Comment by bradmartin** [comment]
Doh! Should have checked the plugin source first 😄  https://github.com/EddyVerbruggen/nativescript-mapbox/blob/master/mapbox.android.js#L346

**Comment by EddyVerbruggen** [comment]
Hmm, I just saw `addPolyline` is not in the `d.ts` file. Let me add that and also add [`removePolyline`](https://www.mapbox.com/android-sdk/api/4.2.0-beta.4/com/mapbox/mapboxsdk/maps/MapboxMap.html#removePolyline-com.mapbox.mapboxsdk.annotations.Polyline-) as I think that makes sense.

**Comment by EddyVerbruggen** [comment]
OK, when adding a polyline pass in an `id` property (a number makes sense, but can be any type, like the `id` of markers). Then use `removePolylines` (plural) to get rid of it. See the updated [readme](https://github.com/EddyVerbruggen/nativescript-mapbox#removepolylines-android).

**Comment by bradmartin** [comment]
What a turn around 🎉

**Comment by bradmartin** [comment]
I've copied over the files, rebuild and installed the updated source. `removePolylines` is undefined on the map instance. I have the other methods. Might be a small issue (typo)

**Comment by EddyVerbruggen** [comment]
Did you also update `mapbox-common.js`? Otherwise plz show me the stacktrace/error.

**Comment by bradmartin** [comment]
`removePolylines` is just undefined on the map object. 
`animateCamera`, `addMarkers`, `removeMarkers`, `addPolyline` all log out the function when called on the map instance I have. I'm pretty sure I copied over all the .js files and got a new build going. I'll try again and let you know with better info.

Log when calling `this._map.animateCamera;`

``` JS
function (args) {
    mapbox.animateCamera(args, this.native);
}
```

**Comment by EddyVerbruggen** [comment]
Yep, that's the definition of [this function](https://github.com/EddyVerbruggen/nativescript-mapbox/blob/master/mapbox-common.js#L106-L108), a few lines below is `removePolylines`. I'm afraid there's an old version of that file being cached somewhere..

**Comment by bradmartin** [comment]
Something was cached locally. Had to do a complete teardown to get it going. Thanks again @EddyVerbruggen  👍  it's possible that my package.json locked at `2.0.0` was causing the issue even though I was manually placing the code in the node_module. Likely on the build it was getting the npm version source
