### ISSUE TITLE
Request: change Position of Markers without removing them first

### ISSUE THREAD

**Issue by tastypwnda** [Yermo/nativescript-mapbox#48]
We have an issue where the first draw of marker icons shows them without custom marker image and on the second attempt it works. So if I successfully have drawn a marker I want to just move it. Do you plan this function for future releases?

**Comment by EddyVerbruggen** [comment]
You're right about the custom image not showing upon first appearance. How about I fix that issue on iOS instead of adding a move feature?

**Comment by tastypwnda** [comment]
I would appreciate a bug fix on this topic, because for now every marker we place in our app needs to be drawn twice. Is there also a way showing in which direction a user is heading? Like a direction indicator or map rotation?

**Comment by EddyVerbruggen** [comment]
Direction is not possible atm, but this bug has been fixed in the very soon to be released 2.2.0 version.

**Comment by tastypwnda** [comment]
Out of curiosity why is direction not possible? I looked into the mapbox API and there are some features like "map-rotation" that would help our usability along.

**Comment by EddyVerbruggen** [comment]
I meant it's not possible with this plugin at the moment (AFAIK).
