### ISSUE TITLE
[Question] add Marker on tap

### ISSUE THREAD

**Issue by lukashlobil** [Yermo/nativescript-mapbox#51]
Hello, I am creating the map programmatically. I'd like to add a marker on tapped location on the map. I know how to add markers to the map programmatically, but don't understand how to register a tap handler and get tapped coordinates. Can you point me to the solution please?

**Comment by EddyVerbruggen** [comment]
Hmm, interesting one, I don't think you can currently get the tapped coordinates. We'll need to look in the Mapbox SDK to see if that's possible.

**Comment by lukashlobil** [comment]
According to [official docs](https://www.mapbox.com/mapbox-gl-js/example/mouse-position/) it seems to be very possible. 
paraphrasing code example: 
`map.on('mousedown', function (e) {
        JSON.stringify(e.lngLat);` })

I am willing to help out with the implementation, although I haven't really developed a NativeScript plugin before.

**Comment by EddyVerbruggen** [comment]
Appreciate you help looking up the code in the official doc, but that's the JS API whereas this plugin uses the native SDK's. Could be there's something similar.

**Comment by EddyVerbruggen** [comment]
[Relevant Android API](https://www.mapbox.com/android-sdk/api/4.1.1/com/mapbox/mapboxsdk/maps/MapboxMap.OnMapClickListener.html)

For iOS there seems to be no such thing.. I'd expect something on [the delegate](https://www.mapbox.com/ios-sdk/api/3.3.4/Protocols/MGLMapViewDelegate.html) but there's not. However, there seems to be [a way](https://github.com/mapbox/mapbox-gl-native/issues/1113).

**Comment by EddyVerbruggen** [comment]
The Android implementation is ready to go, [check the doc](https://github.com/EddyVerbruggen/nativescript-mapbox#setonmapclicklistener-android). iOS is not likely to follow quickly as the Mapbox folks didn't expose an easy to use function yet. I hope this will at least offer some value to you.

Available from GitHub, not op npm yet.

**Comment by EddyVerbruggen** [comment]
Android support landed in 2.2.3.

**Comment by ajkula** [comment]
Hello, i might undertand your problem i had the same, on the mapbox.shox().then() callback, set an on map click listener, that promise never resolve, everything set there is valid for the rest of the instance.
only problem, which is the same as i got, every markers set after the initial .show() call, won't appear on the current session... and so i'm looking for a way to refresh map, anyway basically you'd like to :

```
 MapModel.prototype.doShow = function() {
mapbox.show({
            accessToken: accessToken,
            style: mapbox.MapStyle.DARK,
            blablabla
}).then(
            function(result) {
                mapbox.setOnMapClickListener(function(point) {
                    listener(point);
               });
           }
)}
```

**Comment by EddyVerbruggen** [comment]
iOS support via #153
