### ISSUE TITLE
Enhancement/Request: timeout when loading XML map

### ISSUE THREAD

**Issue by bradmartin** [Yermo/nativescript-mapbox#52]
The mapbox loading into a view can cause an app to hang for half a second or so. When you declare the map in XML and navigate to the page you have no way to delay that execution so it doesn't cause an interruption to the navigation transition.

A simple solution would be to add a property on the XML view, such as `delayMapInit` and then accept a value in milliseconds, so then we can make sure the navigation transition has completed before the map constructor is started which isn't the smoothest process. Let me know your thoughts @EddyVerbruggen, you might have a better idea since you know the SDKs better than I for mapbox.

**Comment by EddyVerbruggen** [comment]
Great idea!

**Comment by EddyVerbruggen** [comment]
Update: got Android behaving nicely locally.

**Comment by bradmartin** [comment]
looking forward to it... prepping the app for publish and this is one of the last things on my personal issues 😄

**Comment by EddyVerbruggen** [comment]
Can you update the plugin from GitHub (see the last check-in). You get to set a `delay` property in the XML definition. For instance, `delay="500"` means the plugin will wait half a second before invoking the Mapbox SDK.

**Comment by bradmartin** [comment]
Yes I'll test this out soon.

**Comment by bradmartin** [comment]
Good to go 👍

**Comment by EddyVerbruggen** [comment]
Sweet! 2.2.2 is on npm.
