### ISSUE TITLE
Change map style method

### ISSUE THREAD

**Issue by bradmartin** [Yermo/nativescript-mapbox#53]
I've not looked into the source of the SDKs to see if it's possible, but being able to change the map style dynamically would be a nice feature 😄 . 

Specifcally looking to do against the XML rendered map after the fact.

Scenario: user loads the app doesn't like the default style or is hard on their eyes so they can try out 'dark'.

**Comment by EddyVerbruggen** [comment]
Great suggestion once more - available in 2.2.3. Updated the [readme](https://github.com/EddyVerbruggen/nativescript-mapbox#setmapstyle), can be used from XML's `mapReady` as well.
