### ISSUE TITLE
iOS accessToken in XML not working

### ISSUE THREAD

**Issue by bradmartin** [Yermo/nativescript-mapbox#54]
Getting this dialog: https://github.com/EddyVerbruggen/nativescript-mapbox/blob/master/mapbox.ios.js#L34
 
Markup works fine on Android.
``` xml
<map:Mapbox row="1" col="0" rowSpan="5" colSpan="5" id="map" delay="800" disableRotation="true" mapStyle="streets" mapReady="{{ onMapReady }}" latitude="39.8282" longitude="-98.5795" zoomLevel="3.0" showUserLocation="false" hideLogo="true" hideAttribution="false" accessToken="pk.whatever.GOhome"></map:Mapbox>
       
```

I'll dig around later and see if I'm missing something obvious

**Comment by bradmartin** [comment]
This shows in the log when navigating to this page, it might be more useful to you than me Eddy. I have very little iOS knowledge 😄 

``` terminal
Nov  9 22:40:07 Bradleys-MacBook-Pro NASTC[74265]: Presenting view controllers on detached view controllers is discouraged <UIViewControllerImpl: 0x7fcb32e60870>.
Nov  9 22:40:07 Bradleys-MacBook-Pro NASTC[74265]: [ERROR] {}[Setup]: loading style failed: HTTP status code 401

```

**Comment by EddyVerbruggen** [comment]
Hey Brad,

Looks like certain properties can't be used, not sure what's up with that, but doing it like this works (that accessToken error is just a symptom of that problem):

``` xml
            <map:Mapbox
               delay="800"
               disableRotation="true"
               mapStyle="streets" 
               mapReady="onMapReady" 
               latitude="39.8282" 
               longitude="-98.5795" 
               zoomLevel="3.0" 
               showUserLocation="false" 
               hideLogo="true" 
               hideAttribution="false" 
               accessToken="my-token">
            </map:Mapbox>

```

**Comment by bradmartin** [comment]
Let me give that a try, actually was about to dig into the iOS error messages and see what in the world was going on 😄

**Comment by EddyVerbruggen** [comment]
One thing I learned from iOS error messages: they're useless.

**Comment by bradmartin** [comment]
Good to know lol, I'm still having an issue. Trying to see what attribute is causing an issue. Were you saying the snippet ^^^ worked?

**Comment by EddyVerbruggen** [comment]
Yes it did for me. Perhaps try without `disableRotation` and `mapReady` first?

**Comment by bradmartin** [comment]
Error

``` xml
        <map:Mapbox id="map" delay="800"  mapStyle="streets" latitude="39.8282" longitude="-98.5795" accessToken="mykey"></map:Mapbox>

```

**Comment by EddyVerbruggen** [comment]
That `id` must go

**Comment by bradmartin** [comment]
Yea seems `id` is the issue on iOS... now to see what I need... blank map but no dialog.

Now this is constantly logging: 

```
Nov 10 13:00:14 Bradleys-MacBook-Pro NASTC[82518]: Failed to make complete framebuffer object 8cd6
Nov 10 13:00:14 Bradleys-MacBook-Pro NASTC[82518]: Failed to bind EAGLDrawable: <CAEAGLLayer: 0x600000431260> to GL_RENDERBUFFER 1
```

**Comment by EddyVerbruggen** [comment]
My example posted above (without the id) and a correct accesstoken showed me a few US states

**Comment by bradmartin** [comment]
Rendering now, so it is the `id` (I removed my grid properties 😉 )

**Comment by EddyVerbruggen** [comment]
Do you need the id for anything?

**Comment by bradmartin** [comment]
Was how I got the instance of the UI, but mapReady and then assigning will work. So don't need it but was just how I went about it.

**Comment by EddyVerbruggen** [comment]
Ah, cool, btw I needed to do `mapReady="onMapReady"` instead of `mapReady="{{ onMapReady }}"` to make it work.

**Comment by bradmartin** [comment]
Yea... I'll work on that, may just construct and pass into my view-model. No big deal, thanks for helping @EddyVerbruggen. Feel free to close, maybe doc the `id` not working on iOS 🤔

**Comment by EddyVerbruggen** [comment]
ok, thanks for letting me know as well!

**Comment by bradmartin** [comment]
I'm starting to question everything I believe in 😄 
I'm not certain it is the `id` now.

**Comment by bradmartin** [comment]
Still can't narrow it down 😞  - the map renders but I am constantly getting the `set accessToken warning and it seems the lat/long and zoom are being ignored.

I've simplified everything to make it easier to narrow down: 

``` xml
<Page id="page" 
    xmlns="http://schemas.nativescript.org/tns.xsd" 
    xmlns:map="nativescript-mapbox" 
    xmlns:FAB="nativescript-floatingactionbutton" loaded="loaded">
    <ActionBar title="Map">
        <NavigationButton text="Back" icon="res://ic_arrow_back" tap="{{ goBack }}" />
        <ActionBar.actionItems>
            <ios>
                <ActionItem icon="res://ic_directions_white" tap="{{ directionsFabTap }}" ios.position="right" />
            </ios>
        </ActionBar.actionItems>
    </ActionBar>
    <StackLayout>
        <!-- MapBox -->
        <map:Mapbox
        height="100%"
        mapReady="onMapReady" 
        latitude="39.8282" 
        longitude="-98.5795" 
        accessToken="myKey">
        </map:Mapbox>
    </StackLayout>
</Page>

```

**Comment by bradmartin** [comment]
It's very random and at this point IDK if it's the code not updating on the app, tried livesync and running with changes. Sometimes it works and sometimes it doesn't after making changes, just lost man.

**Comment by EddyVerbruggen** [comment]
It turns out you have to make sure you're not using properties not listed in the readme, so the `height` property needs to go.

You can control layout like I'm doing in the [demo app](https://github.com/EddyVerbruggen/nativescript-mapbox-demo): wrap it in a `ContentView` like this:

``` xml
<Page id="page" 
    xmlns="http://schemas.nativescript.org/tns.xsd" 
    xmlns:map="nativescript-mapbox" 
    xmlns:FAB="nativescript-floatingactionbutton" loaded="loaded">
    <ActionBar title="Map">
        <NavigationButton text="Back" icon="res://ic_arrow_back" tap="{{ goBack }}" />
        <ActionBar.actionItems>
            <ios>
                <ActionItem icon="res://ic_directions_white" tap="{{ directionsFabTap }}" ios.position="right" />
            </ios>
        </ActionBar.actionItems>
    </ActionBar>
    <StackLayout height="100%">
        <ContentView height="100%">
            <map:Mapbox
                mapReady="onMapReady" 
                latitude="39.8282" 
                longitude="-98.5795" 
                accessToken="your-key">
            </map:Mapbox>
        </ContentView>
    </StackLayout>
</Page>
```

**Comment by EddyVerbruggen** [comment]
Please update to 2.2.3 if you're not using the `delay` property as there was a little bug (unrelated to this issue).

**Comment by bradmartin** [comment]
Thanks. Never used ContentView, wouldn't have guessed that.

**Comment by bradmartin** [comment]
I know why I think. Might have a PR later or early next week.
