### ISSUE TITLE
Question: marker tap on iOS simulator

### ISSUE THREAD

**Issue by bradmartin** [Yermo/nativescript-mapbox#55]
Unfortunately, I don't have an iOS device handy right now. On the simulator should/do the marker taps work? I have the markers rendered for locations and Android everything works fine so just curious if it should be working with the marker opening the `callOut` so I can get to that event.

**Comment by EddyVerbruggen** [comment]
Just checked with a map rendered from code as well as XML and it seems to work nicely in the simulator:

![simulator screen shot 12 nov 2016 22 43 15](https://cloud.githubusercontent.com/assets/1426370/20242339/f0cb73e6-a92a-11e6-9440-753c0b493eae.png)

**Comment by bradmartin** [comment]
Good to know. I'll keep digging. I think I have an idea maybe where I went
wrong.

**Comment by bradmartin** [comment]
Yea checked the demo and works fine. Not sure what's up here but guessing some order of operations and iOS stuff that I don't know about 😄 

![snip20161113_3](https://cloud.githubusercontent.com/assets/6006148/20252577/1f2d43fe-a9e9-11e6-9c45-5d52cc312905.png)

If you see that image above it's from the debugger. I basically get an array of markers from an HTTP call, then loop the array and add the `onTap` and `onCalloutTap` event before calling `addMarkers()` and this works great on Android and it doesn't blow up on iOS as I step through. If I have to I can move the functions to the server side in the JSON no big deal.

**Comment by bradmartin** [comment]
![snip20161113_4](https://cloud.githubusercontent.com/assets/6006148/20253961/8197c224-a9f5-11e6-9670-56a71c8481be.png)

Another debugger screen. I'm still not able to see why iOS doesn't work and Android will.

**Comment by bradmartin** [comment]
Also stumbled across the `{{ mapready }}` bindings work on Android, no luck yet on iOS.

**Comment by bradmartin** [comment]
FOUND IT!!! 

If `delay` is set the marker taps won't work on iOS. Tested with demo code adding a marker in the `mapReady` event and my loop code and without the delay it works fine. If the `delay` is on the map the marker tap I can't get it to work.

**Comment by EddyVerbruggen** [comment]
Looks like the mapReady event fires when the map is loaded, ignoring any delay so that makes a lot of sense.

**Comment by EddyVerbruggen** [comment]
Hey Brad, your feedback was great and it helped me find the problem. Should be OK now (not on npm yet, but it's here on github).
