### ISSUE TITLE
iOS crash - this._mapLoadedCallback is not a function

### ISSUE THREAD

**Issue by bradmartin** [Yermo/nativescript-mapbox#57]
version 2.3
### Exception:

`
file:///app/tns_modules/nativescript-mapbox/mapbox.js:794:28: JS ERROR TypeError: this._mapLoadedCallback is not a function. (In 'this._mapLoadedCallback()', 'this._mapLoadedCallback' is undefined)
`

I haven't pinned down when/why this throws but saw it once when I navigated to the page with the map and then the map worked fine the next time (I think) sorry I don't have much more right now.

**Comment by EddyVerbruggen** [comment]
Perhaps we can get away with adding a `!== undefined` check to [this line](https://github.com/EddyVerbruggen/nativescript-mapbox/blob/master/mapbox.ios.js#L794)

**Comment by bradmartin** [comment]
Now I can't get it to happen :( it's possible I had a version issue with updating and not installing the new iOS build. So this may not even be an issue.

**Comment by dogabudak** [comment]
that generally happens if you are using emulator in live-sync mode, maybe it gives a clue ?
