### ISSUE TITLE
Set z-index programatically

### ISSUE THREAD

**Issue by maabreve** [Yermo/nativescript-mapbox#59]
Hi,  im declaring the map programmatically inside a SideDrawer and the map is in a layer over the drawer.  

Is it possible set z-index programatically?

Thank you

**Comment by EddyVerbruggen** [comment]
Are you using the XML definition to create the map?

**Comment by maabreve** [comment]
No, Im instantiating using  mapbox.show() in the .ts file (NS + Angular)

**Comment by EddyVerbruggen** [comment]
So that's the answer then, defined the map in XML and you should be good; it's exactly why it has been added to the plugin.

**Comment by maabreve** [comment]
Thanks!!
