### ISSUE TITLE
Add click event on marker

### ISSUE THREAD

**Issue by ofirdagan** [Yermo/nativescript-mapbox#6]
Is it possible to run a click handler when a specific marker's box is clicked?

10x.

**Comment by rpereiraprieto** [comment]
i need a click handler on marker, please, help ...

**Comment by rpereiraprieto** [comment]
Hello,
and I did, adding the following to the show method :

_      if(settings.callBack){
          var newListen=new com.mapbox.mapboxsdk.views.MapView.OnInfoWindowClickListener(
              {
                  onMarkerClick:function(clickedMarker)
                  {
                      settings.callBack(clickedMarked);
                      return true;
                  }
              }
         );
          mapView.setOnInfoWindowClickListener(newListen);
      }_

and the call to show , setting the field to the function handler callBack
...
        disableZoom: false, // default false 
        callBack:function(clickedMarker){ ... }

regards.

**Comment by EddyVerbruggen** [comment]
That's great, @rpereiraprieto! Would you mind sending a PR? I'm of course willing to polish it if that's needed but it would be great to have more folks contributing.

**Comment by rpereiraprieto** [comment]
Hi Eddy, 

The method works fine, but only in android. I will wait for someone who make a complete solution for nativescript.

Thank you so much

Regards

Enviado desde mi iPhone

**Comment by EddyVerbruggen** [comment]
If you submit the PR then I'll take a stab at the iOS implementation, promised :innocent:

**Comment by rpereiraprieto** [comment]
ok, i will submit the PR, when i have a few time, today i have a sunny day.

2016-03-26 16:58 GMT+01:00 Eddy Verbruggen notifications@github.com:

> If you submit the PR then I'll take a stab at the iOS implementation,
> promised [image: :innocent:]
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/EddyVerbruggen/nativescript-mapbox/issues/6#issuecomment-201868727

## 

[image: Logo]

Ramón Pereira
_635518821_ · rpereira@adealoxica.com [image: skype]

Adealóxica Ingeniería Informática
Panama  16 · 36203 - Vigo
Tlf: _986122614_ adealoxica@adealoxica.com · www.adealoxica.com

[image: eco] No me imprimas si no es necesario. Protejamos el medio ambiente

AVISO LEGAL: El contenido de este mensaje de correo electrónico, incluidos
los ficheros adjuntos, es confidencial y está protegido por el artículo
18.3 de la Constitución Española, que garantiza el secreto de las
comunicaciones. Si usted recibe este mensaje por error, por favor póngase
en contacto con el remitente para informarle de este hecho, y no difunda su
contenido ni haga copias.

**\* Este mensaje ha sido verificado con herramientas de eliminación de
virus y contenido malicioso ***

Este aviso legal ha sido incorporado automáticamente al mensaje.

**Comment by EddyVerbruggen** [comment]
I just implemented this feature, landing in 1.2.0 real soon.

**Comment by burkeholland** [comment]
+1

**Comment by ofirdagan** [comment]
👍  10x!
