### ISSUE TITLE
Add more ignore 

### ISSUE THREAD

**Issue by bradmartin** [Yermo/nativescript-mapbox#60]
- .vscode
- .idea 
folders

**Comment by EddyVerbruggen** [comment]
The ones you mention are already .gitignored..

**Comment by EddyVerbruggen** [comment]
Aw snap, but they're not .npmignored... somehow I figured that .npmignore would be a superset of .gitignore but I now realize that's rubbish.

**Comment by EddyVerbruggen** [comment]
Next version will be a bit cleaner, thx!
