### ISSUE TITLE
Accuracy on the location icon for Android

### ISSUE THREAD

**Issue by Stavanger75** [Yermo/nativescript-mapbox#61]
Hi

Would be great if accuracy where showing on the location icon. Is not working on Android. Work great on IOS. Probably related to #31 (where location icon is added in code) 

Image with accuracy on location: (from README.md)
https://raw.githubusercontent.com/EddyVerbruggen/nativescript-mapbox/master/screenshots/ios-xml-declared.png

Ref #31 
Accuracy image if needed
https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/res/drawable-xxhdpi/circle_icon.png

**Comment by EddyVerbruggen** [comment]
The implementation is completely different with 3.2.0 - the plugin is using the Mapbox location plugin which comes with its own indicator, so nothing for me to override really.
