### ISSUE TITLE
Cannot read property 'setOnMarkerClickListener' of undefined

### ISSUE THREAD

**Issue by leocrawf** [Yermo/nativescript-mapbox#64]
I have simply map but I cannot get addMarkers to work but the map is rendered nicely.

 I set the map in xml like this:

      <ContentView height="100%" width="100%" class="m-l-0 m-r-0" style="margin-top: 190">
            <Mapbox
                accessToken="token"
                mapStyle="OUTDOORS"
                latitude="17.9958256"
                longitude="-76.7862368"
                zoomLevel="14"
              (mapReady)="onMapReady($event)">
            </Mapbox>
       </ContentView>

Then in angular typescript If I use: 
         args.mapbox.addMarkers(....) 

the app freezes then close. If I use : 
        mapbox.addMarkers(....) 

The map is rendered with the error: 
       Cannot read property 'setOnMarkerClickListener' of undefined. 

Here is the file:

        import { Component } from '@angular/core';
        import {registerElement} from 'nativescript-angular/element-registry';
        var mapbox = require("nativescript-mapbox");

        registerElement("Mapbox", () => mapbox.Mapbox);
    
        @Component({
            selector: 'contact',
            templateUrl: 'modules/contact/contact.component.html',
            styleUrls:['modules/contact/contact.component.css']
        })

     export class ContactComponent {
        public onMapReady(args) {
         console.log(args);//this is outputting undefined.
         
            mapbox.addMarkers([
                {
                    id: 1,
                    lat: 17.9958256,
                    lng: -76.7862368,
                    title: 'One-line title here', // no popup unless set
                    subtitle: 'some text',
                    icon: 'res://green_pin_marker',
                    iconPath: 'res/markers/home_marker.png'
                }
                ]).then(
                        (result) => {
                            console.log("Mapbox Marker done " );
                        },
                        (error) => {console.log("Mapbox Marker error: " + error)}
            );

            }

        }

**Comment by EddyVerbruggen** [comment]
Hi, are you on 2.3.1? I tried to fix that in that version.

**Comment by leocrawf** [comment]
I am using 2.3.1

**Comment by MadhuSudhanBhaskar** [comment]
@EddyVerbruggen I get the same thing, I am not able to add markets to the map. This is my gitrepo.

Not just markers center or other apis, please look into this.

https://github.com/MadhuSudhanBhaskar/NativeTest/blob/angular-start/app/app.component.ts

**Comment by AKNiazi** [comment]
@leocrawf @MadhuSudhanBhaskar I looked into your examples and I came up with this.

```
 onMapReady(args){
    args.map.addMarkers([
    {
      id: 2, // can be user in 'removeMarkers()'
      lat: 52.3602160, // mandatory
      lng: 4.8891680, // mandatory
      title: 'One-line title here', // no popup unless set
      subtitle: 'Infamous subtitle!'
    }]);
  }
```

It is working fine on my Android Emulator and device.

**Comment by MadhuSudhanBhaskar** [comment]
@AKNiazi But in my case its not onload, mine is after some calls. Do I have to copy args to a variable on load in that case?

**Comment by AKNiazi** [comment]
@MadhuSudhanBhaskar. You can do something like

```
export class JourneyDetailComponent {
   private map: any;
   
  onMapReady(args){
    this.map = args.map;
    this.setCenter();
    
  }

  addMarker(){
    this.map.addMarkers([
    {
      id: 2, // can be user in 'removeMarkers()'
      lat: 52.3602160, // mandatory
      lng: 4.8891680, // mandatory
      title: 'One-line title here', // no popup unless set
      subtitle: 'Infamous subtitle!'
    }]);
  }

  setCenter(){
    this.map.setCenter(
    {
      lat: 52.3602160, // mandatory
      lng: 5.8891680, // mandatory
      animated: true // default true
    });
  }
}
```

Once you have the init map object, you can use it any time.

**Comment by MadhuSudhanBhaskar** [comment]
@AKNiazi I get markers working and zoom, but setCenter is always Nigeria even with your co-ordinates.

**Comment by leocrawf** [comment]
**@AKNiazi** what version of the plugin are you using is it 2.3.1?

**Comment by MadhuSudhanBhaskar** [comment]
@leocrawf Looks like it works with above way, but some time setcenter does not work. I am using
map box "nativescript-mapbox": "^2.3.1",

**Comment by leocrawf** [comment]
**@MadhuSudhanBhaskar** Thank you for comments. What do you get if you console.log() out your event object like this:

onMapReady(args){
    this.map = args.map;
     this.setCenter();
     console.log(this.map);
  }

I get Mapbox(255) though I do not really know what that means but I am trying to see if you get something different. One other thing I am testing on android device. What are you testing on?

**Comment by MadhuSudhanBhaskar** [comment]
I am testing it on Android as well. Will see what it logs.

**Comment by leocrawf** [comment]
Even after following all that instruction I am still not seeing the marker only the map. I will do a tns build android and tns run android.

**Comment by leocrawf** [comment]
I did a tns build android and tns run android but still no marker only map.

**Comment by MadhuSudhanBhaskar** [comment]
May be can you share your repo here?

Regards,
Madhu

**Comment by leocrawf** [comment]
My bad. I was not calling this.mapbox().  It now works as expected.

    setCenter(){
    this.map.setCenter(
    {
      lat: 52.3602160, // mandatory
      lng: 5.8891680, // mandatory
      animated: true // default true
    });
     this.mapbox()
   }

**Comment by leocrawf** [comment]
I am now seeing marker but no popup with text.

**Comment by csorgocsaba** [comment]
Hi!
I'm in a same situation. But i have another problem too because I want to call some function from out of onMapReady. E.g. I want to setCenter(markers) when user set the position of the new center. Could I call this function out of onMapReady?
I tried this:

onMapReady(args){
  this.map = args.map;
}

setCenter(options){
  this.map.setCenter(
    {
      lat: 1.0,
      lng: 1.0,
      animated: true
  });
}

And I have a button to call setCenter()

And of course I tried  to use this:

...
setCenter(options){
  mapbox.setCenter(
    { ...

But nothing works

**Comment by csorgocsaba** [comment]
Hi!
I'm in a same situation. But i have another problem too because I want to call some function from out of onMapReady. E.g. I want to setCenter(markers) when user set the position of the new center. Could I call this function out of onMapReady?
I tried this:

onMapReady(args){
  this.map = args.map;
}

setCenter(options){
  this.map.setCenter(
    {
      lat: 1.0,
      lng: 1.0,
      animated: true
  });
}

And I have a button to call setCenter()

And of course I try it to create this:

...
setCenter(options){
  mapbox.setCenter(
    { ...

But nothing works

**Comment by leocrawf** [comment]
**@csorgocsaba** From my simple tests and it has been said by others here that setCenter does not work as intended.

**Comment by csorgocsaba** [comment]
I have managed to use some function to they was called from out of onMapReady, but I need any information about the visible part of map but some runtime exception from java was given when I called getCenter or getViewport.
