### ISSUE TITLE
Mapbox dissapear, when call routerExtensions.back()

### ISSUE THREAD

**Issue by iljagrabar14** [Yermo/nativescript-mapbox#65]
I use mapbox in my application. When I navigate on the page, where I use map, all works perfect. After that I tap on one of the markers and I navigate on the next page. But when I click backButton, or call routerExtensions.back() on the next page, I return on the page with map, but map dissapears. I can tap blindly on my map markers and I will navigate on the next page, but I don't see map.

Here is the code of class with map:

    export class CarwashListComponent implements OnInit {

    ngOnInit() {
        this.initMap();
    }

    initMap(){
        var _this = this;
        this.mapbox.show({
                accessToken: "pk.eyJ1IjoiaWxqYWdyYWJhcjE0IiwiYSI6ImNpd25laGw2YTAwMTIyeW10ZXM0a3l6M2UifQ.CfGJKVjVzM-lRzko7cP37g",
                mapStyle: "light",
                center: { // optional without a default
                    lat: this.cities[0]['coordinates'][1],
                    lng: this.cities[0]['coordinates'][0]
                  },
                    markers: [
                    {
                     lat: 52.3732160, 
                     lng: 4.8941680, 
                     title: 'Nice location', 
                     subtitle: 'Really really nice location', 
                     onCalloutTap: function () {
                                 _this.routerExtensions.navigate(["next_page"]))
            }
                ],
                zoomLevel:9.5,
                showUserLocation: "true"
        })

    }
    }

What am I doing wrong?

**Comment by EddyVerbruggen** [comment]
Not sure, but you should declare your map in XML to make it easy to navigate back and forth and avoid having to manually show and hide the map.

**Comment by idomaz00** [comment]
hi @iljagrabar14 I have the same issue, but I need to declare my map programatically because of some other functionalities. Did you manage to solve this issue?
