### ISSUE TITLE
user location by xml

### ISSUE THREAD

**Issue by yasalmasri** [Yermo/nativescript-mapbox#68]
Hi

I have tried to show user location by generating the map by xml, it shows on iOS but on Android does not appear.

```
<map:Mapbox
          latitude="25.658517"
          longitude="-100.357239"
          zoomLevel="9"
          mapStyle="light"
          hideAttribution="true"
          showUserLocation="true"
          hideCompass="false"
          accessToken="sk.eyJ1IjoiZWRkeXZlcmJydWdnZW4iLCJhIjoia1JpRW82NCJ9.OgnvpsKzB3GJhzyofQNUBw">
        </map:Mapbox>
```
if I generate the map programmatically, it shows the user location on both iOS and Android.
but by XML does not show on Android.

Thanks

**Comment by EddyVerbruggen** [comment]
Looks like you have a point, I don't think that has been implemented for Android yet. Let me take a look.

**Comment by EddyVerbruggen** [comment]
Can you give it a try with the latest version on GitHub (not on npm yet, but soon).

This also manages the permissions for Android 6+ automatically, no longere needed to ask those beforehand.
