### ISSUE TITLE
Custom Style URL,  Angular2 created in XML crashes on iOS 

### ISSUE THREAD

**Issue by ahalls** [Yermo/nativescript-mapbox#69]
I would like to use a custom MapStyle URL.  I'm using Angular2/Nativescript.  I've created the map using in XML. 

```
        <Mapbox #mapboxview
            accessToken= <TOKEN>
            mapStyle= <STYLE URL>
            latitude="39.9780"
            longitude="-82.4182"
            zoomLevel="14"
            showUserLocation="true"
            (mapReady)="onMapReady($event)">
        </Mapbox>
```

Crashes on iOS with: 
```
-[__NSCFString scheme]: unrecognized selector sent to instance
``` 

Works on Android.

**Comment by ahalls** [comment]
I'm guessing a NSString is provided where a NSURL is expected. 

http://stackoverflow.com/questions/33014184/terminating-app-due-to-uncaught-exception-nsinvalidargumentexception-reason

**Comment by EddyVerbruggen** [comment]
Thanks for reporting *and* fixing this!
