### ISSUE TITLE
Create map as XML element?

### ISSUE THREAD

**Issue by jaredwiener** [Yermo/nativescript-mapbox#8]
For ease of positioning, curious if it could be possible to instantiate the map as an XML element instead of calling the javascript and explicitly marking coordinates?

**Comment by xerotolerant** [comment]
Hello. I would like to help with this. What do you need? I'm not super experienced but I was told that helping out on an open source project is a good place to start.

**Comment by EddyVerbruggen** [comment]
Hi @xerotolerant that's very nice of you. I know that Burke Holland was attempting to do the same, perhaps it's a good idea to open an issue [on his fork](https://github.com/burkeholland/nativescript-mapbox).

**Comment by EddyVerbruggen** [comment]
This feature landed in 2.0.0.
