### ISSUE TITLE
Can't get map to show in nativesrcipt angular project

### ISSUE THREAD

**Issue by elvismercado** [Yermo/nativescript-mapbox#81]
I get a blank box.

In the terminal i get the following error: `Failed to bind EAGLDrawable: <CAEAGLLayer: 0x600000830ac0> to GL_RENDERBUFFER 1`

See this image: [http://imgur.com/a/6xYj9](url)

`main.ts`
`
import * as elementRegistryModule from 'nativescript-angular/element-registry';
elementRegistryModule.registerElement("Mapbox", () => require("nativescript-mapbox").Mapbox);
`

`mymap.html`
`
<ContentView width="240" height="240">
	<MapBox
		accessToken="accessToken"
		latitude="52.3702160"
		longitude="4.8951680"
		zoomLevel="3"
		mapStyle="satellite"
		hideAttribution="false"
		showUserLocation="true"
		hideCompass="false"
		mapReady="onMapReady">
	</MapBox>
</ContentView>
`

Simulator: iPhone6 iOS10.2
Tablet: Ipad2 iOS9

**Comment by EddyVerbruggen** [comment]
This may be nothing, but you're registering `Mapbox` and using `MapBox` (uppercase 'B').

Is the accesstoken correct? That blank map may indicate it's not..

**Comment by elvismercado** [comment]
I am registering and using `Mapbox` correctly. I will ' check the access token again and let you know if it was that.
