### ISSUE TITLE
How to destroy map?

### ISSUE THREAD

**Issue by shivapersad** [Yermo/nativescript-mapbox#84]
Presently I am able to show the map but I am having an issue to destroy the created map. I currently have it set to "hide" when I go back to my Homepage but on iOS is there a short delay for the map to get hidden so the screen goes back to the Homepage and the map remains onscreen temporarily before being hidden. Is there any way to destroy the map when the "ngOnDestroy()" lifecycle even is called? Thanks.

**Comment by shivapersad** [comment]
@EddyVerbruggen Any assistance with this issue?

**Comment by EddyVerbruggen** [comment]
Lol, I was just typing a reply: Your usecase has a better fit for the map defined in XML, so it's destroyed when the view is destroyed.

**Comment by shivapersad** [comment]
Do you have an example app I can reference to do the XML use case? Thanks.

**Comment by EddyVerbruggen** [comment]
See the readme and the [demo app](https://github.com/EddyVerbruggen/nativescript-mapbox-demo).

**Comment by shivapersad** [comment]
Any change you have an Angular+Typescript example?

**Comment by EddyVerbruggen** [comment]
The first comment in #80 seems fine, except for the issue fixed in 2.5.2.

**Comment by shivapersad** [comment]
Ok. Will give it a shot. Thanks again.

**Comment by EcoDomDev** [comment]
@EddyVerbruggen I am using Vue with nativescript.

In the used component I have:
```
const mapbox = require("nativescript-mapbox");
```
I tried even with `import`, but when I call in any `@tap` handler `mapbox.destroy` it is `undefined`.

How should I access destroy method in Vue? Thanks.
