### ISSUE TITLE
Edit a map defined into the xml

### ISSUE THREAD

**Issue by Dangradz** [Yermo/nativescript-mapbox#85]
Is it possible to edit dynamically from the .js a map that has been defined into the xml? How can I refer to it into the js?

**Comment by Dangradz** [comment]
nobody?

**Comment by seros00** [comment]
You can refer to the map with the onMapReady function:
`function onMapReady(args) {
  var map = args.map;
}`

**Comment by EddyVerbruggen** [comment]
It's in the [readme](https://github.com/EddyVerbruggen/nativescript-mapbox#declaring-a-map-in-xml-recommended-approach), look for `onMapReady` as @seros00 suggested.
