### ISSUE TITLE
Unable to get markers to display

### ISSUE THREAD

**Issue by shivapersad** [Yermo/nativescript-mapbox#86]
@EddyVerbruggen 

I am running "nativescript-mapbox @ 2.5.1". I was able to get the map to show on the Android version but the markers are not appearing and I get the following in my console log:

JS: Unhandled Promise rejection: iconFactory.fromDrawable is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: iconFactory.fromDrawable is not a function TypeError: iconFactory.fromDrawable is not a function
JS:     at file:///data/data/org.ngccng.cngApp/files/app/tns_modules/nativescript-mapbox/mapbox.js:510:47
JS:     at ZoneDelegate.invoke (file:///data/data/org.ngccng.cngApp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:190:28)
JS:     at Zone.run (file:///data/data/org.ngccng.cngApp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:83:43)
JS:     at file:///data/data/org.ngccng.cngApp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:449:57
JS:     at ZoneDelegate.invokeTask (file:///data/data/org.ngccng.cngApp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:223:37)
JS:     at Zone.runTask (file:///data/data/org.ngccng.cngApp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:123:47)
JS:     at drainMicroTaskQueue (file:///data/data/org.ngccng.cngApp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:355:35)
JS: Error: Uncaught (in promise): TypeError: iconFactory.fromDrawable is not a function

Any assistance on what is causing this issue is appreciated.

**Comment by EddyVerbruggen** [comment]
I've found the cause and fixed this problem in 2.5.2 in issue #80. Thanks for reporting it!

**Comment by shivapersad** [comment]
Ok great. I would like to test but presently getting an issue adding the android platform back to my Nativescript application (error: sed: invalid replacement string). Once I get it back up and running I'll test it and let you know.

**Comment by EddyVerbruggen** [comment]
OK, I'll publish 2.5.2 to npm shortly.

**Comment by shivapersad** [comment]
Ok will try to update the package in a couple hours and see if you've pushed it to npm. By the way do I still need to add

<service android:name="com.mapbox.services.android.telemetry.service.TelemetryService" />

to the AndroidManifest.xml or can I use the previous service?

<service android:name="com.mapbox.mapboxsdk.telemetry.TelemetryService" />

Thanks.

**Comment by EddyVerbruggen** [comment]
The plugin will handle that for you, no need to add it yourself.

**Comment by shivapersad** [comment]
Ok great. Thanks! Sorry for being a pain.

**Comment by EddyVerbruggen** [comment]
You're not 👍

**Comment by shivapersad** [comment]
Hey @EddyVerbruggen. I tested the 2.5.2 so my map displays with markers but when I zoom in on an area the app crashes :(. This is only affecting the Android version. iOS is fine.
