### ISSUE TITLE
Can't download offline region on Android

### ISSUE THREAD

**Issue by KuboStraka** [Yermo/nativescript-mapbox#88]
Hi,
I need to use offline maps in my app (android and ios).

When I tried to use `mapbox.downloadOfflineRegion` method I got and Error. After few minutes of debugging I noticed, that there is no `mapbox.downloadOfflineRegion` method in your _mapbox.android.js_ file (_../node_modules/nativescript-mapbox/_), there are only methods for deleting and list of offline regions.

But in _mapbox.ios.js_ there is also `mapbox.downloadOfflineRegion` method. It is possible to add this method also for android please?

Thanks

**Comment by KuboStraka** [comment]
Hi again,
I managed to solve my problem by copying the `mapbox.downloadOfflineRegion` method from former release (2.4.0) and paste it into _mapbox.android.js_ file in my project.

This solved my problem.

Anyway, the `mapbox.downloadOfflineRegion` method is missing in the latest release (2.5.1).

**Comment by EddyVerbruggen** [comment]
It must have been removed unintentionally. A bit strange... Thanks for bringing this to my attention, I'm re-adding it in 2.5.2.
