### ISSUE TITLE
Not working with Angular2/Typescript?

### ISSUE THREAD

**Issue by marcbruederlin** [Yermo/nativescript-mapbox#9]
I'm trying to use this plugin in an angular 2 typescript project. 

I added the plugin via the `tns plugin add` command and imported it with `var mapbox = require('nativescript-mapbox');` in my component.ts file.
In the angular 2 `ngOnInit` event i call `mapbox.show({
       accessToken: '...'
     });` but i'm getting the following error: 
`Uncaught (in promise): TypeError: Cannot read property 'mapboxsdk' of undefined`

Any idea how to solve this?

**Comment by skdeepak88** [comment]
Are u referencing `mapboxsdk` anywhere ?

**Comment by bloigge** [comment]
I do have the same in plain javascript as well

**Comment by EddyVerbruggen** [comment]
iOS or Android, and are you doing this before `application.start();` perhaps?

**Comment by burkeholland** [comment]
I'm doing it in the constructor without issues. Might want to try moving it there, although I tried with ngInit and it worked fine there as well.

**Comment by smartcris** [comment]
I'm having the same issue  on Android only with plain javascript:
`JS: Error in mapbox.show: TypeError: Cannot read property 'mapboxsdk' of undefined`

**Comment by l3lackcurtains** [comment]
- uninstall the application from device
- remove and add the plugin again
- build the application
- Run it.
  
  **It worked for me, and it works for most of the plugin with such issues.**

**Comment by marcbruederlin** [comment]
Got it. I think the problem was that I forgot to add 

``` xml
<service android:name="com.mapbox.mapboxsdk.telemetry.TelemetryService" />
```

to my `AndroidManifest.xml`.
