### ISSUE TITLE
make sure you add the Telemetry service to your androidManifest.xml

### ISSUE THREAD

**Issue by shyandsy** [Yermo/nativescript-mapbox#90]
- TNS 2.5.2

- ANDROID API 24

- typescript 2.1.6

- test demo program:
[mapbox-error-demo.zip](https://github.com/EddyVerbruggen/nativescript-mapbox/files/814675/mapbox-error-demo.zip)

########################################################

1. I created a test project base on this project

https://github.com/NativeScript/template-hello-world-ts
by
tns create my-app-name --template tns-template-hello-world-ts

2. add the service to AndroidManifest.xml

<service android:name="com.mapbox.mapboxsdk.telemetry.TelemetryService" />

3. then use the following code

<map:Mapbox
          accessToken="your_token"
          mapStyle="light"
          latitude="52.3702160"
          longitude="4.8951680"
          zoomLevel="3"
          showUserLocation="true"
          mapReady="onMapReady">
      </map:Mapbox>

4. I get the error message said "make sure you add the Telemetry service to your androidManifest.xml"

![image](https://cloud.githubusercontent.com/assets/5271457/23520434/9f6ab0c2-ff40-11e6-9f42-9febf6c596d1.png)

the test program is in the attachment, please change to mapbox API token manually.
![image](https://cloud.githubusercontent.com/assets/5271457/23520310/0aa1c804-ff40-11e6-94a7-de70352320d6.png)

=========================

after I add <service android:name="com.mapbox.services.android.telemetry.service.TelemetryService" /> to the AndroidManifest.xml, I got new exception
![image](https://cloud.githubusercontent.com/assets/5271457/23521880/832436c6-ff46-11e6-8f0a-4ece1d996bdc.png)

**Comment by Equisetum** [comment]
See this link: https://github.com/EddyVerbruggen/nativescript-mapbox/issues/78#issuecomment-280910344

**Comment by shyandsy** [comment]
@Equisetum  
i change the service to 
<service android:name="com.mapbox.services.android.telemetry.service.TelemetryService" />
in both androidManifest.xml
but still not working 
![image](https://cloud.githubusercontent.com/assets/5271457/23523924/458ea474-ff4e-11e6-872f-8375a04a3465.png)


try to rebuild 
```
tns build android
```
still not working


try to remove platform and readd platform
```
tns platform remove android
tns platform add android
```
still not working


demo also not working
https://github.com/EddyVerbruggen/nativescript-mapbox-demo/issues/11

**Comment by EddyVerbruggen** [comment]
Working on something similar in #80

**Comment by shyandsy** [comment]
@EddyVerbruggen 
hi i am using Typescript and i saw that #80 using something from nativescript angular

**Comment by shyandsy** [comment]
@EddyVerbruggen  still not working  

![image](https://cloud.githubusercontent.com/assets/5271457/23583188/b095438a-0102-11e7-84c5-2845830bf106.png)


could u check the new version of demo I provided??

[mapbox-error-demo-v2.zip](https://github.com/EddyVerbruggen/nativescript-mapbox/files/819012/mapbox-error-demo-v2.zip)

**Comment by shyandsy** [comment]
got error message "program failed to link at com.mapbox.mapboxsdk.maps.MativeMapView.nativeRender"
![image](https://cloud.githubusercontent.com/assets/5271457/23584131/601bd5e8-011d-11e7-93d3-bbc6e6746d87.png)

code
[mapbox-error-demo-v3.zip](https://github.com/EddyVerbruggen/nativescript-mapbox/files/819077/mapbox-error-demo-v3.zip)

**Comment by EddyVerbruggen** [comment]
That first issue was probably solved, the second may be down to the emulator you use. Did you try this on an Android 4.4 or higher *device*?

**Comment by shyandsy** [comment]
@EddyVerbruggen 
I tried yesterday

the mapbox-error-demo-v3.zip  works correct on real phone, but doesnt work on simulator
